### ISSUE TITLE
`Point` in `PolyArea` different results for different units

### ISSUE THREAD

**Issue by kylebeggs** [JuliaGeometry/Meshes.jl#1010]
There seems to be an issue when converting units in the point in polyarea alg. This is in v0.49.0
```julia-repl
julia> poly = Meshes.PolyArea(Point(-0.5mm, -1mm), Point(0.5mm, -1mm),Point(0.5mm, 1mm),Point(-0.5mm, 1mm))
PolyArea
  outer
  └─ Ring((x: -0.5 mm, y: -1.0 mm), ..., (x: -0.5 mm, y: 1.0 mm))

julia> Point(0.95mm, 0.45mm) ∈ poly
false

julia> Point(uconvert(m, 0.95mm), uconvert(m, 0.45mm)) ∈ poly
true
```

**Comment by kylebeggs** [comment]
If you know right away what the issue is, let me know and I can make a PR tomorrow. If not I'll try to debug tomorrow afternoon or wednesday

**Comment by juliohm** [comment]
Thank you @kylebeggs for reporting. It may be related to the following two lines, but I didn't check:

https://github.com/JuliaGeometry/Meshes.jl/blob/3b25ccefa56a691e486dcf957eb4979c00841918/src/sideof.jl#L102-L103

The `flat` helper function may be ignoring the units somehow.

**Comment by kylebeggs** [comment]
I just checked, `flat` seems to preserve the units of the input (at least testing with m and mm like this example)

**Comment by kylebeggs** [comment]
I was wrong. The issue is `flat`. The docstring for `flat` explicitly says it ignores the units. Should we just convert both geometries to the same units at the start of `sideof`?

**Comment by juliohm** [comment]
Perhaps we should adjust the definition of `flat` to convert to `m` units when possible. There is `CoordRefSystems.units` to extract the units associated with `CoordRefSystems.raw` values. There is also `CoordRefSystems.values` which includes units.

**Comment by kylebeggs** [comment]
I think we should try to preserve the units of the input geometries as much as possible. Say I'm working in femtometers and picometers or something, if we always convert to meters we are going to get a loss in precision and the algorithm may fail, right?

**Comment by juliohm** [comment]
That is a good point. So instead of forcing meters in flat, the suggestion
is to convert the inputs of sideof to the same length unit, right? Maybe
using the LenghtUnit transform?

Em ter., 20 de ago. de 2024, 14:20, Kyle Beggs ***@***.***>
escreveu:

**Comment by kylebeggs** [comment]
Yes, but then the question is if the 2 input geometries are different units, which one do we convert to make them the same?

**Comment by juliohm** [comment]
We should probably introduce a convention for that. One option is to always convert to the unit of the first argument in the list. Another option is to convert to the "finest" unit. I think we can stick to the first option for now, but feel free to add suggestions.
