### ISSUE TITLE
Incorrect parameterization of a `ConeSurface`

### ISSUE THREAD

**Issue by mikeingold** [JuliaGeometry/Meshes.jl#1011]
Calculating the `measure` of a `ConeSurface` seems to produce incorrect results. These results appear to be invariant w.r.t. the base radius but approximate the value expected for a cone whose base has unit radius.

## MWE

```julia
origin = Point(0, 0, 0)
z_axis = Vec(0, 0, 1)
xy_plane = Plane(origin, z_axis)
apex = Point(0, 0, 1)

# Test ConeSurface with radius 1.0
base_disk_10 = Disk(xy_plane, 1.0)
cs_10 = ConeSurface(base_disk_10, apex)

# Test ConeSurface with radius 2.5
base_disk_25 = Disk(xy_plane, 2.5)
cs_25 = ConeSurface(base_disk_25, apex)

# Analytic solution for surface area of a cone (including base)
# let s^2 = r^2 + h^2
#   A = (π * r^2) + (π * r * s)
cs_10_area = 3.142 + 4.443
  # == 7.5844
cs_25_area = 19.635 + 21.147
  # == 40.782

measure(cs_10)
  # == 7.568912593985476 m^2

measure(cs_25)
  # == 7.568912593985476 m^2
```

**Comment by juliohm** [comment]
Thank you @mikeingold , feel free to submit a PR with a fix.

**Comment by mikeingold** [comment]
Running `viz` (GLMakie) on each ConeSurface independently shows the same exact geometry with unit radius. The `ConeSurface` type apparently seems to use the generic `measure` that discretizes the geometry and sums the facet areas which, to my understanding, would utilize the same discretization method used for `viz`.

Debugging the stack...

https://github.com/JuliaGeometry/Meshes.jl/blob/3d403c0893264c6d6122f64b999099320ff6dcad/src/measures.jl#L102

https://github.com/JuliaGeometry/Meshes.jl/blob/3d403c0893264c6d6122f64b999099320ff6dcad/src/discretization.jl#L185

https://github.com/JuliaGeometry/Meshes.jl/blob/3d403c0893264c6d6122f64b999099320ff6dcad/src/discretization.jl#L63

https://github.com/JuliaGeometry/Meshes.jl/blob/3d403c0893264c6d6122f64b999099320ff6dcad/src/discretization/regular.jl#L20-L30

I checked the output of `wrapgrid`, called on line 22, for `cs_25` and found that the base coordinates are incorrectly at unit radius here.

https://github.com/JuliaGeometry/Meshes.jl/blob/3d403c0893264c6d6122f64b999099320ff6dcad/src/discretization/regular.jl#L36-L43

These coordinates fall out of the `sample` call on line 40 when debugging.

https://github.com/JuliaGeometry/Meshes.jl/blob/3d403c0893264c6d6122f64b999099320ff6dcad/src/sampling.jl#L19

https://github.com/JuliaGeometry/Meshes.jl/blob/3d403c0893264c6d6122f64b999099320ff6dcad/src/sampling/regular.jl#L26-L38

Nothing too obvious here, just looks like a regular sampling of the parameterization function...

```julia
cs_25(1,0)
  # Point with Cartesian{NoDatum} coordinates
  # ├─ x: 0.0 m
  # ├─ y: 0.0 m
  # └─ z: 1.0 m
```

:clown_face:

https://github.com/JuliaGeometry/Meshes.jl/blob/3d403c0893264c6d6122f64b999099320ff6dcad/src/geometries/primitives/conesurface.jl#L34-L47

Looks like there's an issue here that is resulting in cones all having unit radius.

I'm out of time for now, but wanted to document this for visibility.

**Comment by mikeingold** [comment]
Looks like this function is generating cross-section planes through the cone, treating the intersection of the plane and the cone as a Circle, and then parameterizing a point on that circle. By my interpretation:
- `v` is a vector pointing from the apex to the center of the base Disk
- `l` is the length of that vector
- `o` is the Point where `v` and the cross-plane should intersect
- `θ` is the cone half-angle
- `r` is supposed to be the radius of the cone-plane intersection circle

It looks to me like line 44's definition of `r` is to blame. I'm not sure how it was derived but I suspect the `cos` should instead be `tan`.

**Comment by juliohm** [comment]
I did a quick sketch here on paper, and believe it should be `sin(theta)`. The hypotenuse is `h * l` and we have `sin(theta) = r / (h*l)`. Appreciate if you can test it locally.

**Comment by juliohm** [comment]
I was wrong, it is not `sin(theta)`. I believe that `theta` itself is defined incorrectly in the code. We need the bisection angle at the apex, not the angle between the normal of the base and the axis.

Appreciate if you can take a closer look at it. I can try to find time next week.

**Comment by mikeingold** [comment]
If I’m interpreting the code correctly, `h` in this code is a parametric argument representing fractional height down the length of the cone, and `l` is distance from apex to the center of the base disk. So, the `h * l` here computes the length along the cone axis where we find the current cross-section of interest. The angle theta is the half-angle at the top/apex, and the goal radius is opposite that angle on the triangle.

**Comment by juliohm** [comment]
Exactly. That is the correct interpretation. The current implementation is using the wrong angle and projection of `h*l` onto the plane of the cone base.

**Comment by mikeingold** [comment]
I may have some time this evening to start a PR for this. I was originally
worried that the issue was buried somewhere in the discretization code that
I'm less familiar with, but I'm comfortable working on parameterizations.

**Comment by mikeingold** [comment]
Update: I derived parametric functions for both cone and cone surface that should work and will help make them easier to define AD rules for. They’re simple enough on paper, so shouldn’t take long to code up and push a PR.
