### ISSUE TITLE
Rotate & color don’t work —— until the mesh is discretized

### ISSUE THREAD

**Issue by ChenZhu-Xie** [JuliaGeometry/Meshes.jl#1025]
An occasional off-topic sub-thread in [Discourse: There’s a hole in a sphere generated by makie.surface](https://discourse.julialang.org/t/theres-a-hole-in-a-sphere-generated-by-makie-surface/118555?u=xczphysics) leads to this problem:

this rotates correctly: 
```
using Meshes, Rotations, GLMakie
Ellipsoid((3., 2., 1.), (0., 0., 0.), RotXYZ(π/4, π/5, π/3)) |> viz
```

but the following doesn't even rotate:
```
using Meshes, Rotations, GLMakie
Ellipsoid((3., 2., 1.)) |> Rotate(RotXYZ(π/4, π/5, π/3)) |> viz
```

However with pre-discretized mesh, it works again:
```
using Meshes, Rotations, GLMakie
discretize(Ellipsoid((3., 2., 1.)), RegularDiscretization(10,10)) |> Rotate(RotXYZ(π/4, π/5, π/3)) |> viz
```

besides, the kwarg `color = 1:nelements(mesh)` of the method `viz` needs `discretize(mesh)` first too:
```
using Meshes, Rotations, GLMakie
ellipsoid = Ellipsoid((3., 2., 1.), (0., 0., 0.), RotXYZ(π/4, π/5, π/3))
ellipsoid = discretize(ellipsoid, RegularDiscretization(10,10))
viz(ellipsoid, color = 1:nelements(ellipsoid), showsegments = true)
```

![image](https://github.com/user-attachments/assets/094b9fc0-eea1-455c-9a82-49a854a9ef07)

**Comment by juliohm** [comment]
Thank you for reporting @ChenZhu-Xie , we will take a look on Monday.
