### ISSUE TITLE
Longitude wrapping breaks `in` for polygons spanning negative and positive longitudes

### ISSUE THREAD

**Issue by disberd** [JuliaGeometry/Meshes.jl#1027]
I realized that when polygons are located around the 180 degrees latitude (like russia's borders), they are automatically split in separate polyareas. The polyarea that sits on the negative longitude part has the artificial border which have a longitude of 180°, while the rest of the vertices have negative longitude.

This breaks the `in` algorithm as basically all longitude within the latitude span become valid.

See this example below where the russia's borders where extracted with `NaturalEarth.countries()` from GeoArtifacts.jl

![image](https://github.com/user-attachments/assets/4e8be78f-0d4c-4f5c-8462-ec39082dfbcd)

You can see this more clearly with the zoom on the incrimnated part of Russia:
![image](https://github.com/user-attachments/assets/91eae540-ed66-4a8c-af03-e5e6e8f7605e)
![image](https://github.com/user-attachments/assets/83a76a85-75d8-4ce8-8787-490149f445a6)

I wonder whether this problem was introduced by my change here https://github.com/JuliaEarth/CoordRefSystems.jl/pull/146 which always made -180 become 180 longitude

<details>
<summary>Example Notebook Code (not fully working notebook to avoid manifest, just paste this in a new notebook)</summary>

```julia
# ╔═╡ e07e7956-6554-11ef-3c4a-35793d7cf60f
begin
	using GeoArtifacts
	using CoordRefSystems
	using Meshes
	using PlutoPlotly
	using CoordRefSystems: Deg
	using Unitful
	using PlutoUI
end

# ╔═╡ 7fcf34c6-99f5-455d-a908-121a66c00277
begin
	_extract(d::Deg) = ustrip(d)
	_extract(l::LatLon) = map(_extract, (l.lat, l.lon))
	_extract(p::Point) = _extract(coords(p))
	_extract(ps::AbstractVector{<:Point}) = map(_extract, ps)
	_extract(p::PolyArea) = mapreduce(_extract, vcat, vertices(p))
	_extract(m::Multi) = mapreduce(vcat, m.geoms) do poly
		vcat(_extract(poly), (NaN, NaN))
	end
	function PlotlyBase.scattergeo(g::Union{<:PolyArea, <:Multi, <:AbstractVector{<:Point}}; kwargs...)
		cs = _extract(g)
		scattergeo(;lat = first.(cs), lon = last.(cs), mode = "lines", kwargs...)
	end
end

# ╔═╡ 6ed36f9a-9d10-4982-b534-0dbdfb7bebbc
begin
	tbl = NaturalEarth.countries(; scale = "1:50")
	countries = tbl.geometry
	russia = countries[76]
end

# ╔═╡ e1225eb0-ead3-4eff-8fcf-06b7fb70abf8
filtered_pts = filter(in(russia), [Point(LatLon(66, lon)) for lon in -179:5:180])

# ╔═╡ 37a0a60d-d65e-4fd0-9c12-4fb87d1f2ab9
plot([
	scattergeo(russia; name = "Russia's borders"),
	scattergeo(filtered_pts; mode = "markers", name = "Filtered Points")
], Layout(;
	legend = attr(;
		xanchor = "right",
		x = 0.99,
		yanchor = "bottom",
		y = 0.4,
		borderwidth = 2,
	)
))
```

</details>

**Comment by disberd** [comment]
In hindsight, while making -180° equal to 180° for the longitude is formally correct, it probably brings more nuisance than usefulness, as it also messes a bit with naive ranges like [LatLon(0, lon) for lon in -180:180] by making the first element equivalent to the last.

**Comment by juliohm** [comment]
We were just investigating this issue. We need to figure out a good strategy to handle these crossings on -180/180.

**Comment by juliohm** [comment]
Fixed upstream: https://github.com/JuliaRegistries/General/pull/114086
