### ISSUE TITLE
Change representation of Line

### ISSUE THREAD

**Issue by serenity4** [JuliaGeometry/Meshes.jl#104]
I know this is breaking, but I have a suggestion for the `Line` data structure. Currently, it stores two points which it crosses. I was thinking of changing the structure as a `Point` and a `Vec`, similar to the `Plane` but in 1D. I feel it would look more natural, be more consistent with the `Plane` object, facilitate evaluation (you won't need to do `b - a` every time) and would make the orientation of the `Line` explicit. Any thoughts on that?

**Comment by juliohm** [comment]
The benefit of `b - a` is that we get back a `Vec` which is a normal `SVector` that works with other Julia functions out there. Also, it seems more usual to construct a line from two points as opposed to a point and a vector. We have `Ray` that is more natural with point and vector. We already have an issue open to discuss Line and Plane representations #90 and so I will close this one.
