### ISSUE TITLE
any interest in Grassmann.jl based mesh?

### ISSUE THREAD

**Issue by chakravala** [JuliaGeometry/Meshes.jl#1099]
[Grassmann.jl](https://github.com/chakravala/Grassmann.jl) has supported its own mesh syntax for years and there is now a newer mesh syntax I developed on top of Grassmann.jl as well, if any serious scientists are interested in that. Grassmann.jl can unify everything geometry related, including meshes and quaternions simultaneously.

**Comment by juliohm** [comment]
Can you please elaborate on your proposal? What is the mesh syntax and how
Grassmann unifies geometry work? Are you proposing to add the package as a
dependency?

Em sex., 4 de out. de 2024, 15:53, Dream Scatter ***@***.***>
escreveu:

**Comment by chakravala** [comment]
My only proposal is that if anybody is interested in this: I am not sharing
these ideas with random people at the moment, but if you want to be an
early adopter, I have mesh tools built up using Grassmann.jl ... I already
was doing this 4 years ago, and I am still doing it today, with my newest
mesh designs 4 years later.

This is entirely separate from Meshes.jl although it supports importing
from Meshes.jl

The purpose is for working with differential geometry with Grassmann.jl,
which works best when the mesh design is based on Grassmann.jl instead of
anything else. So my approach is to always use Grassmann.jl as the starting
point, it has to immediately available at every stage of calculation. So,
it is necessary to build my entirely own mesh system.

My mesh system is not directly inspired by any other mesh system, aside
from the typical features of meshes, so I am not copying anything from
Meshes.jl, it is genuinely from scratch using Grassmann.jl as foundation.

**Comment by juliohm** [comment]
My impression the last time I read Grassmann.jl is that it has a different
audience and requires lot more mathematical maturity, not necessarily
helping the users we have in mind. In any case it would be good to meet to
discuss what do you have in mind in terms of collaboration paths.

This issue can be closed as it is not related to Meshes.jl.

Em sex., 4 de out. de 2024, 20:00, Dream Scatter ***@***.***>
escreveu:

**Comment by juliohm** [comment]
Feel free to reach out over Zulip or over email at juliohm at arpeggeo.tech

**Comment by chakravala** [comment]
You will not be able to discuss with me on Zulip, as I am banned on all
Julia discussion websites, including zulip and all official Julia GitHub
repositories.

This issue is opened on this repository because I am unable to discuss this
on any official Julia chat, as I am banned there.

I am completely unable to join the discussion on zulip or any other Julia
discussion site.

As a result, my project is done in complete isolation from the rest of the
Julia "community"

**Comment by juliohm** [comment]
Reach over e-mail then and we can try to set a video call.

Em sex., 4 de out. de 2024, 22:56, Dream Scatter ***@***.***>
escreveu:

**Comment by chakravala** [comment]
Thank you, I appreciate your interest, afterall I started this discussion.
However, I am not comfortable explaining anything more, unless we have a
trustworthy relationship.

If this is something you wish to pursue, then you need to demonstrate to me
what the nature of your interest in my work is.

I am very happy working alone, I am offering this invitation for the
appropriate situation. so if the situation is appropriate, then we can
arrange a call to discuss it.

I have never had a successful collaboration in the Julia "community" so I
dont expect anything to actually happen.

**Comment by juliohm** [comment]
I understand you don't have the social skills required to promote
collaboration but I'm willing to meet and see what can come out of a chat.
That is it.

If you don't feel comfortable I understand. We will all be fine doing our
work separately.

Em sex., 4 de out. de 2024, 23:17, Dream Scatter ***@***.***>
escreveu:

**Comment by chakravala** [comment]
It's nothing to do with social skills, this is programming work and
intellectual property work ... nothing social about it.

The fact that people equate work with social behavior is very problematic
and leads to most "community" issues.

Free software developers are NOT friends or engaged in social activity.
Free software development is work ... and there is no payment or job which
places us on a team.

I will never consider free software developers my friends, they are all
leeches who take others work for free and build more work on it. There is
nothing social about it. It's all people leeching and being parasites and
doing work.

So no, this has nothing to do with social skills and is only about doing
work.
