### ISSUE TITLE
Separate FEM logic from the mathematical model

### ISSUE THREAD

**Issue by serenity4** [JuliaGeometry/Meshes.jl#11]
As we discussed in #6, it would be nice to clearly separate what is related to FEM from polytope theory. Currently, a `Face` is used to denote the fact that a type is a polytope used in FEM. Then, common polytopes are defined as `Face` subtypes, with a convenience `facets` function that connects all polytope vertices into facets from the GMSH project conventions.

The specificity of `Face` subtypes (as it is in the code) that is related to FEM is just that a mapping is defined from the object type (triangle, tetrahedron...) to an array of `Connectivity` elements (holding each a set of points and the target polytope), according to the GMSH conventions.

A way to go would be to extract this FEM-specific knowledge and put it somewhere else, detached from the actual polytope. Having types for simple polytopes is useful because they have a specific structure that easily allows to build all k-faces from the vertices according to a convention. This convention should be specified by the user, with a default value that can be GMSH's.

Later on, a separate FEM part can define other polytopes that are only relevant in the field. For example, it can be some kinds of "triangles" with more than 3 vertices, possibly including one at the center. They are not triangles in a mathematical sense, because they have more than 3 edges; however, vertices are layed out so that, with a specific connectivity, edges can be defined that can be seen as a triangle. When a center point is defined, it is simply not connected to anything else.
That is, of course, if you consider all FEM points to represent actual vertices. They can just be "points of interest" that have nothing to do with the geometrical shape. In this case, an adequate sampling method, which rely on an ordering convention, should be defined for the relevant polytopes.

**Comment by serenity4** [comment]
I have changes that I still need to put into separate commits before submitting PRs, but it's time to sleep now.

**Comment by juliohm** [comment]
Awesome improvements here. Closing the issue as it is now fixed on master :100:
