### ISSUE TITLE
Inconsistent behaviour between == and isapprox for Line

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGeometry/Meshes.jl#1138]
`Line` objects are defined by two points without considering direction. This means that equal lines have different representations. This works as it should for the `==` operator but not for `isapprox`.

The current implementation of `isapprox` is
```julia
Base.isapprox(l₁::Line, l₂::Line; atol=atol(lentype(l₁)), kwargs...) =
  isapprox(l₁.a, l₂.a; atol, kwargs...) && isapprox(l₁.b, l₂.b; atol, kwargs...)
```

so the issue is that only the points representing the line are compared. Therefore this would also fail if the two points are just reversed for one of the line.

It is not immediately clear to me what a good solution would be but I try to come up with some proposal.

**Edit:** The same seems to be the case for `Ray`. 

## Example

```julia
julia> using Meshes

(@v1.11) pkg> status Meshes
Status `~/.julia/environments/v1.11/Project.toml`
  [eacbb407] Meshes v0.52.4

julia> l1 = Line(Point(0), Point(1))
Line
├─ a: Point(x: 0.0 m)
└─ b: Point(x: 1.0 m)

julia> l2 = Line(Point(0), Point(2))
Line
├─ a: Point(x: 0.0 m)
└─ b: Point(x: 2.0 m)

julia> l1 == l1
true

julia> l1 == l2
true

julia> l1 ≈ l1
true

julia> l1 ≈ l2 # this is inconsistent with the behavior of `==`
false
```

**Comment by juliohm** [comment]
Perhaps we should forward the `isapprox` of `Line` to `==`? Thanks for taking a look into it.

**Comment by simonschoelly** [comment]
I think at least initially that would make sense. For writing tests some approximation might be helpful though. I just checked the `Plane` datatype - this seems to be the same problem just in one dimension higher and there `==` and `isapprox` seem to work correctly.
