### ISSUE TITLE
The type system is an overcomplicated mess

### ISSUE THREAD

**Issue by markmbaum** [JuliaGeometry/Meshes.jl#1150]
I commonly want to dispatch/constrain a function using the underlying numeric type of a simple struct like a `Point`. After the type system was overhauled (a while ago) this became very complicated. Instead of simply using `Point{N,T}` where N is the dimension and T is the numeric type, you have to invoke manifolds (`𝔼`), coordinate reference systems, and unitful numbers. This seems totally unnecessary.

**Comment by juliohm** [comment]
It is certainly necessary if you need to do anything more complicated than
treating points as tuples of numbers.

If you have a specific question, we can help over zulip. Github is not
really a place for gripes.

Em sex., 13 de dez. de 2024, 16:19, Mark Baum ***@***.***>
escreveu:
