### ISSUE TITLE
Should these be abstractvectors instead?

### ISSUE THREAD

**Issue by alok** [JuliaGeometry/Meshes.jl#124]
https://github.com/JuliaGeometry/Meshes.jl/blob/b668e79f7a26ebba8d07d0ced4bf4d9a8024f89f/src/mesh/simplemesh.jl#L15

seems like a free bit of genericity

**Comment by juliohm** [comment]
Can you comment on the use case you have in mind? We plan to refactor this type to use a `ExplicitStructure` for the topology instead of a raw vector of connectivities.
