### ISSUE TITLE
Calculate ray mesh intersection

### ISSUE THREAD

**Issue by jackbeagley** [JuliaGeometry/Meshes.jl#125]
We can already find the intersection between lines, segments and boxes. It would be good to find the intersection between a mesh and a line too (naturally this would involve first finding the intersection, if it exists, between a line and a triangle).
Could use https://github.com/JuliaGeometry/TriangleIntersect.jl

**Comment by juliohm** [comment]
Thank you @jackbeagley for the feature request. Would you like to submit a PR with the proposed method? Notice that we have three different concepts in the codebase already: Line, Segment, Ray. These are not the same concept and it seems that the TriangleIntersect.jl package provides an intersection between Ray and Triangle. Make sure you implement the correct method in the PR if you are willing to contribute.

**Comment by jackbeagley** [comment]
Point taken regarding the different concepts! I'll have a crack at it and hopefully have a PR at some point to it.

**Comment by jackbeagley** [comment]
So I have written most of the code for this, but while testing `intersect(segment, mesh)` or equivalently `intersect(ray, mesh)`. I found that `SimpleMesh` is not a subtype of `Geometry`, which seems strange to me, surely an object made up of `Geometry` is itself `Geometry`? At any rate is it best to define another method for `intersect`, something like `Base.intersect(g::Geometry, m::SimpleMesh)` or does it make sense to make `SimpleMesh` a subtype of `Geometry`?

**Comment by juliohm** [comment]
Currently we have methods for `intersect(geometry, domain)` [here](https://github.com/JuliaGeometry/Meshes.jl/blob/6d5d758adf98bf75545e4ab0b89561b7e4d11a31/src/intersections.jl#L164). The current design makes a distinction between collections of geometries (a domain) such as meshes and the geometries themselves. We can always revise the design if there is a good reason. Experience has shown that we don't gain much by trying to subtype everything as a Geometry.

**Comment by jackbeagley** [comment]
That method only checks if there is an intersection though (returning `true` or `false`), rather than returning the actual intersection. Seems like the way forward might be to implement `Base.intersect(g::Geometry, d::Domain)`?

**Comment by juliohm** [comment]
Yes, I think it is a good way to get it started.

**Comment by juliohm** [comment]
@jackbeagley did you solve this issue already or still missing some methods? :)

**Comment by jackbeagley** [comment]
@juliohm I think everything else is implemented in my fork (for segment and mesh at least), but I'm leaving civilisation tomorrow for four weeks, so even though it's close I just really don't have time to sort it out till then!

**Comment by juliohm** [comment]
Enjoy your vacation @jackbeagley ! 🎉

**Comment by juliohm** [comment]
@HaoxuanGuo I think we are ready for the grand finale here? We have ray-triangle intersection and can do it for all triangles in a mesh right? The result would be a new mesh with only the triangles intersected?

**Comment by juliohm** [comment]
I am actually wondering if we should provide such an intersection method between a `ray` and a full `mesh` or let the users do the loop by hand on their scripts. If we provide an intersection method here then the proposed design in #54 would be problematic. Maybe we could assume that users will write `[intersect(ray, triangle) for triangle in mesh]` to get what they need?

**Comment by GuoHaoxuan** [comment]
@juliohm  Yes, we are only one step away from the finale. But I am thinking about how to complete this last step. Should we treat the mesh as a surface or a solid? If it is a surface, the intersection of the ray and the grid should be a series of points; if it is a solid, it should be a series of line segments. Obviously, intuitively it should be considered a solid, but sometimes the grid is not closed.

If the intersection is calculated only once, any acceleration technique is futile. Simply intersect the ray with each face of the mesh. The face of a polygon can always be decomposed into multiple triangles.

**Comment by GuoHaoxuan** [comment]
In addition, in most cases. The user should build a scene with multiple grids, and then calculate the intersection of the ray and the scene. The scene is not moving at this time, and there will be many rays. At this point, the scene can be cached with an efficient data structure to make the whole faster. But this should not be a problem we are discussing here, but a problem that needs to be solved by users themselves.

**Comment by juliohm** [comment]
Very interesting point @HaoxuanGuo. I think we have surface meshes `paramdim(mesh) == 2` and volume meshes `paramdim(mesh) == 3` in our design, so each case would require a different algorithm. I was thinking about the surface case first, which is simpler I think. Still, in the surface case I think we can just let users use our intersection methods between geometries to build intersection in a full mesh? These are good questions to discuss 👍🏽

**Comment by GuoHaoxuan** [comment]
Users may write code below:

```julia
scene = RTree(meshs)
intersect_points = [r \cap scene for r in rays]
```

But `RTree` or others data structures should not be implemented in our package.

If he just want to calculate one ray intersects one mesh, he can write `[intersect(ray, triangle) for triangle in mesh]` easily.

**Comment by juliohm** [comment]
That is true. We could wrap some of these packages containing efficient data structures implemented in terms of StaticArrays.jl to provide a high-level interface in the future. For now, I think it makes sense to leave this feature to end users, specially because it seems very specific to visualization pipelines. Should we close this issue for now then?

**Comment by GuoHaoxuan** [comment]
Yes, we should close this issue.

**Comment by juliohm** [comment]
Closing for now 👍🏽

**Comment by jackbeagley** [comment]
Interesting discussion! @HaoxuanGuo your assumptions were the opposite of mine, my use case was propagating sound waves throughout a basin (an open mesh), so I was looking for a single intersection (a point) and assuming the mesh to be a surface. I think that is more evidence that it should be left to the user though. (Unless we allowed multiple options to choose from in the future?)

Thanks guys!
