### ISSUE TITLE
Simple mesh returning empty for 3D input

### ISSUE THREAD

**Issue by cgscheidle** [JuliaGeometry/Meshes.jl#131]
I am currently trying to create a triangular mesh for points in 3D. I am using Julia 1.6.0 with Meshes v0.12.8 and Pluto v0.14.4. However, the code only returns a SimpleMesh without elements.

```
let
points = Point3[(1.0, 0.0 ,0.0); (0.0, 1.0 ,0.0); (0.0, 0.0, 0.0); (0.0, 0.0, 1.0)]
connec = connect.([(1,2,3), (1,2,4)], Triangle)
tri = SimpleMesh(points, connec)
end
```

> Output: 
> 0 SimpleMesh{3,Float64}
>   4 vertices
>     └─Point(1.0, 0.0, 0.0)
>     └─Point(0.0, 1.0, 0.0)
>     └─Point(0.0, 0.0, 0.0)
>     └─Point(0.0, 0.0, 1.0)
>   2 faces
>     └─Meshes.Triangle(1, 2, 3)
>     └─Meshes.Triangle(1, 2, 4)

How can I fix the problem as I really like the overall package? 

Thank you in advance!

**Comment by juliohm** [comment]
Hi @cgscheidle you created two triangles in 3D space, that doesn´t make a 3D mesh. You have to use 3D polytopes such as Tetrahedron, Pyramid, etc to create 3D meshes. Please feel free to ask more questions on Zulip.
