### ISSUE TITLE
Fix angle between 3D vectors

### ISSUE THREAD

**Issue by juliohm** [JuliaGeometry/Meshes.jl#135]
We need to fix the current implementation to return the correct oriented angle.

Feel free to tackle the issue if you have time available.

**Comment by lmejn** [comment]
I'd be happy to have a go at this, but I can't seem to reproduce an incorrect result. Are you referring to the `∠` function? https://github.com/JuliaGeometry/Meshes.jl/blob/f78377cc83cb3dc3976aee425faaf8031de3a6ee/src/angles.jl#L25-L28
Would you able to provide an example of when the angle calculation is incorrect?

**Comment by juliohm** [comment]
Hi @lmejn , thanks for checking the issue. If I remember correctly we would like to have this angle function behaving like it behaves in 2D. That is, we wanted it to return the angle in a specific orientation, but I guess it depends on arbitrary choices of reference. In 2D when you type `∠(A, B, C)` that is different than `∠(C, B, A)`. Maybe we should forget about this behavior in 3D and always return the smallest angle as we currently do?

**Comment by lmejn** [comment]
Ah I see. Yes, this would depend on the arbitrary choice of reference: the angle from `∠(A, B, C)` could be measured about either normal vectors, `BA × BC` or `BC × BA` (which of course equals `-(BA × BC)`).

[One way to get a signed angle](https://stackoverflow.com/a/33920320) would be to give a reference unit vector (`vref`):
```julia
function ∠(A::P, B::P, C::P, vref::Vec) where {P<:Point{3}}
  BA, BC = A - B, C - B
  atan((BA × BC) ⋅ vref, BA ⋅ BC)
end
```
To get the angle between vectors, `vref` should be the vector normal to `BA`, `BC`, but you can decide which normal.

I can't think of a case where this would be useful though. I would be inclined to forget about this behaviour, unless there is an actual use case for this kind of computation.

**Comment by juliohm** [comment]
You are correct @lmejn , I think this behavior is not motivated by any algorithm we've implemented so far. I will close the issue and we can re-open if it becomes relevant.
