### ISSUE TITLE
Documentation: styling in dark mode

### ISSUE THREAD

**Issue by cormullion** [JuliaGeometry/Meshes.jl#138]
The documentation looks like it's good, but it needs more attention to the styling when viewed in Dark Mode (which I suspect is increasingly common):

Links too dark:

<hr />

<img width="829" alt="Screenshot 2021-05-27 at 14 50 24" src="https://user-images.githubusercontent.com/52289/119837891-dfc0fb80-befa-11eb-9aae-f486b88deb25.png">

<img width="864" alt="Screenshot 2021-05-27 at 14 59 15" src="https://user-images.githubusercontent.com/52289/119839500-1e0aea80-befc-11eb-856e-724d0a5b371e.png">

<hr />

Types too dark:

<img width="802" alt="Screenshot 2021-05-27 at 14 51 12" src="https://user-images.githubusercontent.com/52289/119838031-fcf5ca00-befa-11eb-92b3-c73b9cf09d23.png">

<hr />

Inline code difficult to read:

<img width="815" alt="Screenshot 2021-05-27 at 14 50 39" src="https://user-images.githubusercontent.com/52289/119837937-e94a6380-befa-11eb-96a5-d32a56ce633c.png">

You can use [this site](https://color.a11y.com) to check for accessibility.

**Comment by juliohm** [comment]
Thank you @cormullion for pointing the issue. Do you have suggestions for improving the dark theme? I am not very good with themes so any help is highly appreciated.

**Comment by cormullion** [comment]
I'm not very good with CSS, and you've got CSS and SCSS files in action, but according to a quick look with the Web Inspector:

<img width="1248" alt="Screenshot 2021-05-27 at 16 32 50" src="https://user-images.githubusercontent.com/52289/119854706-35040980-bf09-11eb-9ff8-0182431339ee.png">

you're picking up dark blues and purples for the anchors. Changing that to `#eee` or similar should get you light coloured text.

**Comment by juliohm** [comment]
Thank you @cormullion , mind submitting a PR with improvements? You know much better how to choose these. I'd be happy to merge the changes.

**Comment by cormullion** [comment]
I made some attempts at doing this, but it looks like the docs use SCSS as well as CSS and uses also Documenter tools I'm not familiar with, so a simple edit to the CSS (like I do for my packages) didn't work.So  I'll have to bow to someone else's expertise here...:)

**Comment by juliohm** [comment]
I remember we only need to edit the SCSS file. Documenter.jl will consume this file and will produce the CSS file in the correct folder. Do you know where in the SCSS file the changes are necessary? We could try to open a PR and see if the build is successful updating the docs dark theme.

**Comment by cormullion** [comment]
If you change line 12 of `meshes-dark.scss` to a brighter color, like this:

<img width="840" alt="Screenshot 2021-05-30 at 15 28 03" src="https://user-images.githubusercontent.com/52289/120108137-c23e9c80-c15b-11eb-9fff-06a647cdb066.png">

you can get more visible links:

<img width="852" alt="Screenshot 2021-05-30 at 15 27 20" src="https://user-images.githubusercontent.com/52289/120108138-c4a0f680-c15b-11eb-8520-15e09577d55b.png">

This is the only change I think you'll need to do. I wish I understood this SCSS stuff better...

**Comment by juliohm** [comment]
Will test locally, thanks for the suggestion :)

**Comment by juliohm** [comment]
Much better indeed! Fixed on master 👍🏽
