### ISSUE TITLE
Mesh plotting

### ISSUE THREAD

**Issue by henry2004y** [JuliaGeometry/Meshes.jl#143]
Hi,

I see there's now a recipe for plotting meshes. However, why can't I reproduce the mesh plot in the documentation with Plots.jl GR backend?
```julia
using Meshes, Plots

points = Point2[(0,0),(1,0),(0,1),(1,1),(0.25,0.5),(0.75,0.5)]
connec = connect.([(1,2,6,5),(2,4,6),(4,3,5,6),(3,1,5)], Ngon)
mesh = SimpleMesh(points, connec)
plot(mesh)
```

What I see is the following:
![mesh](https://user-images.githubusercontent.com/20110816/121241560-3f78b880-c8a4-11eb-8bd5-26a061bd91f4.png)

I also tried some other meshes, but still there were only filled planes. Do I need another plotting method beside `plot(mesh)`?
Tried on Linux and Windows, with Julia 1.6.1, Meshes v0.16.4, Plots v1.16.3.

**Comment by juliohm** [comment]
Hi @henry2004y , we set a few options by default in the docs to show the edges:

```julia
plot(mesh, linecolor=:black, fillcolor=:gray90)
```

However we don't know if we should maintain these Plots.jl recipes now that we have MeshViz.jl for plotting 3D meshes with Makie: https://github.com/JuliaGeometry/MeshViz.jl

**Comment by henry2004y** [comment]
Glad to see the recipes for Makie! Makie is still quite slow to start, but the 3D figures looks so much better. One thing that confused me in MeshViz.jl was that `import GLMakie` seemed to be required: `using Makie` would not work. Is that how the recipe system for Makie behaves currently?

**Comment by visr** [comment]
Yes, to be able to plot you need to use one of the Makie backends directly, see also https://makie.juliaplots.org/stable/.
