### ISSUE TITLE
Add split for polygons

### ISSUE THREAD

**Issue by juliohm** [JuliaGeometry/Meshes.jl#145]
It would be useful to define a split function that takes a polygon (possibly with holes), builds bridges to transform it into a single outer boundary, and then splits it into two "halves" with an algorithm similar to the algorithm implemented in Dehn1899. This split operation can be used to speed up the `hasintersect` implementation which currently checks all triangles in a triangulation. We should instead check the halves.

**Comment by serenity4** [comment]
So the idea is to use this feature to apply a dichotomy for finding intersections?

**Comment by juliohm** [comment]
Exactly, like a binary search on geometries. Currently we just triangulate and query every triangle which is not ideal. We could simply split in half and perform two queries recursively.

**Comment by juliohm** [comment]
Just to clarify even further, the triangulation is only performed for non-convex geometries. Convex geometries are tested directly with the GJK algorithm.

**Comment by juliohm** [comment]
The original algorithm I had in mind doesn't work in general, for example in the presence of holes. After we split, there is no clear method to undo the bridges. Perhaps we will need to stick with the triangulation for non-convex geometries for now. If you know some clever split of a polygon with holes into two halves, please let me know. I will close the issue tomorrow otherwise and focus on other missing features.
