### ISSUE TITLE
Iterators make the world a better place

### ISSUE THREAD

**Issue by mohdibntarek** [JuliaGeometry/Meshes.jl#147]
I think it would be great to have more iterators here.
- Element/face/edge/node iterators for a  grid
- Face/edge/node iterator for an element
- Edge/node iterator for a face, and
- Node iterator for an edge

Is there such functionality already in other packages?

**Comment by juliohm** [comment]
Yes, we have most of these iterators for SimpleMesh already. We are in the process of adding them to CartesianGrid if not available yet. Can you please share some example that is not working?

**Comment by mohdibntarek** [comment]
I was looking for an edges iterator for elements so I created #150 .

**Comment by juliohm** [comment]
If you can point out specific iterators that are not working, we can work on them, and help is super welcome. I will close the issue and we can continue the discussion over Zulip.
