### ISSUE TITLE
Should a Segment use a 2-tuple instead of a vector?

### ISSUE THREAD

**Issue by mohdibntarek** [JuliaGeometry/Meshes.jl#148]
A Segment is currently a wrapper around a vector but its description implies it's a collection of 2 points.

**Comment by juliohm** [comment]
A SVector is a tuple with support to LinearAlgebra. So whenever we are storing objects that will be subject to algebraic calculations, we use a SVector. There is no performance penalty and you can convert back and forth between the two, for example `Tuple(svec)`.
