### ISSUE TITLE
topology doesn't support CartesianGrid

### ISSUE THREAD

**Issue by mohdibntarek** [JuliaGeometry/Meshes.jl#149]
```julia
julia> grid = CartesianGrid((100,100),(0.,0.),(1.,1.));

julia> topology(grid)
ERROR: MethodError: no method matching topology(::CartesianGrid{2, Float64})
Closest candidates are:
  topology(::Meshes.SimpleMesh) at /Users/mohd/.julia/dev/Meshes/src/mesh/simplemesh.jl:23
Stacktrace:
 [1] top-level scope
   @ REPL[10]:1
```

**Comment by mohdibntarek** [comment]
Renamed the issue.

**Comment by juliohm** [comment]
We are in the process of adding a method for CartesianGrid. Take a look at GridTopology. You should be able to add a method `topology(grid::CartesianGrid) = GridTopology(size(grid))`. It would be nice if you could submit a PR with this addition and a couple of tests.

**Comment by mohdibntarek** [comment]
Sure, this is great!

**Comment by juliohm** [comment]
@mohamed82008 can I assign this issue to you? It should be easy to fix. We just need the method above and a couple of tests to make sure things are working.

**Comment by mohdibntarek** [comment]
Sure
