### ISSUE TITLE
Centroid of domain doesn't weigh the element centroids by their measures

### ISSUE THREAD

**Issue by mohdibntarek** [JuliaGeometry/Meshes.jl#151]
I am assuming this is by design but should it be?

**Comment by juliohm** [comment]
That is a good point. Can you double check where the method is being called
before submitting a PR?

**Comment by mohdibntarek** [comment]
Not many places, I think only in the intersection and partition functions.

**Comment by mohdibntarek** [comment]
The multi-element centroid I mean.

**Comment by juliohm** [comment]
I am thinking about this. The centroid currently works with any kind of domain, even when the elements are points in a PointSet (i.e. 0 measure). Can you share a pathological case where the current centroid fails badly?

**Comment by mohdibntarek** [comment]
Depends on how you define failure. An incorrect centroid is possible. Think of a large element and a very thin one. The centroid returned will be way off its true value.

**Comment by juliohm** [comment]
Yes, I was just wondering about the use cases, but I think using measures as weights makes sense in general. Happy to review a PR with this adjustment. 👍🏽
