### ISSUE TITLE
Helper function to return the normal of a triangle

### ISSUE THREAD

**Issue by jackbeagley** [JuliaGeometry/Meshes.jl#153]
I have written a function useful for some other code I am writing to calculate the normal of a triangle in three dimensions (normal(t::Triangle{3})), is this something that belongs in Meshes.jl? And if so where?

**Comment by juliohm** [comment]
Definitely. It would be nice to have this function implemented 💯 Given that we don't have other normal methods implemented yet, I think it is fine to add the function to ngon.jl directly. We can find a different source file later if necessary.

**Comment by juliohm** [comment]
Fixed on master.
