### ISSUE TITLE
Instantiate Segments with point, direction and length

### ISSUE THREAD

**Issue by jackbeagley** [JuliaGeometry/Meshes.jl#160]
For a project I am working on it is more intuitive for me to describe segments as a starting point, direction and length. Would creating segments in this manner be a welcome feature in Meshes.jl?

**Comment by juliohm** [comment]
I think it is a bit unnatural to instantiate a segment like this. You should probably create a helper function locally to make the conversion: `create_segment(start, dir, len) = Segment(start, start + len*dir)`

**Comment by juliohm** [comment]
Maybe you are interested in a `Ray` instead?

**Comment by jackbeagley** [comment]
I definitely want a segment, mostly for the fact they have a finite length, will just use a local helper function, that's easy. Cheers!
