### ISSUE TITLE
Missing Makie recipe for Box

### ISSUE THREAD

**Issue by juliohm** [JuliaGeometry/Meshes.jl#167]
We need a recipe for Box in MeshViz.jl. This could be accomplished by simply providing a method to convert Box to Quadrangle or Hexahedron.

**Comment by GuoHaoxuan** [comment]
I tried this and find it works perfectly.

```julia
box = Box((0,0,0), (1,1,1))
viz(box)
```

No error. Was it forgot to close?

**Comment by juliohm** [comment]
Oh yes, we fixed that one as well :) Thanks for going through the issues, really helpful.

**Comment by GuoHaoxuan** [comment]
@juliohm I found `showfacets` not worked while showing a `Box`. Is this issue should be re-open?

**Comment by juliohm** [comment]
It is because the option shows the facets of the mesh, which are the
polytopes with dimension N-1 where N is the parametric dimension. In this
case a 3D box has 2D facets that are already shown. To see the edges you
can viz(boundary(box), showfacets=true)
