### ISSUE TITLE
Add transparency option to Makie recipes

### ISSUE THREAD

**Issue by juliohm** [JuliaGeometry/Meshes.jl#168]
We need to add an option in MeshViz.jl to plot with transparency.

**Comment by GuoHaoxuan** [comment]
I think transparency is a part of color.

```julia
viz(Triangle((1.0,0.0,0.0), (0.0,1.0,0.0), (0.0,0.0,1.0)), color=colorant"rgba(255,0,0,0.2)")
```

Works well.

**Comment by juliohm** [comment]
I think an attribute like `transparency` or `alpha` would still be useful to do this behind the scenes for the user. This is particularly useful when we are visualizing a full mesh and want to color elements with a given color each.

Right now we are specifying `color` as a generic attribute that can contain either Colors.jl or normal `Number` values. I think we need to solve this issue in two steps: (1) create a new attribute that takes `Vector{Number}` and converts to `Vector{Color}` given a colorscale, and (2) crate a new attribute `transparency` that takes the resulting vector of color and creates the transparency channel.

**Comment by juliohm** [comment]
Fixed in the master branch of MeshViz.jl. Now we can pass a global transparency `alpha = 0.5` for all elements of the mesh or a vector of transparency for individual elements:

```julia
using Meshes, MeshViz

import CairoMakie as Mke

g = CartesianGrid(10, 10, 10)

viz(g, color = 1:1000, alpha = rand(1000))
```
![grid](https://user-images.githubusercontent.com/3345261/165387871-0b00ecd4-0cf7-4be7-bc00-1dafc48a6715.png)
