### ISSUE TITLE
SimpleMesh fails with generic Vector{Connectivity}

### ISSUE THREAD

**Issue by deltaeecs** [JuliaGeometry/Meshes.jl#177]
With
`vertices = Point3[(0, 0 , 0), (1, 0, 0), (1, 1, 1), (0, 1, 0)]`
`elements = connect.([(1,2,3,4),(3,4,1)], [Tetrahedron, Triangle])`
`SimpleMesh(vertices, elements)`

I got output

> ERROR: TypeError: in new, expected FullTopology{Connectivity}, got a value 
of type FullTopology{Connectivity{Tetrahedron, 4}}
Stacktrace:
 [1] SimpleMesh (repeats 2 times)
   @ C:\Users\delta\.julia\packages\Meshes\LXhFZ\src\mesh\simplemesh.jl:20 
[inlined]
 [2] SimpleMesh(points::Vector{Point3}, connec::Vector{Connectivity})      
   @ Meshes C:\Users\delta\.julia\packages\Meshes\LXhFZ\src\mesh\simplemesh.jl:25
 [3] top-level scope
   @ REPL[51]:1

using Hexahedron lead to the same result

Julia version info

> Julia Version 1.7.0-rc1
Commit 9eade6195e (2021-09-12 06:45 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
  JULIA_PKG_SERVER = https://mirrors.tuna.tsinghua.edu.cn/julia

**Comment by juliohm** [comment]
Thank you for reporting the issue @deltaeecs , it seems like a simple issue with inner vs. outer constructors in SimpleMesh + FullTopology, but I will try to find the time look at it soon.

@serenity4 do you have any free time available to take a look at it today? I ran the example quickly in the debugger and for some reason the Julia compiler is trying to call a convert method for `FullTopology` even when the field is already of that type.

**Comment by serenity4** [comment]
I am a bit busy at the moment but I might be able to take a look at it this week-end.

**Comment by juliohm** [comment]
@deltaeecs feel free to submit a PR if you have time and knowledge to fix the issue. We are both quite busy this week and so will only be able to take a look at this over the weekend.

**Comment by deltaeecs** [comment]
> @deltaeecs feel free to submit a PR if you have time and knowledge to fix the issue. We are both quite busy this week and so will only be able to take a look at this over the weekend.

I find that this bug happens when mixed meshes are used in Connectivity, like triangle and  tetrahedron/tetrahedron.
The _elms_ in  FullTopology will just count the 3D ones when using mixed Connectivity.
Therefore I located the problem in the bolded line below.

> `struct FullTopology{C<:Connectivity} <: Topology
>   \# input fields
>   connec::Vector{C}
> 
>  \# state fields
>   ranks::Vector{Int}
>   elms::Vector{Int}
> 
>   function FullTopology{C}(connec) where {C}
>     ranks = [paramdim(c) for c in connec]
>     elms  = **findall(isequal(maximum(ranks)), ranks)**
>     new(connec, ranks, elms)
>   end
> end

`
But I'm not sure what does _elms_ exactly mean here, and therefore unable to fix it. Could you provide some tips here so that I can continue here? Thx!

**Comment by deltaeecs** [comment]
> @deltaeecs feel free to submit a PR if you have time and knowledge to fix the issue. We are both quite busy this week and so will only be able to take a look at this over the weekend.

Sorry for the incomplete conclusion above, it seems to be a convert related problem as you mentioned earlier. 
I tried this 
```
 points = rand(Point3, 6) 
 eles = connect.([(1,2,3,4),(3,4,5,6)], Tetrahedron) 
 SimpleMesh(points, eles)`
```

it outputs correct results

> 2 SimpleMesh{3,Float64}
  6 vertices
    └─Point(0.615631852114589, 0.8805637239819214, 0.8934766577896559)
    └─Point(0.3245135056703887, 0.13901388286531857, 0.7539999536877902)        
    └─Point(0.5667319178567357, 0.8999722406298878, 0.40825801340369283)        
    └─Point(0.7338200333739044, 0.17315479327634709, 0.2878009111818829)        
    └─Point(0.7090726490231214, 0.7457584946718475, 0.7298570673316036)
    └─Point(0.28301664652631753, 0.0908332649319249, 0.3165917792011975)        
  2 elements
    └─Tetrahedron(1, 2, 3, 4)
    └─Tetrahedron(3, 4, 5, 6)

But when I change eles into 
```
eles2 = Vector{Connectivity}(undef, 2)
eles2 .= eles
SimpleMesh(points, eles2)
```
The same bug appears

> ERROR: LoadError: TypeError: in new, expected FullTopology{Connectivity}, got a 
value of type FullTopology{Connectivity{Tetrahedron, 4}}
Stacktrace:
 [1] SimpleMesh (repeats 2 times)
   @ C:\Users\delta\.julia\packages\Meshes\LXhFZ\src\mesh\simplemesh.jl:20 [inlined]
 [2] SimpleMesh(points::Vector{Point3}, connec::Vector{Connectivity})
   @ Meshes C:\Users\delta\.julia\packages\Meshes\LXhFZ\src\mesh\simplemesh.jl:25
 [3] top-level scope
   @ c:\Users\delta\OneDrive - pku.edu.cn\Codes\Julia\MoM\src\MeshFileReader.jl:106

Datatype of  `eles` and  `eles2` are
>julia> typeof(eles)
Vector{Connectivity{Tetrahedron, 4}} (alias for Array{Connectivity{Tetrahedron, 4}, 1})
>julia> typeof(eles2)
Vector{Connectivity} (alias for Array{Connectivity, 1})

Datatype of relative FullTopology `ft1` and `ft2` are
```
ft1 = FullTopology(eles)
ft2 = FullTopology(eles2)
typeof(ft1)
typeof(ft2)
```
>julia> typeof(ft1)
FullTopology{Connectivity{Tetrahedron, 4}}
>julia> typeof(ft2)
FullTopology{Connectivity}

When constructing SimpleMesh with FullTopology, results are 
>julia> SimpleMesh(points, ft1)
2 SimpleMesh{3,Float64}
  6 vertices
    └─Point(0.615631852114589, 0.8805637239819214, 0.8934766577896559)
    └─Point(0.3245135056703887, 0.13901388286531857, 0.7539999536877902)        
    └─Point(0.5667319178567357, 0.8999722406298878, 0.40825801340369283)        
    └─Point(0.7338200333739044, 0.17315479327634709, 0.2878009111818829)        
    └─Point(0.7090726490231214, 0.7457584946718475, 0.7298570673316036)
    └─Point(0.28301664652631753, 0.0908332649319249, 0.3165917792011975)        
  2 elements
    └─Tetrahedron(1, 2, 3, 4)
    └─Tetrahedron(3, 4, 5, 6)

>julia> SimpleMesh(points, ft2)
ERROR: TypeError: in new, expected FullTopology{Connectivity}, got a value of type FullTopology{Connectivity{Tetrahedron, 4}}
Stacktrace:
 [1] SimpleMesh (repeats 2 times)
   @ C:\Users\delta\.julia\packages\Meshes\LXhFZ\src\mesh\simplemesh.jl:20 [inlined]
 [2] top-level scope
   @ REPL[84]:1

which really confuses me.
I'd like to help but I don't understand why the convert method called here, hope these information could help you.

**Comment by juliohm** [comment]
Thank you @deltaeecs, I am also wondering why the convert method is being called here given that the type of the field in `SimpleMesh` is a parameter `TP <: Topology` and should accept any type of `FullTopology` even the one with heterogeneous types of elements.

Notice that the code also fails when you replace `Tetrahedron` by `Quadrangle`, and that discards the hypothesis that the bug is specific to 3-rank polytopes (i.e. 3D elements).

If you can ask in Julia forums for help, that would be great. Try the Zulip or Discourse for Julia.

I think the issue may be related to the simple existence of this method:

https://github.com/JuliaGeometry/Meshes.jl/blob/6dc46d3c952f0733eded54a286fd447b12d46de6/src/topologies/full.jl#L59-L62

**Comment by serenity4** [comment]
I had a brief look and defining `Base.convert(::Type{T}, t::T) where {T<:Topology} = t` seems to fix the issue.
I have no idea why this overload is necessary though, as we already have `Base.convert(::Type{T}, ::T)` in `Base`. Looks like the `convert` method you linked is indeed found to be more specific, which expectedly triggers a bug.

**Comment by juliohm** [comment]
Interesting @serenity4, should we double check with the community why the conversion is being attempted by the compiler before we submit a fix here? I also find it strange that we need to manually define a conversion method for Polytope given that the Base method is a catch-all method.

**Comment by juliohm** [comment]
@serenity4 I tried adding the convert method as you described but it didn't fix the issue for me. Could you please double check?

**Comment by serenity4** [comment]
Oh, indeed, sorry the overload should be for `FullTopology`:
```julia
Base.convert(::Type{T}, t::T) where {T<:FullTopology} = t
```

**Comment by serenity4** [comment]
MWE for the issue:

```julia
abstract type SuperType end

struct MyType{T} <: SuperType end

function Base.convert(::Type{<:MyType}, t::SuperType)
  println("Converting")
  MyType{Int}()
end

convert(MyType{Int32}, MyType{Int32}())
# goes through the `convert` method we just added instead of `Base.convert(::Type{T}, ::T)`
```

**Comment by serenity4** [comment]
Posted on [Discourse](https://discourse.julialang.org/t/specificity-of-binary-method-with-diagonal-type-specification-for-dispatch/70281). There's probably a reason for this behavior, but I have no idea what would be the logic to back this up.

**Comment by serenity4** [comment]
Alright, so it seems diagonal type restrictions are less specific than subtype relations. An alternative and possibly better fix for the issue is to change [this line](https://github.com/JuliaGeometry/Meshes.jl/blob/master/src/topologies/full.jl#L59) with `function Base.convert(::Type{FullTopology}, t::Topology)`. It would make sense to me as we don't know what connectivity type will be present in the resulting `FullTopology` anyway.

**Comment by juliohm** [comment]
Awesome, thank you for the help. Mind submitting a PR fixing all convert
methods for Topology types?
