### ISSUE TITLE
\in method for Point in Segment

### ISSUE THREAD

**Issue by ErickChacon** [JuliaGeometry/Meshes.jl#185]
This method is missing. However, this can be easily achieved by defining a segment with the same point:

```julia
s1 = Segment(P2(0,0), P2(1,1))
p1 = Point(0.5,0.5)
!isnothing(intersect(s1, Segment(p1, p1)))
```
I am not sure if that it is the right approach, might be better to have methods for Point with Segment, and use it in Segment with Segment?

**Comment by juliohm** [comment]
Yes, I agree that using a complicated intersection algorithm to find if a point is in a segment feels like a big hammer to solve a small problem. If you know a more specific algorithm that is more efficient as well, please use that instead.

**Comment by ErickChacon** [comment]
Ok, I will consider that. BTW, do you have access to the paper used for segments "A robust method for calculating
  the simplicity and orientation of planar polygons"?

**Comment by juliohm** [comment]
I present to you the awesome SciHub :D

https://sci-hub.ru/

You can type in any DOI, title, etc and it will return the paper with high chance.

**Comment by ErickChacon** [comment]
I could not access it previously. Anyway, I think it would be better to start with a collinear method? That is probably being used for the intersection of segments already.

**Comment by juliohm** [comment]
Feel free to choose a simple method, the simpler the better. We value performance and correctness, and if it is simple, that is the best.

**Comment by juliohm** [comment]
@ErickChacon any update on this?

**Comment by juliohm** [comment]
This is fixed on master.
