### ISSUE TITLE
SimpleMesh failed when types of inputs are AbstractVector{<:Point} and ::TP

### ISSUE THREAD

**Issue by deltaeecs** [JuliaGeometry/Meshes.jl#187]
When I construct a volume cell with view of points and then use function **_boundary_** to generate its boundaries
```
nodes = rand(Point3, 4)
tetra = Tetrahedron(view(nodes, 4:-1:1))
facets = boundary(tetra )
```
I get error message
```
ERROR: MethodError: no method matching SimpleMesh(::SubArray{Point3, 1, Vector{Point3}, Tuple{StepRange{Int64, Int64}}, true}, ::FullTopology{Connectivity{Triangle{Dim, T} where {Dim, T}, 3}})
Closest candidates are:
  SimpleMesh(::AbstractVector{<:Point}, ::AbstractVector{<:Connectivity}) at C:\Users\12253\.julia\packages\Meshes\GrGir\src\mesh\simplemesh.jl:25
  SimpleMesh(::Array{Point{Dim, T}, 1}, ::TP) where {Dim, T, TP<:Topology} at C:\Users\12253\.julia\packages\Meshes\GrGir\src\mesh\simplemesh.jl:20
Stacktrace:
 [1] SimpleMesh(points::SubArray{Point3, 1, Vector{Point3}, Tuple{StepRange{Int64, Int64}}, true}, connec::Vector{Connectivity{Triangle{Dim, T} where {Dim, T}, 3}})
   @ Meshes C:\Users\12253\.julia\packages\Meshes\GrGir\src\mesh\simplemesh.jl:25
 [2] boundary(t::Tetrahedron{3, Float64, SubArray{Point3, 1, Vector{Point3}, Tuple{StepRange{Int64, Int64}}, true}})
   @ Meshes C:\Users\12253\.julia\packages\Meshes\GrGir\src\polytopes\tetrahedron.jl:27
 [3] top-level scope
   @ REPL[21]:1
```

Clearly **SimpleMesh** does not accept view, I can fix it by modifying **SimpleMesh** to 
```
struct SimpleMesh{Dim,T,TP<:Topology} <: Mesh{Dim,T}
  points::AbstractVector{Point{Dim,T}}
  topology::TP
end
```
But will this lower the performance? Is there a better way?

**Comment by juliohm** [comment]
I am surprised how you are finding these corner cases 💯 I don't know why the default constructor of SimpleMesh is not taking care of the conversion from view to actual vector. Asking our Julia expert @serenity4 for guidance =)

A better quick fix would be to call the `collect(t.vertices)` in the boundary method, but let's see if someone else knows why the conversion didn't happen.

**Comment by juliohm** [comment]
Alternatively, you can add an extra type parameter

```julia
struct SimpleMesh{Dim,T,V<:AbstractVector{Point{Dim,T}},TP<:Topology} <: Mesh{Dim,T}
  points::V
  topology::TP
end
```

 so that any vector is accepted without performance penalties. Mind submitting a PR?

This type is quite mouthful but I think that is it.

**Comment by deltaeecs** [comment]
> I am surprised how you are finding these corner cases 💯 I don't know why the default constructor of SimpleMesh is not taking care of the conversion from view to actual vector. Asking our Julia expert @serenity4 for guidance =)
> 
> A better quick fix would be to call the `collect(t.vertices)` in the boundary method, but let's see if someone else knows why the conversion didn't happen.

I'm working with electromagnetic problems,  the basis functions are constructed on the boundaries of tetrahedron and hexahedron, therefore I need Meshes to construct the mesh and then extract there boundaries. Which is the reason I met these bugs 😄.

I'll have a try and submit a PR if it works~

**Comment by deltaeecs** [comment]
> Alternatively, you can add an extra type parameter
> 
> ```julia
> struct SimpleMesh{Dim,T,V<:AbstractVector{Point{Dim,T}},TP<:Topology} <: Mesh{Dim,T}
>   points::V
>   topology::TP
> end
> ```
> 
> so that any vector is accepted without performance penalties. Mind submitting a PR?
> 
> This type is quite mouthful but I think that is it.

Actually it works, but I'm still confused about why it's better than this 
```
struct SimpleMesh{Dim,T,TP<:Topology} <: Mesh{Dim,T}
  points::AbstractVector{Point{Dim,T}}
  topology::TP
end
```

**Comment by juliohm** [comment]
`V<:AbstractVector{Point{Dim,T}}` is Julia's way of saying: `V` should be inferred by the compiler as any subtype of `AbstractVector{Point{Dim,T}}`. If you just write `points::AbstractVector{Point{Dim,T}}` directly in the field the compiler won't try to figure out the type.
