### ISSUE TITLE
Measure function for Hexhedron incorrect.

### ISSUE THREAD

**Issue by deltaeecs** [JuliaGeometry/Meshes.jl#193]
**measure** function for Hexahedron outputs wrong results when the input hexahedron is not a regular cube
The correct one should be divided like this
![image](https://user-images.githubusercontent.com/48714525/140268304-3e1cce17-5243-412e-a797-4cec8c3998f3.png)

More, the test case in lline 145 of 
https://github.com/JuliaGeometry/Meshes.jl/blob/master/test/polytopes.jl , which is 
```
    h = Hexahedron(P3[(0,0,0),(1,0,0),(1,1,0),(0,1,0),
                      (0,0,1),(1,0,1),(1,1,2),(0,1,1)])
```
is incorrect, since
Ponits[5:8] are not in the same plane. This means the hex we got is not a hexahedron, but  something like this
![image](https://user-images.githubusercontent.com/48714525/140268802-27178bc0-faed-4585-88a3-5ee18a99ba9e.png)

**Comment by juliohm** [comment]
I divided the hexahedron as illustrated in the picture, maybe some indices were flipped? Notice that our ordering convention for indices is different. We make the bottom and top faces with CCW orientation.

Regarding the test, you are correct, we should fix it 👍🏽  Could you please submit a PR fixing this issue?

**Comment by deltaeecs** [comment]
okay, I'll fix it with the SimpleMesh one

**Comment by juliohm** [comment]
Please keep the two fixes separate, I mean different PRs. 👍🏽

**Comment by deltaeecs** [comment]
> Please keep the two fixes separate, I mean different PRs. 👍🏽

By two branches? I’m not familiar with git... 🤣

**Comment by juliohm** [comment]
Yes, you may find this link useful: https://github.com/firstcontributions/first-contributions

You can create two separate branches and push to your fork, then start two separate PRs.
