### ISSUE TITLE
Is it appropriate to add the BVH algorithm to this package?

### ISSUE THREAD

**Issue by GuoHaoxuan** [JuliaGeometry/Meshes.jl#198]
The BVH algorithm is used to calculate the intersection of the ray and the scene. Cache all objects in the scene, and calculate for different `Ray`s.

It is a bit similar with #125 . But this is a large project. Is it appropriate to be added in this package?

**Comment by juliohm** [comment]
Can you please provide a reference to the method? Any paper or book describing it?

**Comment by GuoHaoxuan** [comment]
@juliohm Sorry I have not found the reference on the principle algorithm instead of some improvements.

What about

Lauterbach, Christian, et al. "Fast BVH construction on GPUs." Computer Graphics Forum. Vol. 28. No. 2. Oxford, UK: Blackwell Publishing Ltd, 2009.

and

https://pbr-book.org/3ed-2018/Primitives_and_Intersection_Acceleration/Bounding_Volume_Hierarchies

**Comment by juliohm** [comment]
This is a data structure for accelerating intersection between multiple objects, right? I am used to R-trees and minimum bounding rectangles (MBRs): https://en.wikipedia.org/wiki/R-tree Maybe the BVH is a similar data structure?

Julia has https://github.com/alyst/SpatialIndexing.jl for R-trees, but I didn't use the package seriously yet. What we could do is experiment with the concept and then figure out if it fits the scope. If the implementation relies on actual geometry structs then it may make sense to place it here. If it is a generic data structure that operates with coordinates of points only, maybe we just need a wrapper over a separate package?

**Comment by GuoHaoxuan** [comment]
@juliohm Yes. This is a data structure for accelerating intersection between multiple objects. Compared to R-tree, is is not balanced.

In traditional case, it only contains `Triangle{3}`. But it may could be designed more generic. I think warping it over a separate package is better.
