### ISSUE TITLE
Can we expand a CartesianGrid adding vertices to the left?

### ISSUE THREAD

**Issue by ErickChacon** [JuliaGeometry/Meshes.jl#201]
Imagine that you define a CartesianGrid.
```julia
using Meshes
g = CartesianGrid(Point(10.0,), Point(20.0,), dims = (200,))
```
You do some operations, but now you need to do another operation with one additional vertex to the left. I can create the new grid as follows:
```julia
lag = 1
g2 = CartesianGrid(Point(10.0,) - spacing(g), Point(20.0,), dims = (200 + lag,))
```
In theory, there are 201 vertices that are common in both grids, but in practice they are not because of computational precision.
```julia
collect(vertices(g)) == collect(vertices(g2))[2:end]
# false
```
For my use case, this leads to problems. There is no problem if you add vertices to the right because you do not change the origin. One way to solve that problem is by not modifying the origin and defining an offset such as `origin = vertices[offset]` with a default value equal to `1` as defined in `StepRangeLen`. Here is an example:

```julia
# original range
r = StepRangeLen(10.0, 10/200, 201, 1)
# range with additional vertex value
lag = 1
r2 = StepRangeLen(10.0, 10/200, 201 + lag, 1 + lag)
# compare common vertices
collect(r) == collect(r2)[2:end]
# true
```
Currently, is there a way to expand a `CartesianGrid` ensuring the common vertices are computationally the same? If not, I think adding an `offset` argument and adding a `expand` method would be quite useful. This could be applied to the n-dimensional grid.

In case there is no interest in this feature, just close the issue, please.

**Comment by juliohm** [comment]
You probably have good reasons for this feature in your use case. I am not familiar myself with the StepRangeLen mechanism that leads to robust numerical comparisons. If you can sketch a PR, we can see how much of the code would need to change in order to accommodate the feature.

Before starting the PR, can you please share examples of this API you have in mind for constructing grids with offsets? What changes compared to the current constructors?

**Comment by ErickChacon** [comment]
Thanks for kindly receiving feature requests. The idea behind `StepRangeLen(ref::R, step::S, len, [offset=1])` is to return a range `r` such as the reference value `ref` is not necessarily the origin but it is equals to `r[offset]` and is used as a reference value to compute any other element of the range.  For example:

Using an `offset = 1` is the same as the usual range.
```julia
StepRangeLen(ref, step, len, [offset=1])
# ref, ref + step, ref + 2step, ref + step, ..., ref + (len - 1)step
```
Using an `offset = 2` leads to a range where the reference value is the second element.
```julia
StepRangeLen(ref, step, len, [offset=2])
ref - step, ref,  ref + step, ref + 2step, ref + step, ..., ref + (len - 2)step
```
Using an `offset = 3` leads to a range where the reference value is the third element.
```julia
StepRangeLen(ref, step, len, [offset=3])
ref - 2step, ref - step, ref,  ref + step, ref + 2step, ref + step, ..., ref + (len - 3)step
```
The reason why the common elements are the same is because you perform exactly the same computation. 
In terms of a grid, the idea would be similar, to construct the vertices using a `reference` value and an `offset` such as the `origin = ref - (offset - 1) * step`. For most applications, the reference will be the origin and `offset = 1`, which will not change the current values to construct the vertices, but will allow users to expand the grids when desired, ensuring that common vertices are actually the same.

For the n-dimensional case, `Meshes.jl` uses CartesianIndex which can accept negative values, so it should not be complicated to construct the vertices. Does it make sense to you? In case you want further details, I can check in more detail the CartesianGrid type and explain what methods need to be changed.

**Comment by ErickChacon** [comment]
Once the CartesianGrid accepts an `offset` value, then we can create an expand method as follows:
```julia
function expand(g::CartesianGrid{Dim}, left::SVector{Dim}, right::SVector{Dim}) where {Dim}
  CartesianGrid(g.dims + left + right,  g.ref, g.spacing, offset = left)
end
```

**Comment by juliohm** [comment]
Thanks, let me see if I understood it correctly. The proposal consists of changing the internal `origin` field of the `CartesianGrid` struct to a `reference` + an `offset` field, and then adjust the implementations in terms of `StepRangeLen`? It sounds like a nice generalization and we don't loose anything in terms of memory space. Happy to review a PR :)

Regarding the `expand` function, maybe it is too specific to your use case, it may not make sense to add it to the official API, but we can see if there is a set of similar operations that could fit nicely here after the `reference` + `offset` feature is available.

**Comment by ErickChacon** [comment]
@juliohm that is exactly the proposal, use `reference` and `offset` instead of `origin`. With respect to the `expand` function, no problem at all, I can define that for my use case. I will start the PR soon.

**Comment by ErickChacon** [comment]
Thanks to PR #208. Now it is possible to expand `CartesianGrids` with intersecting vertices and elements numerically equivalent to those of the original `CartesianGrid`. See an example in the tests:
https://github.com/JuliaGeometry/Meshes.jl/blob/bcc08b0b53622f2578c61561fef91153c05c393b/test/mesh.jl#L131-L137
