### ISSUE TITLE
RectilinearGrid type

### ISSUE THREAD

**Issue by ErickChacon** [JuliaGeometry/Meshes.jl#202]
Would be of interest to have a RectilinearGrid type? See an example at https://en.wikipedia.org/wiki/Regular_grid. This type of grid might not be so useful for applications, but it can be used to test the flexibility of models without further complications.

**Comment by juliohm** [comment]
Yes, that would be a nice addition. We should think carefully about it because maybe we can implement both rectilinear and curvilinear in a single struct. That could save a lot of code repetition. Do you have experience implementing these grid types?

**Comment by ErickChacon** [comment]
I only have experience with rectilinear grids in a naive way (not as sophisticated as in `Mehes.jl`). The way I construct them, is by defining a minimum Point, a maximum Point, and a tuple of knots for each axis. However, I have not thought about methods that might be required apart from the computation of vertices and centroids.

**Comment by juliohm** [comment]
I think we need to define ranges for each dimension an a mapping function that takes these ranges and converts to actual points on the manifold. I think this feature is not high-priority compared to other open issues, but good to keep in mind in case someone finds time to work on it.

**Comment by juliohm** [comment]
Added RectilinearGrid type in https://github.com/JuliaGeometry/Meshes.jl/commit/1ed1e26eb5bab89372038f67a4b510c949c8fc09
