### ISSUE TITLE
force Float64 for Ray

### ISSUE THREAD

**Issue by GuoHaoxuan** [JuliaGeometry/Meshes.jl#206]
Due to `Ray` use a `Vec{Dim,T}` as its member. #199 not affected `Ray`. But I tried

```julia
Ray{Dim,T}(p::Point{Dim,T}, v) where {Dim,T} = new{Dim,T}(p, Vec{Dim,T}(v))
```

as a inner construct method.

Sadly, it not worked. So, I hope someone could tell me why and write the right code for it.

**Comment by juliohm** [comment]
Yes, I was thinking about `Vec` when you contributed the `Point` improvement. Currently our `Vec` is simply an alias for `SVector` from StaticArrays.jl. What we really need is a custom static vector type following the `StaticArrays.jl` interface where we can force the same conversion to float. They provide a base struct that you can inherit most methods, it would be nice if you could review their API to implement a new `Vec` that is not exactly equal to `SVector`.

**Comment by juliohm** [comment]
Maybe this is the parent type we need to use to inherit most methods: https://github.com/JuliaArrays/StaticArrays.jl/blob/fa17430f8c3e6a83551946e830ee40c434d72854/src/StaticArrays.jl#L75

**Comment by juliohm** [comment]
Closing in favor of #207
