### ISSUE TITLE
Add boundary for all Primitive geometries

### ISSUE THREAD

**Issue by juliohm** [JuliaGeometry/Meshes.jl#210]
Given a primitive geometry, we should be able to construct its boundary mesh (or geometry). For example, the boundary of a `Ball` is a `Sphere`. The boundary of a `Cylinder` is a `SimpleMesh` with two disks and the wall of the cylinder. We can already sample these geometries using our sampling methods, we just need to connect the dots to return a mesh.

- [x] Box
- [x] Ball
- [x] Sphere
- [x] Line
- [x] Ray
- [x] Plane
- [x] Cylinder
- [x] BezierCurve

**Comment by GuoHaoxuan** [comment]
So, what is the method name? Use the `SimpleMesh` construction method? As we know, some geometry has many different represent of mesh. For example, sphere has UV sphere, ico sphere, quad sphere and Goldberg polyhedra. How to choose that?

**Comment by juliohm** [comment]
In the case of Ball the boundary is a Sphere primitive. In the case of
other primitives we can use a SimpleMesh.

**Comment by GuoHaoxuan** [comment]
@juliohm For `Cylinder` the number of faces of the wall (Or the number of the edges of the disks) is not exactly as well. In another word, we may require some other parameters to generate the boundary. What about using a kw args?

**Comment by juliohm** [comment]
Sounds like a good idea. I would create a separate PR for each primitive so
that we can more easily assess the design differences.

**Comment by juliohm** [comment]
I've implemented a couple of different discretization methods. Now we can discretize the sphere with quadrangles + triangles using any sampling size:

```julia
sphere = Sphere((0.,0.,0.), 1.)

mesh = discretize(sphere, RegularDiscretization(100))

viz(mesh, showfacets = true)
```
![image](https://user-images.githubusercontent.com/3345261/144707913-ef4cae16-9f18-4145-b511-9a2ca01b023c.png)

and we can pass this polygonal mesh to `triangulate` to create a triangle mesh:

```julia
tmesh = triangulate(mesh)

viz(tmesh, showfacets = true)
```
![image](https://user-images.githubusercontent.com/3345261/144707951-454d29f0-885b-42b8-ba8d-7d021d6de69e.png)

I will polish the Makie recipes now to hide these internals so that end users can simply `viz(sphere)`.

**Comment by GuoHaoxuan** [comment]
Line and Ray has a infinite volume. Are these boundary exist?

**Comment by juliohm** [comment]
For line we should return `nothing` and for Ray the origin point. Makes
sense? That is how the Makie recipes will figure out if there is something
to plot.

**Comment by GuoHaoxuan** [comment]
@juliohm Sounds great.

**Comment by juliohm** [comment]
Ok, just registered a patch release where the following works:

```julia
viz(sphere, color = :orange)
```
![image](https://user-images.githubusercontent.com/3345261/144710064-2ad005fe-3389-4e79-9862-29237e9b5929.png)

**Comment by juliohm** [comment]
Now we are only missing the boundary of `Cylinder` which is a cylindrical surface plus two disks and the boundary of `BezierCurve`. In the first case we need a new struct to represent the cylindrical surface, like we do with `Ball` -> `Sphere`. In the last case we can return the two end points as a `PointSet`.

Let me know if you want to work on that @HaoxuanGuo 👍🏽

**Comment by GuoHaoxuan** [comment]
@juliohm I am not familiar on the topologic of mesh. But I would like to have a try.

**Comment by juliohm** [comment]
@HaoxuanGuo I will work on the cylinder case now, it should be ready by the end of the day. If you can help with the BezierCurve to add a boundary and maybe review the recipe in MeshViz.jl that would be great.

**Comment by juliohm** [comment]
Now all primitives have boundary. I did refactor the solid `Cylinder` type and also introduced a new `CylinderSurface` type. We need to review these primitives in the future and try to use more constructive geometry to avoid code repetition.
