### ISSUE TITLE
Intersection between `Polygon`s and `Sengment`s and `Ray`s.

### ISSUE THREAD

**Issue by GuoHaoxuan** [JuliaGeometry/Meshes.jl#214]
This is an extra step towards #125 . Moved from #213 to here. Make `[intersect(ray, triangle) for triangle in mesh]` works.

This may require 2 tiny steps. 

- [x] Triangulate `Polygon`. Make Discretization to 3D.
- [ ] Check intersections to every triangle.

**Comment by juliohm** [comment]
For the 3D discretization, maybe we can project the polygon onto a 2D plane using least squares with the vertices, then rotate the plane to a horizontal plane to discard the 3rd coordinate, perform triangulation, and then return the mesh with the original vertices. It shouldn't be very difficult to implement given our current API for triangulation.

**Comment by juliohm** [comment]
I will open a separate issue just for the 3D triangulation because it is a major feature.

**Comment by juliohm** [comment]
Linking the issue here #218

**Comment by juliohm** [comment]
@HaoxuanGuo the 3D discretization is already implemented for polygons without holes. Would you like to tackle the intersection algorithm with rays now? Polygons with holes only appear in 2D GIS work anyways so we got these covered when it comes to intersection.

**Comment by GuoHaoxuan** [comment]
@juliohm Yes, I would like to.
