### ISSUE TITLE
Subtype Point with AbstractVector

### ISSUE THREAD

**Issue by lmejn** [JuliaGeometry/Meshes.jl#221]
To increase the versatility of `Point`, it could be a subtype of `AbstractVector`.

In my personal case, I only came across Meshes.jl when I was looking for better 3D support in my project. A lot of code I had already written consisted of manipulating point positions and using their position to compute quantities at that particular point (*e.g.* `fi = f(p::AbstractVector)`), where `p` was a vector with x, y and z positions.

I went about implementing Meshes.jl, but found I couldn't automatically use `Point` for my methods. This is due to two reasons:
1. `Point` is not a subtype of `AbstractVector`, hence functions with `AbstractVector` arguments wouldn't apply.
2. Methods such as `Base.getindex(p::Point, ...)` are not defined, hence can't do `x = p[1]`

There are some workarounds in the Meshes.jl already. For example, I could get the underlying `SVector` by calling `coordinates(p::Point)`, which will solve reason 2. However, I'd have to define methods such as `f(p::Point) = f(coordinates(p))` for every method to solve reason 1. Alternatively, I could keep my code to using `AbstractVector` types, only converting to `Point` when needed.

Of course, how I'd like to use Meshes.jl is not necessarily how other people would, but I thought I'd open up the discussion about this to see whether it's a good idea!

**Comment by juliohm** [comment]
There are very good reasons to distinguish between the concept of Point and the concept of coordinates and we won't change this behavior. A single point can be referenced in different coordinate systems and so there is no single set of coordinates to describe it. You can use lat/lon if you are on the sphere or x,y,z if you embed the sphere on R^3. You should write functions that dispatch on Point, not on specific coordinates.

**Comment by lmejn** [comment]
Thanks for clarifying! Are these reasons explained somewhere? I'd be curious to learn more!

**Comment by juliohm** [comment]
For one you can't add two points, this operation is not defined. You can only add coordinates if they support such operation. We are still working on the interface for coordinates and transformations so very little documentation is available.
