### ISSUE TITLE
Docs pages are down

### ISSUE THREAD

**Issue by jwscook** [JuliaGeometry/Meshes.jl#23]
I just thought I'd let you know that the documentation pages are down. Perhaps the CI needs to be re-triggered?

**Comment by juliohm** [comment]
Thank you @jwscook for reporting the issue. We don't have doc pages yet, still in progress. Please consider reading the tests to understand how to use the concepts form the package.

**Comment by jwscook** [comment]
Ahh ok 👍 , the docs badge threw me.

**Comment by juliohm** [comment]
This is now fixed, you can access the dev version of the documentation here: https://juliageometry.github.io/Meshes.jl/dev/

We will soon tag a new release with a stable documentation too.

**Comment by jwscook** [comment]
Thank you!
