### ISSUE TITLE
Add function to compute normals and add angle method for Vec

### ISSUE THREAD

**Issue by kylebeggs** [JuliaGeometry/Meshes.jl#233]
Sorry if I am somehow missing this, but I don't see a function to compute normals of a surface. Something like `n = normals(m::Mesh)`. After getting the normals of a surface, it is also useful to be able to compute the angle between them sometimes, so add a method of `\angle(v::Vec)`. I can add these, just read that I should open an issue first to confirm it is a good idea before making a PR.

**Comment by juliohm** [comment]
We designed the package so that any domain is an iterable of elements. If
you have a mesh of triangles it should suffice to call normal.(mesh) and
rely on Julia's broadcast. Regarding the angle we have angle functions
defined, can you please double check?

**Comment by kylebeggs** [comment]
`normal.(mesh)` is exactly what I wanted. Sorry I missed that. I did look at the source and only methods for points are in src/angles.jl. I also created 2 vectors and tried to call it, but received a MethodError.

**Comment by juliohm** [comment]
Can you clarify what angle exactly do you need? Angles are defined between rays usually. The functions in src/angles.jl are for rays, but expressed directly in terms of Point because they show up in many algorithms.

**Comment by juliohm** [comment]
I will close the issue meanwhile, feel free to ask more questions in the Zulip channel.
