### ISSUE TITLE
Operations on meshes: translation, rotation, scaling

### ISSUE THREAD

**Issue by VEZY** [JuliaGeometry/Meshes.jl#234]
Hello, I'm migrating my package to Meshes.jl but I didn't find any functions for translation, rotation or scaling. Is this a planned feature or is it out of the scope of this package ? I was particularly interested on doing that for `SimpleMesh`es.

**Comment by juliohm** [comment]
Yes, it is definitely planned. We've delayed this issue for a while, but it is certainly one of the major ones that we want to take seriously next year. Meanwhile, you can try to reuse pieces of code from CoordinateTransformations.jl Geodesy.jl Rotations.jl ReferenceFrameRotations.jl etc. All these packages handle a specific subset of a more general solution.

**Comment by VEZY** [comment]
Awesome ! Yes OK I think I'll implement something myself waiting for a more efficient one in Meshes.jl.
