### ISSUE TITLE
ERROR: LoadError: MethodError: no method matching generate_benchmark_definition(::Module, ::Vector{Symbol}, ::Vector{Any}, ::Expr, ::Nothing, ::Nothing, ::Parameters)

### ISSUE THREAD

**Issue by iajzenszmi** [JuliaGeometry/Meshes.jl#237]
ian@ian-HP-Stream-Laptop-11-y0XX:~/meshes.jl/Meshes.jl/benchmark$ julia benchmarks.jl
ERROR: LoadError: MethodError: no method matching generate_benchmark_definition(::Module, ::Vector{Symbol}, ::Vector{Any}, ::Expr, ::Nothing, ::Nothing, ::Parameters)
Closest candidates are:
  generate_benchmark_definition(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any) at ~/.julia/packages/BenchmarkTools/SnZV6/src/execution.jl:461
Stacktrace:
  [1] benchmarkable(ex::Expr, params::Vector{Any})
    @ Main ~/meshes.jl/Meshes.jl/benchmark/utils.jl:13
  [2] benchmarkable(ex::Expr)
    @ Main ~/meshes.jl/Meshes.jl/benchmark/utils.jl:5
  [3] add_benchmark!(group::BenchmarkGroup, ex::Expr)
    @ Main ~/meshes.jl/Meshes.jl/benchmark/utils.jl:25
  [4] _broadcast_getindex_evalf
    @ ./broadcast.jl:670 [inlined]
  [5] _broadcast_getindex
    @ ./broadcast.jl:643 [inlined]
  [6] getindex
    @ ./broadcast.jl:597 [inlined]
  [7] copy
    @ ./broadcast.jl:899 [inlined]
  [8] materialize
    @ ./broadcast.jl:860 [inlined]
  [9] add_benchmark!(group::BenchmarkGroup, exs::Vector{Expr})
    @ Main ~/meshes.jl/Meshes.jl/benchmark/utils.jl:29
 [10] top-level scope
    @ ~/meshes.jl/Meshes.jl/benchmark/points.jl:3
 [11] include(fname::String)
    @ Base.MainInclude ./client.jl:451
 [12] top-level scope
    @ ~/meshes.jl/Meshes.jl/benchmark/benchmarks.jl:10
in expression starting at /home/ian/meshes.jl/Meshes.jl/benchmark/points.jl:3
in expression starting at /home/ian/meshes.jl/Meshes.jl/benchmark/benchmarks.jl:10
ian@ian-HP-Stream-Laptop-11-y0XX:~/meshes.jl/Meshes.jl/benchmark$

**Comment by juliohm** [comment]
Are you following the instructions in the docs on how to run benchmarks? I am busy at the moment, but please confirm this is the expected way of running benchmarks.

cc: @serenity4

**Comment by serenity4** [comment]
Please read the docs [here](https://juliageometry.github.io/Meshes.jl/stable/contributing/devguide.html#Running-benchmarks-locally) to run benchmarks. I tested the instructions locally and everything worked fine. If it doesn't for you, make sure to include more information (at least your Julia version, and versions for BenchmarkTools/Meshes).

**Comment by juliohm** [comment]
Thank you @serenity4 for checking.
