### ISSUE TITLE
Rename PolySurface to PolyArea

### ISSUE THREAD

**Issue by juliohm** [JuliaGeometry/Meshes.jl#24]
@serenity4 I was thinking about the name `PolySurface` I suggested last year but I think the name `PolyArea` is clearer. I will prepare a quick PR with the changes, ok?

Please let me know if you feel that the name `PolyArea` isn't clear.

**Comment by serenity4** [comment]
I was wondering what was the exact difference between surface and area after all. From Wikipedia:
> The area is the measurement of the size of flat-surface in a plane (two-dimensional), whereas surface area is the measurement of the exposed surface of a solid shape (three-dimensional). This is the key difference between area and surface area.

So, area refers to a measure, and not to a shape. I think this renaming is totally fine in 2D (and, as you point out, clearer). It's the higher-D case that could lose in clarity. But if you intend to mostly use it in 2D, then I'd say this loss of generality can still be worth it.

**Comment by serenity4** [comment]
So, I would say, just consider whether you are going to use it in 3D (and more) or not. If you do, then you _might_ regret this renaming, if not it's totally fine.

**Comment by juliohm** [comment]
That is a very good point. Thanks for sharing your thoughts. The use cases are mostly 2D indeed, and I think surfaces in N-D will have better mesh representations. I will create the PR now to make sure that tests are passing as expected. 👍🏽
