### ISSUE TITLE
Missing cylinder triangulation

### ISSUE THREAD

**Issue by VEZY** [JuliaGeometry/Meshes.jl#243]
Hello, I think there is no implementation of `triangulate` for the `Cylinder` primitive. 
I found the issue when trying to plot a simple cylinder with MeshViz:

```julia
using Meshes, MeshViz, GLMakie
viz(Cylinder(0.1))
```

**Comment by juliohm** [comment]
We have the `boundary(cylinder)` implemented as a `CylinderSurface` already. We just need to add a RegularDiscretization method for this surface. Do you think you can help with that? There are examples with spheres to serve as a base.

I can try to work on that after some deadlines this month in case you don't know how to proceed.

**Comment by VEZY** [comment]
Just to be sure, you mean we need to implement:

```julia
function discretize(cyl::Cylinder{T}, method::RegularDiscretization) where {T}
[...]
end
```

But also a RegularSampling right ? 

and then:

```julia
triangulate(cyl::Cylinder{T}) =
  discretize(cyl, RegularDiscretization(100)) |> triangulate
```

I would be happy to help but I'm not sure to understand the package design correctly. I must say I have very little time and I'm not sure to have the skills to do it (though I'm sure there are some resources somewhere online?).

I'll give it a try if I find a little bit of time. Thank you for considering this issue.

**Comment by juliohm** [comment]
Yes. Everything is very composible and we just need to know how to sample
points on the surface of the cylinder and how to connect these points into
quadrangles + triangles. The rest follows from the other implementations.

What about first submitting a PR for RegularSampling with CylinderSurfsce?
After that we can work on the connectivities.

**Comment by VEZY** [comment]
OK, I just did a PR (#244). I didn't have time to check the validity domain of the implementation yet. Hope this helps.

**Comment by juliohm** [comment]
Fixed on master. Now we can visualize cylinders and cylinder surfaces that are oblique, for example:

![image](https://user-images.githubusercontent.com/3345261/183258627-614e2201-f63a-44ee-8224-f0e9dc711944.png)

As usual, the code composes really nicely, you can simply do:

```julia
using Meshes, MeshViz
import GLMakie as Mke

c = Cylinder(1.0) # aligned with z axis

viz(c)
```
![image](https://user-images.githubusercontent.com/3345261/183258671-77c22a65-f019-41a1-9c0e-bde9485a9b66.png)

```julia
# top plane has a normal (1,1,1)
c = Cylinder(1., Plane((0.,0.,0.), (0.,0.,1.)), Plane((0.,0.,2.), (1.,1.,1.)))
```
![image](https://user-images.githubusercontent.com/3345261/183258733-3349142a-32a1-47a9-bceb-bd71b79e8612.png)

We can control the discretization on the wall of the cylinder as usual:

```
m = discretize(boundary(c), RegularDiscretization(50, 2))

viz(m, showfacets = true)
```
![image](https://user-images.githubusercontent.com/3345261/183258780-3e4d71c3-b076-4228-9596-206872bb2759.png)

```
m = discretize(boundary(c), RegularDiscretization(50, 10))

viz(m, showfacets = true)
```
![image](https://user-images.githubusercontent.com/3345261/183258800-f97708c3-0f67-4c91-918f-03035ed31737.png)
