### ISSUE TITLE
Is there a nice way to evaluate a function at some points?

### ISSUE THREAD

**Issue by cjwyett** [JuliaGeometry/Meshes.jl#252]
Say I have some function
```
 f(x) = log(sin(x))
```
And some points
```
pts = Point1.([1,2,3])
```
The way I'm going about evaluating the function at the points seems a little untidy to me: 
``` 
eval(f, pts) = f.([p.coords[1] for p in pts])
```
Is there a nice clean built in method that can handle this kind of stuff for me?

Thanks

**Comment by juliohm** [comment]
Hi @cjwyett please direct questions to the Zulip support channel.
