### ISSUE TITLE
Nvidia warp as backend

### ISSUE THREAD

**Issue by jakubMitura14** [JuliaGeometry/Meshes.jl#253]
Hello I wonder wheather it would be feasible to use NVIDIA warp [1] as CUDA accelerated backend for meshe computations?

https://github.com/NVIDIA/warp

**Comment by juliohm** [comment]
Hi @jakubMitura14 , I am not familiar with the framework, so someone with more experience in it needs to jump in and write down a concrete proposal. In general, we want to provide options for all audiences, but that may require additional packages to avoid explosion of dependencies.
