### ISSUE TITLE
Incomplete modification from intersecttype to intersection

### ISSUE THREAD

**Issue by GuoHaoxuan** [JuliaGeometry/Meshes.jl#264]
https://github.com/JuliaGeometry/Meshes.jl/blob/83aa55978077b09f39f411e83b9e4fa0a79554cd/src/discretization/fist.jl#L84

I noticed that intersecttype was being changed to intersection three weeks ago, but there is a possible omission here.

**Comment by juliohm** [comment]
We should also add a test for that because the tests didn't cover it
apparently :/

Em seg., 9 de mai. de 2022 09:19, Haoxuan Guo ***@***.***>
escreveu:
