### ISSUE TITLE
Out of memory with 8 triangles

### ISSUE THREAD

**Issue by ederag** [JuliaGeometry/Meshes.jl#267]
Uncommenting the last line eats about 1Gb per second, with no end (it froze my desktop once),
so be prepared to interrupt.

```julia
using Meshes

points = [
	Point(-0.5, -0.8660254037844386)
    Point(0.5, -0.8660254037844386)
    Point(1.5, -0.8660254037844386)
    Point(-1.0, 0.0)
    Point(0.0, 0.0)
    Point(1.0, 0.0)
    Point(-0.5, 0.8660254037844386)
    Point(0.5, 0.8660254037844386)
    Point(1.5, 0.8660254037844386)
]

triangles = [
	(1, 2, 5)
    (1, 4, 5)
    (2, 3, 6)
    (2, 5, 6)
    (4, 5, 7)
    (5, 6, 8)
    (5, 7, 8)
    (6, 8, 9)
]

mesh = Meshes.SimpleMesh(points, connect.(triangles))

# Beware, this eats all the RAM quickly (few 10s of seconds) !
# Meshes.refine(mesh, Meshes.TriRefinement())
```

Another clue:
`MeshViz.viz(mesh)` works fine, but `viz(mesh, showfacets=true)` eats all the RAM as well.

Tested with `Meshes v0.22.5` and `julia-1.6.5`.

**Comment by juliohm** [comment]
You are not ordering the connectivities coherently. Please make sure that they are all counter-clockwise, otherwise the underlying half-edge structure will break in undefined ways. See also #137.

**Comment by ederag** [comment]
Thanks, I had read the manual (nicely written, by the way) but overlooked
https://juliageometry.github.io/Meshes.jl/stable/geometries/polytopes.html#Meshes.Ngon
and
https://juliageometry.github.io/Meshes.jl/stable/geometries/polytopes.html#Meshes.PolyArea
and did not find #137.

But as a feedback, I'm surprised that this is not considered as a bug
and kept open to warn other users.
Crashing a whole desktop with a toy example should be avoided, IMO.

At the very least, that limitation should be mentioned in
https://juliageometry.github.io/Meshes.jl/stable/meshes.html#Meshes.SimpleMesh
(which I did read before usage)

**Comment by juliohm** [comment]
> But as a feedback, I'm surprised that this is not considered as a bug
> and kept open to warn other users.
> Crashing a whole desktop with a toy example should be avoided, IMO.

Most errors like this happen simply because we didn't implement a method yet and there is some recursion involved. There are other issues already open like this. We could add methods to introduce nicer error messages or actually implement the missing features. I tend to devote my time to the latter option.

If you feel that you can submit a PR with a better error message, we are happy to review. Alternatively, a PR improving the docstring of SimpleMesh would be very welcome.
