### ISSUE TITLE
Unclear documentation: subtracting Points

### ISSUE THREAD

**Issue by nick-adamowicz** [JuliaGeometry/Meshes.jl#270]
https://github.com/JuliaGeometry/Meshes.jl/blob/11855a2aaf0688fffae4678635bef08b377fb4d4/src/points.jl#L98-L104

The current documentation lists:

"Return the Vec associated with the direction from point A to point B."

wouldn't it be more accurate to say:

"Return the Vec associated with the direction from point B to point A."

since, e.g.:

```
pa = Point(1,1) # point a
pb = Point(5,8) # point b
dp = pa - pb # difference vector between points a & b
pb + dp == pa # => true
```

... or am I just confused :) ...

**Comment by juliohm** [comment]
Good catch @fujiwara-tofu-tm , could you please submit a PR with the fix?

**Comment by nick-adamowicz** [comment]
this is the first time I've ever made a pull request, so please bear with me. Did I do it correctly?

**Comment by juliohm** [comment]
You did it perfectly 💯 Merged and should be included in the next release. Thank you!
