### ISSUE TITLE
documentation issue, RegularSampling

### ISSUE THREAD

**Issue by nick-adamowicz** [JuliaGeometry/Meshes.jl#272]
https://github.com/JuliaGeometry/Meshes.jl/blob/4be3b986e7988cd61157f81b193964b0204f44fe/src/sampling/regular.jl#L5-L19

slight typo in ``... `np` poitns along ...`` -> ``... `np` points along ...``

also, the provided example:

```
sample(Sphere((0,0,0), 1), RegularSampling(360, 180))
```

throws an error since the following constructor doesn't convert the provided radius to a Float32 or Float64 (depending on the form of the constructed Point):

https://github.com/JuliaGeometry/Meshes.jl/blob/4be3b986e7988cd61157f81b193964b0204f44fe/src/primitives/sphere.jl#L17

suggested change to RegularSampling documentation:

```
sample(Sphere((0,0,0), 1), RegularSampling(360, 180))
```
->
```
sample(Sphere((0,0,0), 1.0), RegularSampling(360, 180))
```

... or I guess we could modify the Sphere constructor ....

**Comment by juliohm** [comment]
Thank you @fujiwara-tofu-tm for catching these small typos and issues ❤️ These are super helpful contributions. Would you mind submitting a PR to fix the Sphere constructor? We need to fix many constructors that are still using integer arguments to convert to floating point.

Also, feel free to submit a separate PR with the typo fix in the RegularSampling docstring to replace poitns -> points

**Comment by juliohm** [comment]
Fixed on master.
