### ISSUE TITLE
Parallelization support?

### ISSUE THREAD

**Issue by henry2004y** [JuliaGeometry/Meshes.jl#28]
Hi,

Glad to see this brand new package in the Julia community! Hopefully this will become the go-to choice for constructing a 2D/3D mesh in Julia!

I do have a question regarding parallelization: does it now support building a mesh in a distributed manner, or if not, will that be considered in the future?

**Comment by juliohm** [comment]
Thanks! Can you elaborate on what you mean by building meshes in parallel?
You mean parallel meshing algorithms?

**Comment by henry2004y** [comment]
I am thinking of a scenario where multiple processors are involved, and ideally each processor owns a partition of the mesh. In computational astrophysics, we often do large simulations based on block-based AMR mesh, for example [AMReX](https://amrex-codes.github.io/amrex/). The general idea is to split the whole mesh into small parts, where each individual part knows its relation to its neighbors. I am not sure if there are similar things in the unstructured grid partitions.

If this can be supported from the basic mesh library, or even another new library built upon the serial mesh library, than it would be a huge benefit for quickly setting up a new large scale model that can run on multiple processors.

**Comment by juliohm** [comment]
I see your point. We certainly plan to have partitions at some point but
help is needed in order to achieve something parallel as you suggested.

**Comment by juliohm** [comment]
Closing the issue for now. Thanks for raising the question.
