### ISSUE TITLE
Wrong definition of centroid

### ISSUE THREAD

**Issue by jguterl** [JuliaGeometry/Meshes.jl#280]
The definition of centroid implemented in Meshes.jl is incorrect.
Here is below a correct implementation:
function compute_centroid(x_::Vector{T}, y_::Vector{T}) where {T<:Number}
    @assert length(x_) == length(y_)
    x = [x_..., x_[1]]
    y = [y_..., y_[1]]
    a = similar(x[1:end-1])
    b = similar(a)
    cx = similar(a)
    cy = similar(b)

    a[:] = x[1:end-1] .* y[2:end]
    b[:] = y[1:end-1] .* x[2:end]

    cx[:] = x[1:end-1] + x[2:end]
    cy[:] = y[1:end-1] + y[2:end]

    A = abs(sum(a - b) / 2.0)
    if (A>0.0)
    Cx = sum(cx .* (a - b)) / (6.0 * A)
    Cy = sum(cy .* (a - b)) / (6.0 * A)
    else
    Cx = sum(x_) / length(x_)
    Cy = sum(y_) / length(y_)
    end
    return Point2(Cx, Cy)
end

function compute_centroid(ngon::Ngon)
    
        x = [v.coords[1] for v in ngon.vertices]
        y = [v.coords[2] for v in ngon.vertices]
        return compute_centroid(x,y)
end

**Comment by juliohm** [comment]
Can you please provide a minimum example with the current implementation that you think is incorrect? I am only seeing your code in this issue.

**Comment by jguterl** [comment]
The implementation of centroid in Meshes.jl returns the geometric center of the ngon. The geometric center of a ngon is not the centroid of a ngon. See for instance:https://www.wolframalpha.com/input/?i=centroid

**Comment by juliohm** [comment]
If you can provide a MWE, it will be much easier to evaluate and fix. I don't know which code you has tried that has produced the incorrect result.
