### ISSUE TITLE
Boundary{2,1} not giving correct result for CartesianMesh

### ISSUE THREAD

**Issue by jguterl** [JuliaGeometry/Meshes.jl#287]
Boundary{2,1} does not provide the correct index of the facets. 
See example below

MWE:
using Meshes
mesh = CartesianGrid((0.,0.),(1.,1.), dims=(2,2));
topo = convert(HalfEdgeTopology, topology(mesh))
v = collect(vertices(mesh))

c12 = Coboundary{1,2}(topo) 
b21 = Boundary{2,1}(topo)
b20 = Boundary{2,0}(topo)
c02 = Coboundary{0,2}(topo)
for id in b21(1)
    println("face #$id : ",facet(mesh,id))
end

for id in b20(1)
    println("vertex #$id : ",v[id])
end

**Comment by juliohm** [comment]
@jguterl please use the Zulip chat to ask questions and clarify concepts. The issues you are opening here on GitHub are invalid because you still don't understand some of the concepts. We are happy to help in the chat instead.

**Comment by jguterl** [comment]
My bad. Let me post on Zulip.

**Comment by jguterl** [comment]
For reference:

A possible way of retrieving correctly the faces (rank 1) is the following:
using Meshes
mesh = CartesianGrid((0.,0.),(1.,1.), dims=(2,2));
topo = convert(HalfEdgeTopology, topology(mesh))
v = collect(vertices(mesh))

c12 = Coboundary{1,2}(topo)
b21 = Boundary{2,1}(topo)
b20 = Boundary{2,0}(topo)
c02 = Coboundary{0,2}(topo)
for id in b21(1)
println("face #$id : ",map(i->v[i],facet(topo,id).indices))
end

for id in b20(1)
println("vertex #$id : ",v[id])
end
