### ISSUE TITLE
Implement ringequal for polygons and closed chains

### ISSUE THREAD

**Issue by dorn-gerhard** [JuliaGeometry/Meshes.jl#310]
I just figured out that the sequence how polytopes are initialized makes a difference when checking for isequal.

``Segment((1,0), (0,0)) == Segment((0,0), (1,0))`` returns ``false``

This is due to the implementaion in ``polytopes.jl`` in line 60:
``==(p1::Polytope, p2::Polytope) = vertices(p1) == vertices(p2)``
I see that the sequence of points is important but any cyclic permutation should be allowed.

For Segments a solution could be:

``==(s1::Segments, s2::Segments) = Set(vertices(s1)) == Set(vertices(s2))``

Maybe there is a solution to check for all cyclic permutations for polytopes in general

**Comment by juliohm** [comment]
That is a good question, should we consider polytopes equal up to permutation? In practice I think that can complicate things or at least compromise performance? What is the scenario where we would actually check for equality?

**Comment by juliohm** [comment]
I thought about it a bit more and the most conservative way forward is to introduce a new function like `ringequal` that compares polygons and closed chains as rings. The default == should be the most simple and performant definition for test purposes. Notice that this ringequal doesn't make sense for 3D geometries, so I will rename the issue to something more specific.

**Comment by dorn-gerhard** [comment]
a suggestion for a ringequal function:

``` julia
function ≗(p1::Polytope,p2::Polytope)
    if Set(vertices(p1)) == Set(vertices(p2))
      ix = findfirst(vertices(p1)[1] .== vertices(p2))
      if circshift(vertices(p1), ix-1) == vertices(p2)
        return true
      end
    end
    false
end
```
respectively
``` julia
function ≗(p1::Polytope,p2::Polytope)
    if all([i in vertices(p2) for i in vertices(p1)])
      ix = findfirst(vertices(p1)[1] .== vertices(p2))
      if circshift(vertices(p1), ix-1) == vertices(p2)
        return true
      end
    end
    false
end
```
(Set is slow)

a test:
``` julia
p1 = Ngon((1,0), (2,2), (3,2), (0,1), (3,2))
v = vertices(p1)
p2 = Ngon(circshift(vertices(p1),2))
p3 = Ngon(shuffle(v))

p1 ≗ p2, p1 ≗ p3, p1 == p2
```

**Comment by juliohm** [comment]
Notice that the function should only accept Polygon and Chain.

Polytope in our terminology includes 3D polyhedra or higher dimensional objects.

**Comment by dorn-gerhard** [comment]
yes, you are right.

So after current PR I can add a function ``ringequal`` (or circledequal? there is also ``circshift`` in julia) for Polygons and Chains. A possible symbol could be
- ``\circeq``: ≗
- ``\circledequal``: ⊜

A question will be if we map isequal to ringequal by default, like
``isequal(s1::Segment, s2::Segment) = ringequal(s1,s2)``
No idea about the consequences

**Comment by juliohm** [comment]
The \circeq looks great 👍🏽 

Regarding the case with Segment, I don't think it is a ring (i.e. the begin != end)

**Comment by juliohm** [comment]
@dorn-gerhard can we add this circeq in a PR and solve this issue? Should be quick to solve now that we aligned the name and symbol :)
