### ISSUE TITLE
Packages using Meshes.jl

### ISSUE THREAD

**Issue by EdoAlvarezR** [JuliaGeometry/Meshes.jl#311]
This is more of a feature request than an issue.

Any chance that a list of packages that currently use Meshes.jl could be added to the readme and docs? As I've been considering using Meshes.jl, I've found myself wishing to see how other people implement Meshes.jl to their own use cases.

**Comment by juliohm** [comment]
You can find this information in the JuliaHub website. They show the dependants of a package.
