### ISSUE TITLE
Types of point and segment

### ISSUE THREAD

**Issue by henry2004y** [JuliaGeometry/Meshes.jl#32]
Hello,

When playing with the code, I got a question about the type system in the package. For example,
```julia
using Meshes

points = Point2[[1.0,1.0],[3.0,1.0]]
a = Segment(points[1], points[2])
typeof(a) == Segment # false?
typeof(points[1]) == Point # false?
typeof(points[1]) == Point2 # true?
```
Do I need to specify all the parameters for the type, e.g. `typeof(a) == Segment{2,Float64,StaticArrays.SArray{Tuple{2},Point{2,Float64},1,2}}`? Why is `Point` not a general supertype for all points?

**Comment by juliohm** [comment]
The function `typeof` in Julia returns the exact type of the object, which includes the type parameters. Perhaps you can share your use case and we can try to help. If you are only interested in figuring out if a geometry is a segment, you can do `a isa Segment` for example.

Also, please consider asking questions in Zulip instead.

**Comment by juliohm** [comment]
I've created a meshes.jl stream there: https://julialang.zulipchat.com/#narrow/stream/275558-meshes.2Ejl
