### ISSUE TITLE
Ordering convention for intersection pairs

### ISSUE THREAD

**Issue by juliohm** [JuliaGeometry/Meshes.jl#325]
As discussed in #324 we need to introduce an ordering convention for the various intersection pairs.

@dorn-gerhard do you have a proposal in the form of an algorithm that takes two geometry types and decides which one should come first?

**Comment by dorn-gerhard** [comment]
Sure. 
I would rank geometries according to the following criterias (some first thoughts): 

1. According to `paramdim` in ascending order 
   - 0: paramdim(::Point) = 0, 
   - 1: paramdim(::Line or ::Ray or ::Segment or ::Bezier) = 1
   - ≥ 1: paramdim(::Sphere) = N-1 (1, 2, ...)
   - 2: paramdim(::Plane or ::Triangle or ::Ngon or ::PolyArea) = 2, paramdim(::CylinderSurface) = 2
   - ≥ 2: paramdim(::Box or ::Ball) = N (2, 3, ...)
   - 3: paramdim(::Cylinder or ::Pyramid or ::Tetrahedron or ::Hexahedron) = 3
2. has measure?
   - NO: 
     - 1: Line, Ray
     - 2: Plane
   - YES:
     - 0: Point
     - 1: Segment
     - ≥ 1:  Sphere
     - 2: Triangle, Ngon, PolyArea, CylinderSurface
     - ≥ 2: Box, Ball
     - 3: Cylinder, Pyramid, Tetrahedron, Hexahedron
3. throws domain errors?
  - NO:
     - 1: Line
     - 2: Plane, Quadrangle (**should actually throw a domain error!!!**)
   - YES:
      - 1: Ray, Segment
      - 2: Triangle
   - Not callable:
      - 0: Point
      - ≥ 1:  Sphere

**Comment by juliohm** [comment]
> 2\. has measure?
>     
>     * NO:
>       
>       * 1: Line, Ray
>       * 2: Plane

Fixed in https://github.com/JuliaGeometry/Meshes.jl/commit/b5201447e6d049ad2d6ee3071886e3e38ec6f11b

> 3\. throws domain errors?
> 
> * NO:
>   
>   * 1: Line
>   * 2: Plane, Quadrangle (**should actually throw a domain error!!!**)

Fixed in https://github.com/JuliaGeometry/Meshes.jl/commit/7f9c763c5a8a04ba9bb310e008dc98067e1ea723

> * Not callable:
>   
>   * 0: Point
>   * ≥ 1:  Sphere

You mean that we should add a `sphere(u, v)` parametrization, correct?

**Comment by dorn-gerhard** [comment]
thanks for fixing, 
regarding not callable geometries, ``sphere(u, v)`` would be great, with u, v being spherical coordinates θ ∈[0, π] and ϕ ∈[0, 2π].

calling a point shouldn't be possible as number of arguments should correspond to paramdims.

Box and Ball should be also callable with N arguments

Pyramid, Cylinder and Tetrahedron  should be callable with 3 arguments

**Comment by dorn-gerhard** [comment]
but what do you think of this ordering scheme of intersection types?

A. paramdim
B. measure
  1. infinite measure
  2. finite measure

C. domain error
   1. not restricted
   2. restricted

D. nvertices
   - 0: not defined
   - n: actual number of vertices 

This would yield the following order:
 - Point (A=0)
 - Line (A=1, B=1, C=1, D=0)
 - Ray (A=1, B=1, C=2, D=0)
 - Segment (A=1, B=2, C=2, D=2)
 - Sphere (A>=1, B=2, C=2?, D=0)
 - Plane (A=2, B=1, C=1, D=0)
 - Halfplane (A=2, B=1, C=2, D=0) (does not exist yet)
 - CylinderSurface(A=2, B=2,C=0,D=0)
 - Triangle (A=2, B=2, C=2, D=3)
 - Quadrangle (A=2,B=2,C=2,D=4)
 - Ngons...
 - Box (A>=2, B=2, C=0, D=0)
 - Ball(A>=2, B=2, C=0,D=0)
 - Cylinder, Pyramid, Tetrahedron, ... (A=3, B=2, C=0, D=?)
Not sure where to put PolyArea...

**Comment by juliohm** [comment]
Can you please confirm that you are using A, B, C, D for lexicographic comparison? That is, if the criterion A is not available, we use criterion B, then C, then D?

PolyArea and Ngon are both instances of Polygon

**Comment by juliohm** [comment]
> regarding not callable geometries, sphere(u, v) would be great, with u, v being spherical coordinates θ ∈[0, π] and ϕ ∈[0, 2π].
> Box and Ball should be also callable with N arguments
> Pyramid, Cylinder and Tetrahedron should be callable with 3 arguments

It would be nice to open an issue for these so that we don't forget to fix it at some point :)

**Comment by dorn-gerhard** [comment]
I checked all objects within primitives and polytopes: 
`types = [subtypes(Primitive); subtypes(Polytope)]`

I created a sample vector of all those objects:

``` julia
elem = [
       Ball((2.,2.), 2), 
       BezierCurve(Point2[(0.,0.),(1.,-1.), (2.3,4)]),
       Box((1,1), (2.,3)), 
       Cylinder(4, Segment((2,3,4), (1,2,3))), 
       CylinderSurface(4, Segment((2,3,4), (1,2,3))), 
       Line((1,2), (3,4)),
       Plane((2,3,4), (1,2,3), (5,3,2)), 
       Ray((1,2,3), (1,2,3)),
       Sphere((3,2,1), 2), 
       Chain((2,3), (1,2), (4,3)), 
       Hexahedron((1,2,3), (0,0,1), (1,0,0), (1,1,0), (2,3,2), (3,1,3), (1,2,1), (2,3,5)), 
       Ngon((2,3,4), (1,2,3), (1,2,4)), # Triangle
       Ngon((2,3,4), (1,2,3), (1,2,4), (6,5,3)), # Quadrangle
       Ngon((1,2), (3,1), (3,4), (9,4), (9,5), (2,3)),  # Hexagon
       PolyArea(Chain((1,2,3), (0,0,1), (1,0,0), (1,1,0), (2,3,2), (1,2,3))), 
       Pyramid((1,2,3), (1,2,5), (1,4,2), (1,4,5), (3,3,3)), 
       Segment((12,3,4), (1,2,9)), 
       Tetrahedron((1,2,3), (1,4,2), (5,2,3), (2,3,1))]
```

`paramdim` and `measure` now works for all types. 
Some types can be initalized in a wrong way or are not that logical (as pyramid which is always assumed to have a Quadrangle as ground side, wikipedia states: The base of a pyramid can be trilateral, quadrilateral] or of any polygon shape).

Objects which are not callable (yet) are (should be fixed at some point - I open an issue #335 ):
- Ball
- Box
- Cylinder
- CylinderSurface
- Sphere
- Chain (not so sure how)
- Hexagon 
- PolyArea (not so sure how)
- Pyramid (not so sure how)
- Tetrahedron

**Comment by dorn-gerhard** [comment]
> Can you please confirm that you are using A, B, C, D for lexicographic comparison? That is, if the criterion A is not available, we use criterion B, then C, then D?
> 
> PolyArea and Ngon are both instances of Polygon

Yes exactly.
I now provide a complete table for ordering according to this convention:

A. paramdim
B. measure
  1. infinite measure
  2. finite measure

C. domain error
   1. not restricted
   2. restricted

D. nvertices
   - 0: not defined
   - n: actual number of vertices 

This would yield the following order:
| type | A (`paramdim`) | B (finite `measure`) | C (is restricted, `g::geometry(zeros(paramdim(g))...)` only relevant for measure = ``Inf``| D (`nvertices` for Polytope) |
|------|------------------|--------|--|----|
| Point | 0 | 1 | n/c | 1 |
| Line | 1 | 0 | 0 | n/a (primitive)|
| Ray | 1 | 0 | 1 | n/a (primitive)|
| Chain | 1 | 1 | n/c | >= 0 |
| BezierCurve | 1 | 1 | 1 | n/a (primitive)|
| Segment | 1 | 1 | 1 | 2 |
| Sphere | >= 1 | 1 | n/c | n/a (primitive)|
| Plane | 2 | 0 | 0 | n/a (primitive)|
| CylinderSurface | 2 | 1 | n/c | n/a (primitive)|
| PolyArea | 2 | 1 | n/c | >=1 |
| Triangle | 2 | 1 | 1 | 3 |
| Quadrangle | 2 | 1 | 1 | 4 |
| Ngons{k} | 2 | 1 | 1 | k |
| Ball | >= 2 | 1 | n/c | n/a (primitive)|
| Box | >=2 | 1 | n/c | n/a (primitive)|
| Cylinder | 3 | 1 | n/c | n/a (primitive)|
| Tetrahedron | 3 | 1 | n/c | 4 |
| Pyramid | 3 | 1 | n/c | 5 |
| Hexahedron | 3 | 1 | 1 | 8 |


Since Ball and Box are equivalent according to that table I chose a lexicographical order.
n/c means not callable (see issue #335 )
n/a means not available (in general not implemented for primitives, only for polytopes), but only important to order polytopes

**Comment by juliohm** [comment]
That is very nice @dorn-gerhard 🥇  what is your plan of action here? Working on #335 before establishing the final ordering convention?

**Comment by juliohm** [comment]
This is finally fixed on master after a major refactoring of the intersection types. Thanks again for the awesome work creating the above table @dorn-gerhard 💯
