### ISSUE TITLE
Tutorial on simple meshes

### ISSUE THREAD

**Issue by Veenty** [JuliaGeometry/Meshes.jl#328]
I would like to add section in the docs on how to create simple meshes.

Maybe a whole section with tutorials with simple docs could be nice

**Comment by juliohm** [comment]
Thank you @Veenty. You can expand the section we have currently on meshes and add more examples below the basic example with SimpleMesh: https://juliageometry.github.io/Meshes.jl/stable/meshes.html

**Comment by juliohm** [comment]
Closed the PR #330 because the added example was not following the surrounding text and code style.
