### ISSUE TITLE
RectilinearGrid not available in downloadable?

### ISSUE THREAD

**Issue by Veenty** [JuliaGeometry/Meshes.jl#329]
So I just updated Meshes using `add Meshes` , however I'm not able to use RectilinearGrid

when I do status I get

```
[35d6a980] ColorSchemes v3.19.0
  [e9467ef8] GLMakie v0.7.3
  [9ecf9c4f] MeshViz v0.6.1
  [eacbb407] Meshes v0.25.15
  [42171d58] PlyIO v1.1.2
  [3f865c0f] ScatteredInterpolation v0.3.6
```

but I also get 

```
julia> RectilinearGrid
ERROR: UndefVarError: RectilinearGrid not defined

```

Any idea why it could be?

**Comment by juliohm** [comment]
We are still working on the next release. In order to use the version in the master branch you can `add Meshes#master`
