### ISSUE TITLE
API change proposal of Partition(..., ::ProductPartition)

### ISSUE THREAD

**Issue by Petr-Hlavenka** [JuliaGeometry/Meshes.jl#331]
Hi @juliohm, I have a problem with the unstable API of `Partition(..., ::ProductPartition)`. It behaves unpredictably. Where with `BisectPointPartition` I can rely on `left, right = partition(...)`, with ProductPartition I cannot rely on a similar `left, middle, right = partition` pattern. For some unknown reason, it returns a tuple of either one, two or three subsets, depending on how many labels it finds. But, for any reasonable use, I'd prefer to have always access to " ((P1 && !P2), (!P1&&P2), (P1&&P2)). MWE how annoying it is:
```
box = Box(Point3(-1, -1, -1), Point3(1,1,1))
box = simplexify(boundary(box))
pl = Plane((50.0, 0., 0), (0.5, 0.5, 0))
n = normal(pl)
p = origin(pl)
δ = 1e-15
p1 = BisectPointPartition(n, p - δ*n)
p2 = BisectPointPartition(n, p + δ*n)
pp = ProductPartition(p1, p2)
part = partition(PointSet(vertices(box)), pp)
```
returns 
```
1 Partition{3,Float64}
  └─8 View{8 PointSet{3,Float64}}
```
But, I have no idea what those indices are. Do they come from the left? Or right? I have to test one point of the set once more and write complex `if length(part) == 1 .... == 2 ... ==3....` with additional tests and a reshuffling part. Can I propose a change of the interface to return always 3 vectors (that might be empty)? So that one can write stable
```
only_p1, only_p2, p1_and_p2 = partition(...,  ProductPartition(p1, p2))
```

**Comment by juliohm** [comment]
@phlavenk your frustration is coming from the fact that you are not understanding the concepts and we should probably improve the documentation. The partition of a set into subsets is a general concept and does not have anything special with your use case with 3 subsets. The returned object is a partition with N subsets. You can access each subset with Π[1], Π[2], ..., Π[N], or you can collect(Π) to save the subsets into a new vector of objects. Finally, you can use indices(Π) to collect the corresponding indices of the partition in the original set.

```julia
box = Box(Point3(-1, -1, -1), Point3(1,1,1))
plane = Plane((50.0, 0., 0), (0.5, 0.5, 0))

n = normal(plane)
o = origin(plane)
δ = 1e-15 # tight tolerance

pset  = PointSet(vertices(box))
part1 = BisectPointPartition(n, o - δ*n)
part2 = BisectPointPartition(n, o + δ*n)
part  = ProductPartition(part1, part2)

Π = partition(pset, part)

for inds in indices(Π)
  view(pset, inds)
end
