### ISSUE TITLE
Interactive point plot broken in docs

### ISSUE THREAD

**Issue by stillyslalom** [JuliaGeometry/Meshes.jl#332]
Zooming and panning changes the viewport for tick markers and grid lines, but the points themselves are stuck in position. This is most likely an issue with the underlying plotting library (WGLMakie?). Interactivity works as expected for the sphere and rectangle plots.

https://user-images.githubusercontent.com/4324760/204373396-208e776e-8e5b-4639-8cec-a6a02790bf7b.mp4

Video taken in Google Chrome on Windows 11 from https://juliageometry.github.io/Meshes.jl/dev/points.html.

**Comment by juliohm** [comment]
Yes, this is an issue with the Makie stack.

**Comment by stillyslalom** [comment]
This issue, presumably? https://github.com/MakieOrg/Makie.jl/issues/2243

**Comment by juliohm** [comment]
I think asking the Makie maintainers is the way to go here. We are not following their issue tracker.

**Comment by stillyslalom** [comment]
I understand wanting to keep issues tightly focused on Meshes.jl, but this issue *does* impact this repo, even if the source is upstream. It's worth tagging issues in dependencies to make downstream impacts visible to a dependency's maintainers.

**Comment by juliohm** [comment]
But Makie.jl is not a dependency of Meshes.jl. Our only interaction with Makie.jl is through MeshViz.jl, which is a collection of standard Makie recipes.

The issue you linked seems to describe very well the behavior you shared in the video. This behavior should appear in any package documentation that has a 3D scatter with WGLMakie.jl
