### ISSUE TITLE
Geometries missing parameterization

### ISSUE THREAD

**Issue by dorn-gerhard** [JuliaGeometry/Meshes.jl#335]
Objects which are not callable (yet) are (should be fixed at some point):
- [x] Box
- [x] Triangle
- [x] Quadrangle
- [x] Tetrahedron
- [x] Hexahedron
- [x] Ball
- [x] Sphere

**Comment by juliohm** [comment]
Thanks for opening the issue. Can you clarify what you mean by callable in this context? You mean a specific type of constuctor?

**Comment by dorn-gerhard** [comment]
You are welcome. 
not a constructor but to address each point in the geometry.
`paramdim` indicates the number of parameters necessary to address all points in that geometry.

The following should work for all geometries `g`:
`g(zeros(paramdim(g))...)`

e.g. 
``` julia
julia> pl = Plane((0,1,2), (2,3,1), (1,2,3))
Plane{Float64}(Point(0.0, 1.0, 2.0), [2.0, 3.0, 1.0], [1.0, 2.0, 3.0])

julia> pl(0,0)
Point(0.0, 1.0, 2.0)
```

Well for some more complex geometries parametrization might not be unique or straightforward. 
But for the ones in the list, we should implement them (if possible)

**Comment by juliohm** [comment]
I think the more usual term for this is "parameterization". The goal is to make the geometries parametric whenever possible 👍🏽

**Comment by juliohm** [comment]
@jackbeagley this is a list of geometries missing parameterization. As you can see the idea of `g(t)` for `t` in `[0,1]` can also work with 2D and 3D geometries using coordinates `g(u,v)` and `g(u,v,w)` instead. PRs are welcome to add missing parameterizations.

**Comment by juliohm** [comment]
Added parameterization for all geometries in the original list ✅
