### ISSUE TITLE
The 3 methods of `Ploytope` constructor are inconsistent

### ISSUE THREAD

**Issue by lihua-cat** [JuliaGeometry/Meshes.jl#336]
Hi, @juliohm. I just started to use Meshes.jl 2 days ago so maybe I missed something.

I found there are 3 methods to create a `Polytope`

https://github.com/JuliaGeometry/Meshes.jl/blob/0f93828d25078959b2957d35fefca5c3c69b0d6d/src/polytopes.jl#L28-L32

So I tried to create a `Segment` by 3 different methods and expected to get the same result. 
```julia
p1 = Point(0, 0)
p2 = Point(1, 1)

s1 = Segment(p1, p2)            # method 1 in Line 30
s2 = Segment([(0, 0), (1, 1)])  # method 2 in Line 31
s3 = Segment((0, 0), (1, 1))    # method 3 in Line 32

typeof(s1)  # Segment{2, Float64, StaticArraysCore.SVector{2, Point2}}
typeof(s2)  # Segment{2, Float64, Vector{Point2}}
typeof(s3)  # Segment{2, Float64, Vector{Point2}}
```
The type of `s1` constructed by 2 `Point`s is different from the other two. Is this a bug or for some reason?

**Comment by juliohm** [comment]
That is something that we should probably review, thanks for reporting @lihua-cat. I remember initially using `SVector` in some places to have compile-time length information, but I don't think we rely on that anymore. Do you think you can assess the impact of replacing the `SVector` by a simple `Vector`? That would be super helpful.

**Comment by lihua-cat** [comment]
Sorry, I have no experience in developing a programming package. In fact, I have no idea what "assess the impact ..." means. But if there are some guidelines or it just needs some benchmarks maybe I can help.

**Comment by juliohm** [comment]
@lihua-cat you can develop the package, replace SVector by Vector, see if the test suite takes roughly the same time to run, and submit a pull request. Try to go step-by-step, and ask here if you have questions.

**Comment by lihua-cat** [comment]
It seems the `SVector` is neccessary to pass the following test in line 369:
https://github.com/JuliaGeometry/Meshes.jl/blob/0f93828d25078959b2957d35fefca5c3c69b0d6d/test/intersections.jl#L355-L369

Replace the `SVector` by `Vector` will change the behavior of comparing two segments with `===`. According to documents of `===`, `Vector`(mutable) are compared by address in memory and `SVector`(immutable) are compared by contents at the bit level.

Here is a simple example to show the difference:
```julia
using Meshes

# SVector
p1 = Point(0,)
p2 = Point(1,)
s_sv1 = Segment(p1, p2)
s_sv2 = Segment(p1, p2)
typeof(s_sv1)  # Segment{1, Float64, StaticArraysCore.SVector{2, Point1}}
ismutable(s_sv1.vertices)  # false
s_sv1 == s_sv2  # true
s_sv1 === s_sv2  # true

# Vector
s_v1 = Segment((0,), (1,))
s_v2 = Segment((0,), (1,))
typeof(s_v1)  # Segment{1, Float64, Vector{Point1}}
ismutable(s_v1.vertices)  # true
s_v1 == s_v2  # true
s_v1 === s_v2  # false
```

I also compared the benchmark results of `r₂ ∩ s₉`: with `SVector`, the result is 265.282 ns (10 allocations: 400 bytes) and with `Vector`, it is 283.972 ns (11 allocations: 464 bytes).

I think it maybe a good idea to use `SVector` in all 3 `Polytope` constructors but I'm afraid it will affect a lot of things. So, @juliohm, what do you think?

**Comment by juliohm** [comment]
@dorn-gerhard can you please confirm that we don't need === in these tests and that we can use == instead?

@lihua-cat regarding the times from 283ns to 265ns with SVector, anything that is measured in nanoseconds is basically noise. We can't measure performance differences reliably when the code is fast as that. If you can double check that other operations like areas, intersections between different objects, etc are roughly the same speed we can certainly replace SVector by Vector for consistency.

**Comment by dorn-gerhard** [comment]
I think so, we can use == instead of ===

Regarding this special function, we actually need a `isequal(s1::Segment, s2:.Segment)` function that checks returns true for the following two segments: 
``` julia
p1 = Point(1,2,3)
p2 = Point(2,3,1)
s1 = Segment(p1, p2)
s2 = Segment(p2, p1)
s1 == s2 # yields false at the moment
```
We had a short discussion on this issue in #310 to check cyclic permutation in general to introduce a `circequal` ≗ (LaTeX: \circeq) function which should be then the default for ==(::Segment, ::Segment)

If you agree I open a PR for circequal to add it in `utils.jl`. 
It should also be checked for which geometries (e.g. Ngon) this function would be applicable.

**Comment by juliohm** [comment]
As we discussed in the other issue the cyclic definition doesnt make sense
for segment. Our segment is oriented with first and last point.

Em sex., 16 de dez. de 2022 15:19, Gerhard Dorn ***@***.***>
escreveu:

**Comment by lihua-cat** [comment]
@juliohm More benchmarks:
```julia
using Meshes
using BenchmarkTools

T = Float64
P1, P2, P3 = Point{1,T}, Point{2,T}, Point{3,T}
V1, V2, V3 = Vec{1,T}, Vec{2,T}, Vec{3,T}

## case1: segments in 3D
s1 = Segment(P3(0.0, 0.0, 0.0), P3(1.0, 0.0, 0.0))
s2 = Segment(P3(0.5, 1.0, 0.0), P3(0.5, -1.0, 0.0))
@btime $s1 ∩ $s2 # ≈ P3(0.5, 0.0, 0.0)

## case 2: rays and segments in 3D
r₁ = Ray(P3(1,2,3), V3(1,2,3))
s₁ = Segment(P3(1, 3, 5), P3(3,5,7))
@btime $r₁ ∩ $s₁ # ≈ s₁ ∩ r₁ ≈ P3(2,4,6)

## case 3: segments and planes in 3D
p = Plane(P3(0, 0, 1), V3(1, 0, 0), V3(0, 1, 0))
s = Segment(P3(0, 0, 0), P3(0, 2, 2))
@btime $s ∩ $p # == P3(0, 1, 1)

# case 4: ngons and segments in 3D
o = Octagon([P3(0.0,0.0,1.0), P3(0.5,-0.5,0.0), P3(1.0,0.0,0.0), P3(1.5,0.5,-0.5),
                 P3(1.0,1.0,0.0), P3(0.5,1.5,0.0), P3(0.0,1.0,0.0), P3(-0.5,0.5,0.0)])
s = Segment(P3(-1.0, -1.0, -1.0), P3(1.0, 1.0, 1.0))
@btime $o ∩ $s # == P3(0.0, 0.0, 0.0)
```
|  case  | SVector | Vector |
| --- | -------- | ------- |
| 1 |  2.000 μs (41 allocations: 68.88 KiB) |  2.000 μs (41 allocations: 68.88 KiB) |
| 2 |  2.200 μs (41 allocations: 68.88 KiB) |  2.289 μs (41 allocations: 68.88 KiB) |
| 3 | 36.593 ns (1 allocation: 48 bytes) | 58.087 ns (2 allocations: 160 bytes) |
| 4 | 14.100 μs (225 allocations: 18.47 KiB) | 13.700 μs (225 allocations: 18.19 KiB) |

roughly the same speed. Can I submit a pull request now (including replace === by == in these tests)?

**Comment by juliohm** [comment]
@lihua-cat what about the entire test suite? If you make the change the entire test suite takes roughly the same amount of time? Please feel free to start a PR with the fixes, that would be a good way of testing the change in different platforms as well.
