### ISSUE TITLE
Torus passing through three given points

### ISSUE THREAD

**Issue by stla** [JuliaGeometry/Meshes.jl#337]
Hello,

The code in [this gist](https://gist.github.com/stla/cc7b9bc580c8e299931089d821734685) allows to create a mesh of a torus whose "equator" passes through three given points. Maybe you would like to include that in the package.

**Comment by juliohm** [comment]
You mean defining a new primitive type called Torus and methods to discretize it into a mesh? That would be a good addition 👍🏽

**Comment by stla** [comment]
Yes, but I especially wanted to promote my transformation :-D Here is an application:

![Capture du 2022-12-14 22-34-35](https://user-images.githubusercontent.com/4466543/207719943-ee74853d-0bf3-4072-8a59-e7b09558f2eb.png)

**Comment by juliohm** [comment]
I will close this issue as well because it doesn't follow our guidelines. If you have a specific feature in mind that you would like to contribute, please open the issue and submit a PR for review. Other comments and discussions can be redirected to our Zulip channel.

**Comment by stla** [comment]
But I'm not very familiar with your package, sorry. I don't know how you deal with "primitives" and "discretizations".

**Comment by stla** [comment]
What is your Zulip channel? Some Github repo have a "Discussions" section, but I don't see one here.

**Comment by juliohm** [comment]
The direct link for the Zulip channel is in the README. Copying it here:

https://julialang.zulipchat.com/#narrow/stream/275558-meshes.2Ejl
