### ISSUE TITLE
Point embedded in R^1

### ISSUE THREAD

**Issue by henry2004y** [JuliaGeometry/Meshes.jl#34]
Hi,

I found another potential bug for allocating a `CartesianGrid` object. Following the [example in the document](https://juliageometry.github.io/Meshes.jl/dev/meshes.html#Meshes.CartesianGrid)
```
a = CartesianGrid((-1.,),(1.,), dims=(100,))
```
This operation can never finish, no matter what values I input for `dims`. I also tried
```
a = CartesianGrid((100,),(10.,),(1.,))
```
Same issue I guess.

**Comment by juliohm** [comment]
Yes, I think this is actually related to another issue about creating points in R^1. We need to add a constructor to handle the case `Point(1.0)` for example with a single coordinate.
