### ISSUE TITLE
Revert the orientation of the faces in a topolgy

### ISSUE THREAD

**Issue by stla** [JuliaGeometry/Meshes.jl#347]
Hello,

The [Dupin cyclide](https://en.wikipedia.org/wiki/Dupin_cyclide) can be obtained by applying a [geometric inversion](https://en.wikipedia.org/wiki/Inversive_geometry) to a torus. So, starting with a mesh of a torus, I applied the geometric inversion to the vertices of this mesh to obtain the vertices of the cyclide, and I made a mesh of the cyclide by using the same topology as the one of the torus mesh. Unfortunately, the orientation of the faces obtained in this way is not the good one: when I plot the mesh, I can see that the normals should be negated. Is there a convenient way to inverse the orientation of the faces of a topolgy? Or maybe I am in a wrong way?

**Comment by stla** [comment]
Otherwise, the simplest way I can see is to reverse the range of one of the two parameters in the construction of the vertices of the torus (i.e. going from pi to -pi instead of going from -pi to pi).

**Comment by juliohm** [comment]
> Is there a convenient way to inverse the orientation of the faces of a topolgy? Or maybe I am in a wrong way?

Please use the Zulip channel to ask user questions. If a feature is missing, we can then write an appropriate issue to track work.
