### ISSUE TITLE
Add `origin` and `direction` for other "LineLike" structures

### ISSUE THREAD

**Issue by jackbeagley** [JuliaGeometry/Meshes.jl#366]
There are three "LineLike" objects in Meshes.jl - Lines, Rays and Segments. Currently only `Ray` has the functions `origin` and `direction`. Given the similarities between these objects, I propose that `origin` and `direction` are implemented for these other objects as well. Keen to hear others thoughts!

**Comment by juliohm** [comment]
As we discussed in the recent PR you contributed, we can easily work with `g(1) - g(0)` as a generic alternative for the "direction" and with `g(0)` for the "origin" of the geometry `g` .

Regarding direction, it is a concept that makes sense for oriented geometries and we could consider it for Segment, given that our segment is oriented. It doesn't make sense for Line given that lines don't have an orientation.

Regarding origin, it is an asymmetric concept that doesn't make sense for Line and probably not for Segment either.

For the sake of a simple design that is minimalistic, the suggested approach with parametrizations `g(t)` for `t` in `[0,infinity]` is preferred.
