### ISSUE TITLE
Low priority: consistency with implicit conversion in Point constructors

### ISSUE THREAD

**Issue by FPGro** [JuliaGeometry/Meshes.jl#37]
This is a reference to small inconsistencies that were left over from the #35 fix. Point constructors for all dimensions work now, but a small inconsistency remains with mixed-type inputs: Implicit conversion is disallowed for some constructors but not all:

```julia
julia> Point(0, 1.) # this is good
ERROR: MethodError: no method matching Point(::Int64, ::Float64)
Closest candidates are:
  Point(::V...) where V at REPL[7]:1
...

julia> Point((0, 1.)) # this is especially undesirable
Point{1, Tuple{Int64, Float64}}([(0, 1.0)])

julia> Point([0, 1.]) # implicit conversion
Point{2, Float64}([0.0, 1.0])

julia> Point{2,Float64}(0, 1.) # good
ERROR: MethodError: no method matching Point{2, Float64}(::Int64, ::Float64)
Closest candidates are:
  Point{Dim, T}(::V...) where {Dim, T, V} at REPL[5]:1
...

julia> Point{2,Float64}((0, 1.)) # needs a better error message
ERROR: DimensionMismatch("Can't construct a Point{2,Float64} with an input of length 1")
...

julia> Point{2,Float64}([0, 1.]) # implicit conversion
Point{2, Float64}([0.0, 1.0])
```

One should decide to either allow or forbid implicit conversion in all Point constructors and enforce that scheme. (But this is really not a pressing issue)

BTW: A few tests were created but disabled until consistency is enforced:
https://github.com/JuliaGeometry/Meshes.jl/blob/c010bab3913fe5a88466ad0948d0dcb1e0b4b83f/test/points.jl#L79

**Comment by juliohm** [comment]
Amazing @FPGro , thanks for opening the issue. Feel free to tackle it if you have ideas. 💯

**Comment by juliohm** [comment]
@FPGro do you have a suggestion to fix this one? I am working actively in other fronts of the codebase and help with these constructors would be awesome. You are the master of constructors 🥇

**Comment by FPGro** [comment]
@juliohm Sure, though I leave it as a first issue for somebody else but it shouldn't be too hard, I can try it.

What's the decision on behavior? Forbid implicit conversion everywhere? And should there be restrictions on the element type of `Point`?
I'm especially thinking about weird edge cases like `Point{N, Tuple{Int, Int}}` or so, should those be allowed?

**Comment by juliohm** [comment]
I think forbidding implicit conversion everywhere sounds reasonable. Regarding the extra constraint on the type of coordinates, let's leave this untouched. We never know how people will use the package. :)

**Comment by serenity4** [comment]
Since implicit conversions are natural for arrays, why wouldn't it be the case for points? Especially if the point type is specified as in `Point{2, Float64}(0, 1.)` where I believe implicit conversion should occur. What about `Point{2, Float64}(0, 1)` by the way? Typing in the dots to have float literals is good practice, but maybe we shouldn't make it a hard requirement. In the case where the point type is not specified (`Point(0, 1.)` for example), wouldn't we want to have a similar behavior as for arrays and therefore allowing implicit conversions?

**Comment by juliohm** [comment]
I think the main issue here is performance. Whenever we throw an error about implicit conversions users will be aware of the issue and likely fix their code to avoid unnecessary conversions in large point clouds. I can't see an application where mixed coordinate types make sense other than space-time reference systems. If all the coordinates live in a spatial coordinate system, which I think is the scope of this package then we better avoid conversions, agree?

Let me know what do you think. I feel weird typing `Point(2, 2., 2f0)` for example.

**Comment by juliohm** [comment]
Sorry I confused things a bit. We already have a design that forces a single coordinate type, the parameter T of the Point{Dim,T}. However the discussion here is about supporting conversions in constructors. I feel that we shouldn't allow it in order to warn users of potential unnecessary conversions in their use cases.

**Comment by FPGro** [comment]
Would it make sense to set up a tiny benchmark for point creation to see the impact of pure or mixed argument types to the constructor?

**Comment by serenity4** [comment]
I believe that if you have large point clouds, you wouldn't specify points by hand. Therefore you would rely on variables that already have some type, and the points would just wrap around that type. If whatever you put into the points have inconsistent types, then the problem comes from the point cloud coordinate generation process.

However, if you just want to type in a point manually, I see frequent situations where you would type `Point2(1, 2)`, then have an error, and have to replace that with `Point2(1., 2.)` for example. In that case it is really OK, performance loss will be minimal, and forbidding it would imho degrade user experience.

**Comment by serenity4** [comment]
@FPGro Yes, that would be ideal to make better informed decisions. I believe a benchmark suite for Meshes in general would be quite handy as well at some point.

**Comment by juliohm** [comment]
@serenity4 the example you gave with `Point2(1,2)` works fine with the current implementation, can you please clarify with another example?

**Comment by juliohm** [comment]
I just feel that we may over-complicate the design to support a rare use case where users mistype a dot here and there. It is good to have a benchmark, but code complexity is also an important dimension to keep in mind.

**Comment by serenity4** [comment]
`Point2(1., 2)` then?

Edit: even `Point(1., 2)`, if you typed a dot you would probably mean float coordinates.

**Comment by serenity4** [comment]
With `Base.promote_rule` overloads, it shouldn't be much work, right?

**Comment by juliohm** [comment]
You would like to see this one working? It is not clear to me that this type of typo would be common in the wild. But I am looking forward to benchmarks and to the proposed solution. 👍🏽

**Comment by serenity4** [comment]
Yes, I would like to see it working _exactly_ as `[1., 2]` for better consistency with Julia array types. Most people will think of points as arrays of numbers anyway. `SVector{2, Float64}(1., 2)` works as well AFAIK. So basically, I think all implicit conversions should happen like Julia arrays.

**Comment by serenity4** [comment]
I can try a PR soon if you like.

**Comment by juliohm** [comment]
That would be awesome. Please double check with @FPGro to make sure you guys are not spending time on the same task 👌🏽

**Comment by FPGro** [comment]
@serenity4 You want to PR a benchmark or a change in constructors?

I don't think you even need `promote_rule` here, the construction of the internal `StaticVector` should do this already :D less may be more here, let's see

**Comment by serenity4** [comment]
I was going for the change in constructors + a small micro-benchmark in the description (not included in the PR, but just to test the conversion performance penalty). If you want I can let you do that, since you are already familiar with constructors. Then I could do a PR with more elaborate benchmarks (though you may want to do your own micro-benchmark for the PR) and open another benchmarking issue in the process.

**Comment by FPGro** [comment]
@serenity4 sounds good

**Comment by FPGro** [comment]
Microbenchmark for constructing SVectors in different ways, because these are the speeds we ultimately want to match:

Input: | Int | Float | Mixed
-------|----|-------|---------
SVector(x,y,z):      |   2.700 ns (allocs: 0)   | 2.400 ns (allocs: 0) |   2.400 ns (allocs: 0)
SVector((x,y,z)):    |   33.551 ns (allocs: 1)  | 32.998 ns (allocs: 1) |  36.419 ns (allocs: 1)
SVector([x,y,z]):   |    Error           |        Error            |       Error
SVector{S,T}(x,y,z):  |  2.400 ns (allocs: 0)  |  2.400 ns (allocs: 0)  |  2.400 ns (allocs: 0)
SVector{S,T}((x,y,z)): | 32.430 ns (allocs: 1) |  35.851 ns (allocs: 1) |  34.542 ns (allocs: 1)
SVector{S,T}([x,y,z]): | 2.400 ns (allocs: 0)  |  2.400 ns (allocs: 0)  |  295.638 ns (allocs: 2)

Note: the very last measurement deliberately uses inputs of type `Vector{Real}`, hence the high cost. Those are hard to come by in real code and we shouldn't worry about those too much. Aside from that, using `Vector`s as input or the elements directly seems to be the best idea here.

Appended: microbench skript, as a .txt because GitHub
[benchSA_copy.txt](https://github.com/JuliaGeometry/Meshes.jl/files/6000248/benchSA_copy.txt)

**Comment by FPGro** [comment]
I'll try the `Point` constructors tomorrow, but they shouldn't be too far off. Considering the high performance and negligible cost of mixed input, it would probably do more harm than good (for performance) to explicitly check that inputs don't have mixed types.

**Comment by FPGro** [comment]
The current definition gives these timings:
Input:              |    Int              |       Float            |       Mixed
-----------------|--------------|------------------|--------------
Point(x,y,z):        |   6.200 ns (allocs: 0)  |  2.400 ns (allocs: 0)   | Error
Point((x,y,z)):      |   58.996 ns (allocs: 1)  | 83.060 ns (allocs: 1)  | 90.259 ns (allocs: 1)
Point([x,y,z]):      |   2.456 μs (allocs: 11)  | 4.456 μs (allocs: 11) |  3.267 μs (allocs: 16)
Point{S,T}(x,y,z):    |  5.600 ns (allocs: 0)  |  7.900 ns (allocs: 0)  |  Error
Point{S,T}((x,y,z)):  |  90.997 ns (allocs: 1) |  50.307 ns (allocs: 1) |  Error
Point{S,T}([x,y,z]): |   5.100 ns (allocs: 0)   | 6.500 ns (allocs: 0)   | 635.242 ns (allocs: 2)

`Point([x,y,z])` is terrible, the rest is fine even if not optimal. Mixed-type inputs hardly make any difference, so allowing them should be fine.

**Comment by FPGro** [comment]
Slight rewrite with 1 inner and just 4 outer constructors gives:

Input:              |    Int             |        Float            |       Mixed
----------------|--------------|--------------------|---------------
Point(x,y,z):        |   2.700 ns (allocs: 0)  |  4.700 ns (allocs: 0)  |  4.500 ns (allocs: 0)
Point((x,y,z)):      |   31.992 ns (allocs: 1)  | 66.940 ns (allocs: 1) |  61.631 ns (allocs: 1)
Point([x,y,z]):       |  346.840 ns (allocs: 1) | 305.839 ns (allocs: 1) | 711.842 ns (allocs: 5)
Point{S,T}(x,y,z):    |  4.100 ns (allocs: 0)   | 4.100 ns (allocs: 0)  |  4.100 ns (allocs: 0)
Point{S,T}((x,y,z)):  |  37.829 ns (allocs: 1) |  58.350 ns (allocs: 1) |  62.877 ns (allocs: 1)
Point{S,T}([x,y,z]):  |  4.700 ns (allocs: 0)   | 4.800 ns (allocs: 0)  |  322.568 ns (allocs: 2)

Note that the things with just a couple of `ns` are all about equally fast due to fluctuations.

This looks pretty good, although I've yet to check the behaviour with invalid inputs and especially wrongly specified dimensions. I think this is not caught yet. I'll PR and see what the tests do.

**Comment by FPGro** [comment]
PR's out #42 

In case anybody want's to run it themselves, here's the benchmark skript for `Point`s, again renamed to .txt because GitHub won't let me append .jl files to a comment :octocat: 
[bench_copy.txt](https://github.com/JuliaGeometry/Meshes.jl/files/6001928/bench_copy.txt)

**Comment by juliohm** [comment]
Fixed on master.
