### ISSUE TITLE
How do I extract all the faces of a cube element?

### ISSUE THREAD

**Issue by AhmedSalih3d** [JuliaGeometry/Meshes.jl#372]
Hello everyone!

I am trying to do something, which I hope is relatively simple. Using Meshes.jl I have drawn a single cube element:
And now I want to loop over its faces. Since it is a cube it has 6 faces.

Is there some specific function in Meshes.jl I have to use to do this?
I've tried stuff as collect(faces(grid,3)) but it just doesn't seem to work. The code is really simple:

```julia
using Meshes
using MeshViz
using GLMakie
using LinearAlgebra
using Statistics

grid = CartesianGrid(1,1,1)
display(viz(grid , showfacets = true, alpha=0.25))
```

**I really dislike asking here, but now I have tried asking on Discourse, Slack and Zulip** To me this seems like an extremely simple operation, I just cannot figure out the syntax **anywhere**.

Kind regards

**Comment by AhmedSalih3d** [comment]
@nick-adamowicz was kind enough to share with me the following information on slack:

```Unfortunately, it looks like the boundary mapping from faces -> vertices is not yet implemented for 3-D cartesian grids in Meshes.jl. This is from the Meshes.jl source,
# vertices of quadrangle on 3D grid
function (∂::Boundary{2,0,3,T})(ind::Integer) where {T<:GridTopology}
  @error "not implemented"
end
Time to submit a pull request :)
if you're fine doing whatever you're doing in 2-D, this is the equivalent,
using Meshes

# 2 x 2 cartesian grid
cart_grid = CartesianGrid((2,2))

# this maps *elements* (quads)  -> *facets* (edges)
b_2_1 = Boundary{2,1}(cart_grid.topology)

# this maps *facets* (edges) -> *vertices*
b_1_0 = Boundary{1,0}(cart_grid.topology)

# returns the *facet* (edge) indices of *element* (quad) 1
edges = b_2_1(1)

# returns the *vertex* indices of *facet* (edge) 4
verts = b_1_0(4)

# returns the points (coordinates) corresponding to each vertex in verts
vertices(cart_grid)[verts]
```

I am really perplexed that one cannot easily extract face / vertex relations from a 3D element in Meshes.jl? Isn't this extremely basic functionality or is there some complexity which I do not understand?

Perhaps no-one else has ever had a use for extracting faces from 3D elements in Julia? Seems weird to me too :)

Just providing information here, so if anyone else ends up struggling like me, then it seems like it is just not possible.

Kind regards

**Comment by juliohm** [comment]
Please use the Zulip channel for questions, it is easy to achieve what you do but GitHub isn't the place to ask.

**Comment by AhmedSalih3d** [comment]
I fully agree!

I let a bit of frustration get to me, since I could not get it to work at all or find any syntax / someone who could explain it to me. Sorry for my passive aggressive message and thank you very much. For anyone finding this thread for the answer here it is:

grid = CartesianGrid(1,1,1)

boundary(grid[1])
6 SimpleMesh{3,Float64}
  8 vertices
    └─Point(0.0, 0.0, 0.0)
    └─Point(1.0, 0.0, 0.0)
    └─Point(1.0, 1.0, 0.0)
    └─Point(0.0, 1.0, 0.0)
    └─Point(0.0, 0.0, 1.0)
    └─Point(1.0, 0.0, 1.0)
    └─Point(1.0, 1.0, 1.0)
    └─Point(0.0, 1.0, 1.0)
  6 elements
    └─Quadrangle(4, 3, 2, 1)
    └─Quadrangle(6, 5, 1, 2)
    └─Quadrangle(3, 7, 6, 2)
    └─Quadrangle(4, 8, 7, 3)
    └─Quadrangle(1, 5, 8, 4)
    └─Quadrangle(6, 7, 8, 5)
