### ISSUE TITLE
Add a formatting style

### ISSUE THREAD

**Issue by kylebeggs** [JuliaGeometry/Meshes.jl#376]
Some of the source code has formatting errors / the style is not consistent. We should add a `.JuliaFormatter.toml` to the repo with the settings we want and require contributors run that before merging a PR.

**Comment by juliohm** [comment]
Thank you @kylebeggs. If you have familiarity with the bot, please feel free to submit a PR and we can review the code style together.

**Comment by kylebeggs** [comment]
By bot, do you mean GitHub Actions? Honestly I don't know much about that. But at the minimum we can come up with the settings for the code style and create the `.JuliaFormatter.toml` which the bot will need anyways. At least that way contributors can just run it manually (or do format on save like I do when editing).

**Comment by juliohm** [comment]
That would be awesome. Let's start with a JuliaFormatter.toml and see how to configure GitHub Actions later. We can try to adapt the actions from other packages that already use the formatter.
