### ISSUE TITLE
Find normal vector at each point in 3D space

### ISSUE THREAD

**Issue by Dale-Black** [JuliaGeometry/Meshes.jl#383]
Given a matrix of 3D points where `columns = x, y, z` locations and `rows = points`, how would you use meshes to find the normal vector at each point?

e.g.
```julia
points = [
 202  279   8
 202  280   9
 209  278  10
 210  283  12
 212  286  14
 219  295  16
 225  300  18
 234  308  20
 238  305  22
 236  300  24
 233  295  26
 231  289  28
 227  280  30
 223  275  31
]
```

**Comment by Dale-Black** [comment]
I guess this is just a central difference calculation, actually?

**Comment by juliohm** [comment]
@Dale-Black please use our Zulip forum for questions of usage.
