### ISSUE TITLE
`Point(1)` provokes an infinite type recursion

### ISSUE THREAD

**Issue by plut** [JuliaGeometry/Meshes.jl#39]
This also happens when calling the fully-specified constructor `Point{1,Int}(SA[1])`. (I don't think there is right now any way to define a 1-dimensional point!). The simplest way to fix this is probably to define an inner constructor.

**Comment by juliohm** [comment]
@plut can you please confirm the version of the package you are using? This issue was fixed by @FPGro in the latest release.
