### ISSUE TITLE
`adjacencymatrix()` function doesn't work with HalfEdgeTopology

### ISSUE THREAD

**Issue by mm-crj** [JuliaGeometry/Meshes.jl#397]
When I try to import a mesh(say form Gmsh) using `SimpleMesh` as:
```julia
mesh = SimpleMesh(points, cells, relations = true)
```
and then try to find the adjacency of the cells, by:
```julia
adjacencymatrix(mesh)
```
 then it fails due to the [unimplemented function here](https://github.com/JuliaGeometry/Meshes.jl/blob/a0487c6824d6ee9d7389edc25ae937f1e4cf26fd/src/toporelations/adjacency.jl#L105-L108).

### Minimum Working Example

```julia
using Meshes
points = [(0,0),(1,-1),(1,1),(2,-1),(2,1)]
cells = connect.([(1,2,3),(3,2,4,5)])
mesh = SimpleMesh(points, cells; relations = true)
adjacencymatrix(mesh)
```

**Comment by juliohm** [comment]
@mm-crj the method is now available in the master branch. We will trigger a release as soon as possible.
