### ISSUE TITLE
Benchmarking infrastructure

### ISSUE THREAD

**Issue by serenity4** [JuliaGeometry/Meshes.jl#40]
As discussed in #37, we could benefit from benchmarks for:
- informing the users of the costly and cheap functions
- tracking performance regressions during development

It can be implemented first as a simple `benchmark` folder, and possibly added as a GitHub action is desired.

**Comment by juliohm** [comment]
Fixed on master ❤️

**Comment by Arkoniak** [comment]
This issue looks closed, but still it may be of interest to you. You can use https://github.com/tkf/BenchmarkCI.jl to make automated benchmarking on pull requests. We used it in ParallelKMeans.jl and it was rather handy. You need benchmarks.yml in github_action folder, like here: https://github.com/PyDataBlog/ParallelKMeans.jl/blob/master/.github/workflows/benchmarks.yml

and `benchmark` directory with necessary scripts, like here https://github.com/PyDataBlog/ParallelKMeans.jl/tree/master/benchmark

Then you can either build benchmarks locally and in judge mode compare benchmarks to the master or get results as a part of PR, like here: https://github.com/PyDataBlog/ParallelKMeans.jl/pull/101#issuecomment-784559581

**Comment by serenity4** [comment]
Yes, this is exactly what we did in #41 and #50. Thank you for pointing it out though, this is a very handy package.
