### ISSUE TITLE
`isconvex` does not work for polygons in higher-dimensional spaces

### ISSUE THREAD

**Issue by mfsch** [JuliaGeometry/Meshes.jl#405]
For a 2D polygon, the `isconvex` function works as expected:

```julia
julia> isconvex(Ngon(Point2[(0,1),(1,1),(1,0),(2,2)]))
false
```

However, the same polygon in a 3D space is not considered convex:

```julia
julia> isconvex(Ngon(Point3[(0,1,0),(1,1,0),(1,0,0),(2,2,0)]))
true
```

This is because `isconvex` relies on `innerangles`, but the angle function `∠(u, v)` cannot produce a signed angle in three dimensions. Instead of relying on the orientation of the polygon (CW/CCW does not really have a meaning in 3D), we can just rely on the normal vector of the polygon instead. I’ve added an implementation of this approach in my PR #404 for adding the Prism geometry, since I wanted to have a working `isconvex` for the Prism. I’ve also changed the argument types of the existing `innerangle` and `orientation` functions to give an error if the space is not 2D. However, I think for the current approach to work in N dimensions we would have to add a more general implementation of `normal` and `×`.

I also just saw that the issue in 3D has come up before in #135 – perhaps this issue should be reopened and the proposed approach of adding a reference vector could be reconsidered? This is basically what I ended up doing to fix the 3D case, except that I didn’t modify the angle function and kept everything in `innerangles`.

**Comment by juliohm** [comment]
This issue is related to #396 where we are currently discussing what should be the angle definitions adopted in 2D and 3D. Your input there is very welcome.

**Comment by juliohm** [comment]
Depends on #409

**Comment by juliohm** [comment]
Update: the function now works with all primitives and some 3D polytopes that are convex from the type itself.

**Comment by juliohm** [comment]
Fixed already:

```julia
julia> isconvex(Ngon((0,1,0),(1,1,0),(1,0,0),(2,2,0)))
false
```
