### ISSUE TITLE
Define a function to get a single vertex of a polytope

### ISSUE THREAD

**Issue by mfsch** [JuliaGeometry/Meshes.jl#406]
At the moment, most Polytopes are represented internally with a list of vertices. However, in some cases it may make sense to choose a different internal representation to avoid storing redundant vertices and to make it harder to violate assumed invariants of a geometry. Concrete examples are the existing Box and the Prism geometry proposed in #404. For those, the `vertices` function is no longer a trivial computation that simply returns the internal representation, and generally has to allocate a vector.

I think it would make sense to introduce a function `vertex(geo::Geometry, ind::Int)` to get the i-th vertex of a geometry. This can be defined as `vertices(geo)[ind]` by default, but it allows geometries such as Box and Prism to define `vertex` to dynamically compute the i-th vertex and have `vertices(geo) = collect(vertex(geo, ind) for ind in 1:nvertices(geo))`. The naming `vertex` would be consistent with a similar `facet(m, ind)` function defined for meshes.

This also makes it possible to iterate over the vertices of a geometry without allocating a vector without having to change the return type of `vertices` to a generator or statically-allocated array for geometries like Box & Prism.

**Comment by juliohm** [comment]
I like the idea @mfsch , it generalizes well what we currently have with faces 👍🏽

**Comment by juliohm** [comment]
@mfsch I've closed the last PR because of our recent improvements with the Box type. Feel free to submit another PR with the `vertex` function if you feel it is still needed to avoid allocations, or feel free to close this issue if that is not the case anymore.

**Comment by mfsch** [comment]
@juliohm, the main reason for this suggestion was the Prism type, not the Box. In my use of the Prism type, I need a way to access the vertices in an efficient manner, without building and allocating a new array of vertices each time. I think the `vertex` function is the cleanest way of enabling this without changing the return type of `vertices`.

**Comment by juliohm** [comment]
Makes total sense @mfsch , let's start a clean PR with the new vertex function, this time without touching on Box as it doesn't have vertices anymore.

**Comment by mfsch** [comment]
I’ve updated [the corresponding branch](https://github.com/mfsch/Meshes.jl/tree/vertex-function). Do you just want to reopen the previous PR? I think that should update it to the current version of the `mfsch:vertex-function` branch.

**Comment by juliohm** [comment]
Apparently GitHub doesn't allow to reopen the PR in this case. Can you submit a new one?

**Comment by mfsch** [comment]
Addressed in #414.
