### ISSUE TITLE
Fix RegularSampling for Ball

### ISSUE THREAD

**Issue by ErickChacon** [JuliaGeometry/Meshes.jl#426]
`discretize` a 2D Ball is not working adequately. For example, when sampling points homogeneously inside a ball returns incorrect points.

```julia
D = Ball(Point(20,20), 10)
ps = sample(D, HomogeneousSampling(500)) |> collect
viz(D)
viz!(ps, color = :red)
```
![incorrect](https://github.com/JuliaGeometry/Meshes.jl/assets/7862458/46c08591-a936-4893-949d-dea396c7a46a)

**Comment by juliohm** [comment]
Can you please confirm this is the master version? I remember fixing
something recently in our RegularSampling method used in the discretization.

Em qui., 25 de mai. de 2023 19:06, Dr. Erick A. Chacón Montalván <
***@***.***> escreveu:

**Comment by ErickChacon** [comment]
Yes, the latest master version.

**Comment by ErickChacon** [comment]
Previously, it was not possible to use `Homogeneous`  sampling inside a Ball. Now it is posssible, but the `discretize` function is not working adequately when the center of the Ball is not around **0**.  However, sampling can inside a Ball can be more easily tackle as in PR JuliaGeometry/Meshes.jl#425.

**Comment by juliohm** [comment]
This is because our RegularSampling method for Ball is incorrect:

https://github.com/JuliaGeometry/Meshes.jl/blob/108956197bb473da0ca4c81298c689de02d4c7b0/src/sampling/regular.jl#L47-L62

We need to reimplement it in terms of the new parametric representation of Ball:

https://github.com/JuliaGeometry/Meshes.jl/blob/108956197bb473da0ca4c81298c689de02d4c7b0/src/primitives/ball.jl#L50-L71

**Comment by ErickChacon** [comment]
@juliohm The current regular sampling looks like the following:

![regular](https://github.com/JuliaGeometry/Meshes.jl/assets/7862458/3a41c6d1-dc69-4d45-8c45-37fcc538b29c)

Is this the expected result of the algorithm? I think the output is not regular sampling. Our output should look like a regularsampling in an squared but filtered those that are inside the circle (of course, computing in a more efficient way). Do you agree with that? Something like the following?

![regular2](https://github.com/JuliaGeometry/Meshes.jl/assets/7862458/5872682f-06ca-4b09-a311-6882bb45bfd4)

**Comment by juliohm** [comment]
@ErickChacon the RegularSampling method is a method that samples points with regular spacing along the parametric dimensions of the geometry. We use these points to construct the mesh manually in the regular discretization method.

**Comment by ErickChacon** [comment]
@juliohm Are you working on this, so should I stop working on this?

**Comment by juliohm** [comment]
Oh didn't know you were working on it. You didn't assign yourself here. I did not start yet. Feel free to continue.

**Comment by ErickChacon** [comment]
> Oh didn't know you were working on it. You didn't assign yourself here. I did not start yet. Feel free to continue.

I cannot self assign me in `Meshes.jl`.

**Comment by juliohm** [comment]
Adding you to the team 👍🏽

**Comment by juliohm** [comment]
Done. You should be able to do it now.

**Comment by juliohm** [comment]
Regarding this issue. What we really need at the end are optional arguments for RegularSampling to handle the end points of the ranges. Sometimes we include the end points and sometimes we don't. I managed to automate this issue partially with isperiodic in the fallback implementation, but we really need additional options in RegularSampling to handle end points differently depending on the geometry.

**Comment by ErickChacon** [comment]
Ok, I will first use the current Ball interface and then manage the options with respect to end points? Do you mean the same for the initial points at r = 0?

**Comment by juliohm** [comment]
Yes, we could first fix the specific issue with Ball and then refactor the code in a separate PR by adding options to the RegularSampling struct to handle the start and end points. Maybe we don't even need options, just a function to dispatch offsets for different geometries internally.
