### ISSUE TITLE
Traits for array-like domains

### ISSUE THREAD

**Issue by juliohm** [JuliaGeometry/Meshes.jl#48]
I am considering adding the following trait for domain types in the package:

```julia
"""
    IsArrayLike{D}

Tells whether or not a domain type `D` behaves as an array of elements
in a geographic space. For example, a Cartesian grid can be seen as an
array of geometries (e.g. quadrangle, hexahedron). This information can
be used to optimize algorithms (e.g. slices, bounding boxes).
"""
@traitdef IsArrayLike{D<:Domain} <- isarraylike(D)
isarraylike(D) = false
```

Do you think this is an appropriate term for the concept? Basically I want to encode the fact that some domains like `CartesianGrid` are just a Cartesian arrangement of connected elements. So computing bounding boxes for example reduces to looking up the first and last elements instead of looping over all elements of the domain.

**Comment by juliohm** [comment]
I think the term `IsGrid` is more appropriate even though I am having a hard time to formalize the exact properties of the grid we are interested in.

**Comment by serenity4** [comment]
An array may have elements of any kind, ordered or not; I think that `IsGrid` would be preferable yes, as it implies a certain order for its elements (in any slice).
A grid seems to imply, however, that you don't have any relation of order when you take something else than a slice (so basically a 1D subset of the grid, a line or row in the 2D case). I mean, a corner of a grid greater than another does not make any sense.

I believe you should properly establish all the properties of this trait, then we can discuss its name. If you need a name right now (and possibly change it later on), I believe you should go with whatever comes to your mind (`IsGrid for example), document that the name will most likely change, and make another PR for the renaming once we figure out what it should be for exactly.

**Comment by serenity4** [comment]
For me, a grid represents a domain that can be formed by extruding coordinates along several dimensions (with a possible transformation, an identity map being for a cartesian domain), so that you only need (n + m) coordinates instead of n x m coordinates in the 2D case. Note that this is just my opinion though.

**Comment by juliohm** [comment]
I like this definition in terms of extrusions, I wonder if there is a consensus somewhere in computational geometry for these properties. I added the `IsGrid` trait as suggested and also a `isgrid` equivalent for new domain types that may want to interop with the package after the fact.

Let's open a separate issue then in the future when things settle down a bit. I am almost here porting all the functionality from GeoStatsBase.jl to here 🙏🏽

**Comment by juliohm** [comment]
Here is the commit: https://github.com/JuliaGeometry/Meshes.jl/commit/7485d4b6c7775118f430973a0f2db5bf7359671a
