### ISSUE TITLE
Documentation is not deployed since 0.31.9

### ISSUE THREAD

**Issue by cserteGT3** [JuliaGeometry/Meshes.jl#511]
It seems that the documentation has not been updated since v0.31.9. I've checked some of the actions and saw many failed ones. I found a few timeouts, but also warnings that the runner runs out of space.
For example [here](https://github.com/JuliaGeometry/Meshes.jl/actions/runs/5380392152) it says that `Uploaded artifact size of 8406896640 bytes exceeds the allowed size of 1 GB. Deployment might fail.` I am not sure, that it is the issue itself, but certainly does not help. Currently I had only time to go until that point, if later I will have time, I'll investigate more.

**Comment by juliohm** [comment]
Thank you for raising this issue to our attention. We will try to fix it over the week.

**Comment by juliohm** [comment]
We figured out that the issue is caused due to the fact that the gh-pages branch is too heavy in terms of memory. Probably because we are adding Makie visualizations to the docs on every release.

In order to address the issue we need to cleanup the Git repository and reduce its size as a whole. We are looking into ways of doing that.

**Comment by cserteGT3** [comment]
I see. Then maybe that is the reason why git operations (pulling and cloning) takes so long.
I'm wondering if it is reasonable to delete older patch release docs? Theoretically those aren't needed anymore. (When e.g. `v0.23.9` is out, `v0.23.0-v0.23.8` could be deleted?) Of course it solves the problem for now, later the branch size will grow again. And as I'm writing this, I realized that the files need to be deleted from git, not a regular folder 🤦 

My other idea is look around other graphics heavy packages (Luxor.jl for example) and see how they manage it.

**Comment by juliohm** [comment]
The issue was solved by manually checking the `gh-pages` branch, and deleting old docs before v0.30 to save space. We will also contact GitHub support to see if they can run `git gc --aggressive --prune` on this remote repository to cleanup all the non-used objects from very old commits.

**Comment by cserteGT3** [comment]
Thank you! It looks great now.
