### ISSUE TITLE
Implement `names` for Data trait

### ISSUE THREAD

**Issue by juliohm** [JuliaGeometry/Meshes.jl#523]
We already have `propertynames` returning a list of symbols.

**Comment by vortex73** [comment]
Could you please elaborate on this issue.

**Comment by juliohm** [comment]
The `names(dataframe)` returns the list of column names as strings. We already have the `propertynames(data)` implemented in our `Data` trait. We just need to convert the symbols to strings.

Would like to try this one @vortex73 ?

**Comment by vortex73** [comment]
Yes sure I would like to try this one.

**Comment by juliohm** [comment]
@vortex73 the implementation can be as simple as `names(data::Data) = string.(propertynames(data))`. We need tests to make sure the function is covered.
