### ISSUE TITLE
Fix JarvisMarch

### ISSUE THREAD

**Issue by juliohm** [JuliaGeometry/Meshes.jl#549]
The JarvisMarch algorithm for convex hulls is not working currently. We need a hot-fix for it.

**Comment by DanielVandH** [comment]
What's wrong with it?

**Comment by juliohm** [comment]
Hi Daniel,

It was failing with very basic point sets, probably because of angle
definitions. I'll try to create a MWE, but you can try it with a couple of
random points as in rand(Point2, 100).

Em sex., 20 de out. de 2023 01:36, Daniel VandenHeuvel <
***@***.***> escreveu:

**Comment by DanielVandH** [comment]
I initially tried some random point sets, e.g. I looked at:

```julia
using Meshes, DelaunayTriangulation, Test
DelaunayTriangulation.getx(p::Point2) = p.coords[1]
DelaunayTriangulation.gety(p::Point2) = p.coords[2]
Base.isless(p::Point2, q::Point2) = Base.isless(getxy(p), getxy(q))
⊢(p, q) = DelaunayTriangulation.circular_equality(p, q)

for _ in 1:10000
    n = rand(3:1000)
    points = rand(Point2, n) 
    ch = convex_hull(points).indices
    ch2_p = hull(points, JarvisMarch()).rings[1].vertices.data
    push!(ch2_p, ch2_p[begin])
    ch2 = indexin(ch2_p, points)
    @test ch ⊢ ch2 
end
```

Nothing goes wrong.

**Comment by juliohm** [comment]
I should have saved the MWE. We probably fixed the bug with some recent changes to our 2D angle calculation.

Will close the issue for now. We can reopen it if the bug reappears.

**Comment by DanielVandH** [comment]
Here is one (potential) issue:

```julia
using Meshes, DelaunayTriangulation, Test
DelaunayTriangulation.getx(p::Point2) = p.coords[1]
DelaunayTriangulation.gety(p::Point2) = p.coords[2]
Base.isless(p::Point2, q::Point2) = Base.isless(getxy(p), getxy(q))

points = [Point2(10(i - 1), 10(j - 1)) for i in 1:10, j in 1:10] |> vec
ch = convex_hull(points).indices
ch2_p = hull(points, JarvisMarch()).rings[1].vertices.data
push!(ch2_p, ch2_p[begin])

_points = [p.coords.coords for p in points]
using CairoMakie
fig = Figure()
ax = Axis(fig[1, 1])
scatter!(ax, _points)
scatter!(ax, _points[ch], color=:red)
scatter!(ax, _points[ch2], color=:green, markersize=9)
```

![8bf0770c603c8bef8601f4ad01e5c954](https://github.com/JuliaGeometry/Meshes.jl/assets/95613936/45b46d9c-8a9a-4ac0-85a4-cb59c0092567)

The green dots (from this package) are still _technically_ a convex hull, although sometimes it tries to get every collinear point while from the top-left part it skips over many of them. What answer do you expect from a case like this? `[(0, 0), (100, 0), (100, 100), (0, 100)]`, all the red dots, or just a technically valid result?

**Comment by juliohm** [comment]
Initially we only considered a technically valid hull, because it seems
difficult to make the output consistent across algorithms. We also have
GrahamScan for example and I think the output will be potentially different.

If there is a way to reduce the number of vertices that would be great.

Em sex., 20 de out. de 2023 20:31, Daniel VandenHeuvel <
***@***.***> escreveu:
