### ISSUE TITLE
Bug in bridge of PolyArea 

### ISSUE THREAD

**Issue by ClaroHenrique** [JuliaGeometry/Meshes.jl#566]
The following PolyArea is presenting a wrong bridge.

```julia
outer = Ring(
  P2(6, 4),
  P2(6, 7),
  P2(1, 6),
  P2(1, 1),
  P2(5, 2)
)
inner₁ = Ring(
  P2(3, 3),
  P2(3, 4),
  P2(4, 3),
)
inner₂ = Ring(
  P2(2, 5),
  P2(2, 6),
  P2(3, 5),
)

poly = PolyArea(outer, [inner₁, inner₂])
b = bridge(poly, width=0.1)
viz(b[1], segmentsize=4)

```

This image is generated:

![image](https://github.com/JuliaGeometry/Meshes.jl/assets/38709777/1522a078-8994-4b00-ab89-92d2d8d4b7b3)

Original polygon:

![image](https://github.com/JuliaGeometry/Meshes.jl/assets/38709777/862a8972-8157-4a72-9218-62ec3ef8b374)

**Comment by juliohm** [comment]
Fixed on master. We now have a new transform Bridge that should fix a couple of hidden bugs like this.

```julia
viz(poly)
```
![image](https://github.com/JuliaGeometry/Meshes.jl/assets/3345261/b324b4b0-f4c1-49ec-98c7-aa71590e6af2)
