### ISSUE TITLE
`CartesianGrid` for more generic number like `Unitful`

### ISSUE THREAD

**Issue by ehgus** [JuliaGeometry/Meshes.jl#579]
I'm trying to combine `Meshes` with `Unitful` for better expression in real-world problems.

Current `CartesianGrid` cannot be initialized with `Unitful` values because they do not pass  [the argument validator](https://github.com/JuliaGeometry/Meshes.jl/blob/094df432961f085b20c90acb140b0f3268dab742/src/mesh/cartesiangrid.jl#L67)

example code is as follows:
```Julia REPL
julia> using Meshes, Unitful

julia> start = Point(0.0u"m", 0.0u"m", 0.0u"m");

julia> finish = Point(1.0u"m", 1.0u"m", 1.0u"m");

julia> g = CartesianGrid(start,finish);
ERROR: DimensionError: 0.0 and 0.01 m are not dimensionally compatible.
```

The problem is solved by specifying the type of "zero":
```Julia
# previous code line
@assert all(>(0), spacing) "spacing must be positive"
# proposed code line
@assert all(>(zero(T)), spacing) "spacing must be positive"
```

I will make the pull request soon.

**Comment by juliohm** [comment]
Very nice @ehgus :)

We will be implementing more improvements on that direction soon.

**Comment by juliohm** [comment]
Fixed and available as a patch release.
