### ISSUE TITLE
Review show methods of all geometries

### ISSUE THREAD

**Issue by juliohm** [JuliaGeometry/Meshes.jl#581]
Base.summary, Base.show and Base.print should be properly defined with sensible output.

**Comment by Jay-sanjay** [comment]
@juliohm  Hello sir , can you please provide information on what you mean by 'sensible output' , I did not get it.

**Comment by juliohm** [comment]
@Jay-sanjay take the Polytope geometries as an example. We want to implement the following:

1. Base.summary should display a short version of the geometry, for example `Segment((0,0), (1,1))`
2. Base.show should display Base.summary in compact mode and should display the current version in verbose mode

If you can work on this, we can gradually improve the other missing parts.

**Comment by Jay-sanjay** [comment]
sure sir I will try to work on it.

**Comment by juliohm** [comment]
Thank you @Jay-sanjay, we will work on it to fasten things up.

**Comment by Jay-sanjay** [comment]
Sure no problem :)
