### ISSUE TITLE
Redirect old docs to new docs

### ISSUE THREAD

**Issue by kylebeggs** [JuliaGeometry/Meshes.jl#582]
The docs show an example for constructing a `PolyArea` [here](https://juliageometry.github.io/Meshes.jl/dev/geometries/polytopes.html), which no longer works. I made an issue instead of just submitting a PR to fix the docs to make sure this was intentional.

**Comment by juliohm** [comment]
The docs are now hosted at MeshDocs. We should redirect the link above to the new site.

Documenter's maintainers added a function for this redirection recently, but we didn't have time to try it:

https://github.com/JuliaDocs/DocumenterTools.jl/pull/76

Any help creating this redirection would be great.

**Comment by juliohm** [comment]
You can access the new docs with the badges on the README.

**Comment by kylebeggs** [comment]
Ok, I see. That would explain it as I usually just google search for the docs page.

**Comment by eliascarv** [comment]
Resolved in 4ddb1a0174b92fa5c117a0bf1c6c0bc37e550dc7
