### ISSUE TITLE
Ngon(Points...) doesn't work anymore: no method matching Ngon(::Vector{Meshes.Point})

### ISSUE THREAD

**Issue by kool7d** [JuliaGeometry/Meshes.jl#584]
I cannot construct points that work for `Ngon`. `Point` in my case creates `Point3`s, which give the error. 
I check the type of the Points and it says `Point3` is an alias for `Point{3, Float64}`, however the `Ngon` method that uses `Point{Dim, T}` doesn't work with them.

```
julia> typeof(pnts[1])
Point3 (alias for Meshes.Point{3, Float64})

julia> Ngon(pnts)
ERROR: MethodError: no method matching Ngon(::Vector{Meshes.Point})

Closest candidates are:
  Ngon(::Meshes.Point{Dim, T}...) where {N, Dim, T}
   @ Meshes --Meshes\7eraM\src\polytopes\ngon.jl:28
  Ngon(::Tuple{Vararg{Meshes.Point{Dim, T}, N}}) where {N, Dim, T}
   @ Meshes --Meshes\7eraM\src\polytopes\ngon.jl:24
  Ngon(::Tuple...) where N
   @ Meshes --Meshes\7eraM\src\polytopes\ngon.jl:27
```

**Comment by kool7d** [comment]
The problem was that it was a Vector, so I just splatted it and now it works.

**Comment by juliohm** [comment]
The internal representation of Ngon now uses tuples of points. We disabled the outer constructor with Vector so that the Julia compiler can aggressively optimize the code in algorithms. You can splat the points in the vector as you did or you can use the PolyArea as a dynamic alternative with an internal vector representation.

**Comment by kool7d** [comment]
Would you recommend using PolyArea instead?

**Comment by juliohm** [comment]
The use case of PolyArea is basically GIS where polygons have thousands of points representing the boundary of a country in the map, possibly with holes. For simple polygons in meshes like Triangle, Quadrangle, up to 20-gons the Ngon is the preferred geometry type.
