### ISSUE TITLE
Frustums with polygonal bases

### ISSUE THREAD

**Issue by cserteGT3** [JuliaGeometry/Meshes.jl#592]
As discussed in #586 we should discover the options for implementing polygon/Ngon based frustums. I found these Wolfram MathWorld links useful:
- [Conical Frustum](https://mathworld.wolfram.com/ConicalFrustum.html)
- [Pyramidal Frustum](https://mathworld.wolfram.com/PyramidalFrustum.html) which is a special case for [Prismatoid](https://mathworld.wolfram.com/Prismatoid.html)

**Comment by juliohm** [comment]
This is already possible via discretization of `FrustumSurface`:

```julia
f = rand(FrustumSurface)
viz(f)

# frustum with pentagon as the basis
m = discretize(f, RegularDiscretization(5, 2))
viz(m, showsegments=true)
```
![image](https://github.com/user-attachments/assets/638e015f-32b5-4a85-9288-fafb4fecc927)
![image](https://github.com/user-attachments/assets/f8620d0c-7b45-4a77-81a4-27623e761716)

The particular case with triangle basis is also known as `Wedge` and is already implemented as a `Polytope`.
