### ISSUE TITLE
Broken unicode in code

### ISSUE THREAD

**Issue by ehgus** [JuliaGeometry/Meshes.jl#600]
Hi, I see a broken unicode: 
https://github.com/JuliaGeometry/Meshes.jl/blob/327333f39c9713a4ae1f55206c8f8e7bcdb1c737/src/boundingboxes.jl#L35

It looks like 
![image](https://github.com/JuliaGeometry/Meshes.jl/assets/18534737/511d2952-3d8b-4ce8-ae7a-824282f802d5)
Does it only happen to me?

**Comment by juliohm** [comment]
It is an issue with the GitHub page. It should show correctly on VSCode or locally on your editor.
