### ISSUE TITLE
`Unitful` value is not promoted to floating `Point` and `Vector` automatically

### ISSUE THREAD

**Issue by ehgus** [JuliaGeometry/Meshes.jl#601]
The current code does not promote the integer `Unitful` values to floating point when constructing `Point` and `Vector`.
It's because their constructor only promote values when the values are a subtype of `Integer`, but all `Unitful` values are not:
https://github.com/JuliaGeometry/Meshes.jl/blob/327333f39c9713a4ae1f55206c8f8e7bcdb1c737/src/primitives/point.jl#L49
```Julia repl
julia> using Unitful; x = 1u"m";

julia> @show isa(x,Integer) typeof(x)
x isa Integer = false
typeof(x) = Quantity{Int64, 𝐋, Unitful.FreeUnits{(m,), 𝐋, nothing}}
Quantity{Int64, 𝐋, Unitful.FreeUnits{(m,), 𝐋, nothing}}
```

Fortunately, `Unitful` values allows the promotion using `float` function, we can fix the code without adding tedious constructor for `Unitful`.

**Comment by juliohm** [comment]
Very nice @ehgus , thanks for sharing the issue. Feel free to submit a PR with a proposal fix and we can review right away.
