### ISSUE TITLE
`atol` is not defined for `Unitful`

### ISSUE THREAD

**Issue by ehgus** [JuliaGeometry/Meshes.jl#603]
`Base.in` does not support `Unitful` because `atol` is not defined for the type.
My suggestion is to return `zero(T)` for an arbitrary type.
May I submit a PR?

**Comment by juliohm** [comment]
What about returning the atol of the underlying number without units? We can use `ustrip` to remove the unit and decide the tolerance. We will have to add Unitful.jl as a dependency anyways at some point to handle these issues, so I think this is a good opportunity to add it explicitly here.
