### ISSUE TITLE
RectilinearGrid incorrect methods with unsorted coordinates

### ISSUE THREAD

**Issue by ErickChacon** [JuliaGeometry/Meshes.jl#605]
Currently `RectilinearGrid` assumes coordinates are sorted. The methods seem to not work when the user provides unsorted coordinates. We can check if the coordinates are sorted or simply sort it when constructing the RectilinearGrid. See below an example using the centroid method.

```julia
using Random
using Meshes
using CairoMakie

Random.seed!(7)
x = rand(4)
y = rand(5)

# unsorted coordinates
gr = Meshes.RectilinearGrid(x, y)
fig = viz(gr, showfacets = true)
viz!(centroid.(gr), color = :red)
```
![rg-unsorted](https://github.com/JuliaGeometry/Meshes.jl/assets/7862458/aa0780e2-75fb-4893-90ad-5ec4b9d5f0e0)

```julia
# sorted coordinates
gr = Meshes.RectilinearGrid(sort(x), sort(y))
fig = viz(gr, showfacets = true)
viz!(centroid.(gr), color = :red)
```
![rg-sorted](https://github.com/JuliaGeometry/Meshes.jl/assets/7862458/cd5dbb24-fb38-4fd0-aa51-abb4fe16b80a)

**Comment by juliohm** [comment]
This is probably a documentation issue? I think it is reasonable to assume that coordinates are sorted by the user before calling the constructor. That is how rectilinear grids are usually constructed elsewhere.

Should we submit a PR to improve the docstring?

**Comment by ErickChacon** [comment]
Agree, we just need to make it clear in the documentation. I will do the PR.
