### ISSUE TITLE
Reintroduce simple syntax to sample elements from the domain

### ISSUE THREAD

**Issue by ErickChacon** [JuliaGeometry/Meshes.jl#607]
The current syntax to get random elements from a Domain requires to define `UniformSampling`.

```julia
g = CartesianGrid(10,10)
sample(g, UniformSampling(10))
```

However the syntax `sample(g, 5)` is easier for end-users that do not mind about other sampling methods. It would be great to it back into the package with proper type annotation.

**Comment by Jay-sanjay** [comment]
@ErickChacon   @juliohm  Sir I see that traces of UniformSampling are only present here https://github.com/JuliaGeometry/Meshes.jl/blob/0f5a98f488383ff2130a18f3601ca92988e9ca67/src/sampling/uniform.jl#L13

The possible fix I see is to call this function in the sample function.
But, I am not getting I should call it for which sample function , as I am getting several hits in src for `sample` in the repo
