### ISSUE TITLE
`one(T<:Unitful.Quantity)` always return unity without unit, which may cause error

### ISSUE THREAD

**Issue by ehgus** [JuliaGeometry/Meshes.jl#608]
`Meshes` uses `one` frequently  when requiring unity value with given type.
Actually, this may cause error because `zero(T)` returns zero preserving the unit, but `one` is not.

For example, `CartesianGrid{T}(dims)` utilizes `zero` and `one` when initialize origin and spacing internally, thus the unit is mismatched:
https://github.com/JuliaGeometry/Meshes.jl/blob/0f5a98f488383ff2130a18f3601ca92988e9ca67/src/mesh/cartesiangrid.jl#L98-L103

Replacing the initilization to `T(1)` and `T(0)` will fix the problem.

-----
For your information, the behavior of the `one` is intentional because Julia has desgined `one` to return multiplicative identity: https://github.com/PainterQubits/Unitful.jl/issues/685

**Comment by juliohm** [comment]
Thank you for reporting the issue @ehgus. Feel free to submit a PR fixing it, happy to review.
