### ISSUE TITLE
Vertices coloring not working

### ISSUE THREAD

**Issue by remann2** [JuliaGeometry/Meshes.jl#616]
```
m = CartisianGrid(10, 10)
viz(m, color=1:nvertices(m))
 ```

will return DimensionMismatch error, is this a bug?

**Comment by remann2** [comment]
My bad, it seems that only subtypes of Mesh work this way while Grid doesn't? 

> The option color can be a single scalar or a vector of scalars. For [Mesh](https://juliageometry.github.io/MeshesDocs/stable/domains/meshes.html#Meshes.Mesh) subtypes, the length of the vector of colors determines if the colors should be assigned to vertices or to elements. (https://juliageometry.github.io/MeshesDocs/stable/visualization.html)

**Comment by juliohm** [comment]
If it is not working, it is a bug. We have Grid <: Mesh.

Would you like to submit a PR fixing the issue? The plotting recipe is in
the ext folder.

Em ter., 10 de out. de 2023 06:20, Steve ***@***.***>
escreveu:

**Comment by remann2** [comment]
Thanks, I will try.

**Comment by juliohm** [comment]
The easiest way is to simply convert(SimpleMesh, grid) and call the viz
function again.

Em ter., 10 de out. de 2023 06:33, Steve ***@***.***>
escreveu:

**Comment by remann2** [comment]
Hi, I've create a pr plz have a look.
