### ISSUE TITLE
translation messes up Plane

### ISSUE THREAD

**Issue by cserteGT3** [JuliaGeometry/Meshes.jl#622]
The transformation is applied to `u` and `v` of a plane as well, see the following example:

```julia
julia> p1 = Plane((10, 0, 10), (0, 0, 1))
Plane{3,Float64}
├─ p: Point(10.0, 0.0, 10.0)
├─ u: Vec(1.0, -0.0, -0.0)
└─ v: Vec(-0.0, 1.0, -0.0)

julia> ft = Translate(100, 35, 70)
Translate transform
└─ offsets = (100, 35, 70)

julia> p2 = ft(p1)
Plane{3,Float64}
├─ p: Point(110.0, 35.0, 80.0)
├─ u: Vec(101.0, 35.0, 70.0)
└─ v: Vec(100.0, 36.0, 70.0)
```

I realized this, when I was transforming disks, and looked pretty weird. Turns out, the underlying plane is modified like in the example above.

I assume that this should not behave like this.

**Comment by juliohm** [comment]
That looks like a bug indeed. Can you please check all geometries that have
Vec fields to see if the bug is present? If this is specific to Plane, we
can specialize the Translate transform for it.

Em ter., 17 de out. de 2023 07:52, cserteGT3 ***@***.***>
escreveu:

**Comment by cserteGT3** [comment]
Other than `Plane` (and any geometry that uses that, see a disk for example below), `Ray` and `Torus` have `Vec` fields and all are affected:

```julia
julia> p1 = Plane((10, 0, 10), (0, 0, 1))
Plane{3,Float64}
├─ p: Point(10.0, 0.0, 10.0)
├─ u: Vec(1.0, -0.0, -0.0)
└─ v: Vec(-0.0, 1.0, -0.0)

julia> ft = Translate(100, 35, 70)
Translate transform
└─ offsets = (100, 35, 70)

julia> ft(p1)
Plane{3,Float64}
├─ p: Point(110.0, 35.0, 80.0)
├─ u: Vec(101.0, 35.0, 70.0)
└─ v: Vec(100.0, 36.0, 70.0)

julia> d1 = Disk(p1, 15.0)
Disk{3,Float64}
├─ plane: Plane(p: (10.0, 0.0, 10.0), u: (1.0, -0.0, -0.0), v: (-0.0, 1.0, -0.0))
└─ radius: 15.0

julia> ft(d1)
Disk{3,Float64}
├─ plane: Plane(p: (110.0, 35.0, 80.0), u: (101.0, 35.0, 70.0), v: (100.0, 36.0, 70.0))
└─ radius: 15.0

julia> r1 = Ray((0,0,0), (1,0,0))
Ray{3,Float64}
├─ p: Point(0.0, 0.0, 0.0)
└─ v: Vec(1.0, 0.0, 0.0)

julia> ft(r1)
Ray{3,Float64}
├─ p: Point(100.0, 35.0, 70.0)
└─ v: Vec(101.0, 35.0, 70.0)

julia> t1 = Torus((0.,0.,0.), (1.,0.,0.), (0.,1.,0.), 0.2)
Torus{3,Float64}
├─ center: Point(0.5, 0.5, 0.0)
├─ normal: Vec(0.0, 0.0, 1.0)
├─ major: 0.7071067811865476
└─ minor: 0.2

julia> ft(t1)
Torus{3,Float64}
├─ center: Point(100.5, 35.5, 70.0)
├─ normal: Vec(100.0, 35.0, 71.0)
├─ major: 0.7071067811865476
└─ minor: 0.2

```

**Comment by juliohm** [comment]
We forward the Translate transform to the field of structs recursively.
Perhaps we should skip the Vec field always, except in a few cases? Our
current Point struct holds a Vec but that will change soon. It is the only
case where we want to apply the transform to the Vec.

Em ter., 17 de out. de 2023 08:11, cserteGT3 ***@***.***>
escreveu:

**Comment by juliohm** [comment]
Perhaps the easiest fix is to specialize the Translate transform with the
explicit list of geometries affected.

Em ter., 17 de out. de 2023 08:17, Júlio Hoffimann <
***@***.***> escreveu:
