### ISSUE TITLE
Docs for old releases

### ISSUE THREAD

**Issue by tomerarnon** [JuliaGeometry/Meshes.jl#626]
The documentation online only lists the stable and latest releases. It would be useful for users if past versions were maintained as well, to make it easier to find valid documentation when Meshes is pinned in a project, or to compare versions when upgrading.

Context: I just upgraded a project from using Meshes v0.32.3 to the latest v0.35.13 and noticed some changes in behavior that broke my tests. Turning to the online docs to see if I could get some insight on what changed, I realized I couldn't do that.

**Comment by juliohm** [comment]
We tried to keep all versions at some point, but the Makie figures were too heavy. We moved the documentation to an external repo, and are maintaining just the stable and latest to avoid similar explosions of gh-pages size.

Also, the project is still evolving and we don't intend to support these old releases. If you have trouble with the updates, feel free to contact us on Zulip, we are happy to help with the migration.
