### ISSUE TITLE
intersects Function Returns True Even When No Intersection Exists

### ISSUE THREAD

**Issue by Gia67gianni** [JuliaGeometry/Meshes.jl#635]
I attempted to assess the intersection of two boundaries (Hexahedron) (there's no 'intersects' available for Hexahedron), specifically, two SimpleMeshes of Quadrangles. The 'intersects' function returns 'true' even when there's no actual intersection in this scenario.
```
julia> h = Hexahedron((0, 0, 0), (4, 0, 0), (4, 4, 0), (0, 4, 0), (1, 1, 2), (3, 1, 2), (3, 3, 2), (1, 3, 2))
julia> h1 =Hexahedron( (1, 1, 1), (3, 1, 1), (3, 3, 1),  (1, 3, 1), (1.5, 1.5, 1.5), (2.5, 1.5, 1.5), (2.5, 2.5, 1.5), (1.5, 2.5, 1.5)) |> Translate(2.6, 0.0, 0.0)

julia> h_bound = boundary(h)
julia> h1_bound = boundary(h1)

julia> intersects(h_bound, h1_bound)
```
![immagine_2023-11-22_085523913](https://github.com/JuliaGeometry/Meshes.jl/assets/115149419/6adc5b63-15dd-49d1-8987-62c75fd5cc44)

**Comment by juliohm** [comment]
I reduced the MWE to the intersection of two quadrangles, which should return false:

![image](https://github.com/JuliaGeometry/Meshes.jl/assets/3345261/3c599157-1200-45f7-aaae-6fdde2dc5252)

```julia
julia> q1 = Quadrangle((4.0, 4.0, 0.0), (3.0, 3.0, 2.0), (3.0, 1.0, 2.0), (4.0, 0.0, 0.0))
Quadrangle{3,Float64}
├─ Point(4.0, 4.0, 0.0)
├─ Point(3.0, 3.0, 2.0)
├─ Point(3.0, 1.0, 2.0)
└─ Point(4.0, 0.0, 0.0)

julia> q2 = Quadrangle((3.6, 3.0, 1.0), (5.6, 3.0, 1.0), (5.6, 1.0, 1.0), (3.6, 1.0, 1.0))
Quadrangle{3,Float64}
├─ Point(3.6, 3.0, 1.0)
├─ Point(5.6, 3.0, 1.0)
├─ Point(5.6, 1.0, 1.0)
└─ Point(3.6, 1.0, 1.0)

julia> intersects(q1, q2)
true
```

This specific [method](https://github.com/JuliaGeometry/Meshes.jl/blob/30ec2ce96f39d54abc9f7ed1ef0637754ae04cf6/src/predicates/intersects.jl#L50-L109) implements the GJK algorithm, which is beautifully explained in this [video](https://youtu.be/ajv46BSqcK4?si=YNgc6K8XZb3m5vvI).

Our current implementation was extensively tested with 2D geometries embedded in 2D space. In your case, the 2D geometries are embedded in 3D space. Do you have the time to take a deeper look into the algorithm to see if some expression is assuming 2D coordinates?

Feel free to reach out in Zulip if you have questions. I can try to take a look at it next week.

**Comment by Gia67gianni** [comment]
Thank you very much, I will have a look at the algorithm as soon as I can.
