### ISSUE TITLE
`intersects` function returns false when an intersection exists

### ISSUE THREAD

**Issue by MachSilva** [JuliaGeometry/Meshes.jl#639]
Example code in the Julia REPL:
```julia
julia> ray = Ray(Point(0.41169768366272996, 0.8990554132423699), Vec(0.47249211625247445, 0.2523149692768657))
Ray{2,Float64}
├─ p: Point(0.41169768366272996, 0.8990554132423699)
└─ v: Vec(0.47249211625247445, 0.2523149692768657)

julia> box = Box(Point(1.0, 1.0), Point(5.0, 2.0))
Box{2,Float64}
├─ min: Point(1.0, 1.0)
└─ max: Point(5.0, 2.0)

julia> intersects(ray, box)
false

julia> ray ∩ box
Segment{2,Float64}
├─ Point(1.0, 1.2132140537070295)
└─ Point(2.473357517657818, 2.0)
```

This issue is similar to #635, but it is between a ray and an axis-aligned bounding box.

**Comment by juliohm** [comment]
This one should be easy to fix. Can you help adding a method to `intersects` that simply calls the `cap` operator and checks for `nothing`? We have examples with other geometries.

In this case we have an actual intersection algorithm between ray and box that we can use to check if they intersect.

Mind submitting a PR @MachSilva ?

**Comment by MachSilva** [comment]
Sorry for the late reply. I was just about to say that I'll give a try on my free time to submit a PR, but it is already done. Thanks for the solution.

Nevertheless, while searching for the cause of this bug, I noted that the false negative was due to `boundingbox(::Ray)` returning an empty box centered at the ray origin:

```julia
julia> boundingbox(ray)
Box{2,Float64}
├─ min: Point(0.41169768366272996, 0.8990554132423699)
└─ max: Point(0.41169768366272996, 0.8990554132423699)
```

I don't know if this is an intended behavior, but I think a return value of a box with `min = Point(0.411... 0.899...)` and `max = Point(Inf, Inf)` for this ray would make more sense, since the ray could be seen as a primitive with an infinite size just as a line.

**Comment by juliohm** [comment]
Agree. Mind submitting a PR fixing the boundingbox of the Ray as suggested?

**Comment by MachSilva** [comment]
I'll look into it (but no promises, 'cause I'm new to Julia language/ecosystem and to the open source community).
