### ISSUE TITLE
StackOverflowError on segments Visualization

### ISSUE THREAD

**Issue by Yaraslaut** [JuliaGeometry/Meshes.jl#643]
Following code 
```
ent = Vector{Meshes.Point2}()
push!(ent, Meshes.Point(0,0))
push!(ent, Meshes.Point(1,0))
push!(ent, Meshes.Point(0.5,sqrt(3)/2.0))
seg = Vector{Meshes.Segment}()
push!(seg, Meshes.Segment(ent[1], ent[2]))
push!(seg, Meshes.Segment(ent[2], ent[3]))
push!(seg, Meshes.Segment(ent[3], ent[1]))
viz(seg)
```

produce StackOverflowError with trace: 

```
ERROR: LoadError: StackOverflowError:
Stacktrace:
 [1] Array
   @ ./boot.jl:477 [inlined]
 [2] Array
   @ ./boot.jl:486 [inlined]
 [3] Array
   @ ./boot.jl:494 [inlined]
 [4] _collect_indices
   @ ./array.jl:725 [inlined]
 [5] collect
   @ ./array.jl:709 [inlined]
 [6] GeometrySet(geoms::Vector{Segment}) (repeats 79982 times)
   @ Meshes ~/.julia/packages/Meshes/1sXKx/src/sets.jl:23

```

**Comment by juliohm** [comment]
Thank you @Yaraslaut for reporting the issue.

The `viz` recipe assumes that vectors of geometries have well-known embedding dimension and coordinate type. Every geometry is parameterized as `Geometry{Dim,T}`. You can see that `Point2 == Point{2,Float64}` is just an alias.

When you create the container with `seg = Vector{Meshes.Segment}()`, you are not specifying the dimension nor coordinate type of the segments, and therefore we are unable to find the appropriate Makie recipe via multiple dispatch. Maybe we should loosen this restriction and allow for more dynamic recipes.

A quick fix is to use `seg = Vector{Meshes.Segment{2,Float64}}()` instead. You can see that the plot shows up correctly:

![image](https://github.com/JuliaGeometry/Meshes.jl/assets/3345261/6b45dc86-9045-40a9-b88a-68c3cf60d6fe)

Feel free to look into our recipes and propose changes to accommodate these use cases. We will try to take a look when we find some time.

**Comment by juliohm** [comment]
This is now fixed in our `GeometrySet` constructor. This is a Julia trick to infer types properly when the collection doesn't have a concrete eltype: https://github.com/JuliaGeometry/Meshes.jl/commit/ea94c4abf43b2678741293336202a93a17c6f8d6

Now the `viz` command should work even when the collection of geometries doesn't have a well-defined dimension and coordinate type. Thank you for reporting.

Please keep these issues coming 💯

**Comment by Yaraslaut** [comment]
> This is now fixed in our `GeometrySet` constructor. This is a Julia trick to infer types properly when the collection doesn't have a concrete eltype: https://github.com/JuliaGeometry/Meshes.jl/commit/ea94c4abf43b2678741293336202a93a17c6f8d6
> 
> 
> 
> Now the `viz` command should work even when the collection of geometries doesn't have a well-defined dimension and coordinate type. Thank you for reporting.
> 
> 
> 
> Please keep these issues coming 💯 

Thanks for fixing this issue :)
