### ISSUE TITLE
Stackoverflow with intersection of Ropes

### ISSUE THREAD

**Issue by tomerarnon** [JuliaGeometry/Meshes.jl#644]
See the following example: 

```julia_repl
julia> r = Rope(Point(0, 0), Point(1, 1));

julia> intersection(r, r)
ERROR: StackOverflowError:
Stacktrace:
 [1] intersection(f::Function, g₁::Rope{2, Float64, Vector{Point2}}, g₂::Rope{2, Float64, Vector{Point2}}) (repeats 2 times)
   @ Meshes ~/.julia/packages/Meshes/ML1K9/src/intersections.jl:100
```

`intersect` behaves the same way.

**Comment by juliohm** [comment]
Thank you for reporting the issue @tomerarnon.

It is fixed on the master branch: https://github.com/JuliaGeometry/Meshes.jl/commit/7d0a4bec61cfaad13534dfcae3aa0f3a70e03ad4

Please keep them coming 💯
