### ISSUE TITLE
Corner cases in FIST algorithm

### ISSUE THREAD

**Issue by juliohm** [JuliaGeometry/Meshes.jl#65]
The FIST implementation we have is reasonably robust, but it is still failing with some difficult polygonal areas. In our test suite we have a bunch of polygonal area examples in the `data` directory that are loaded for testing. Tests are passing for most polygonal areas in the family `poly1...5.line`, for example:

# poly1.line
![image](https://user-images.githubusercontent.com/3345261/110510122-a3db7e80-80e1-11eb-8614-d0c7a88f01d7.png)
![image](https://user-images.githubusercontent.com/3345261/110510206-b950a880-80e1-11eb-8bed-9b684e7cf595.png)

# poly2.line
![image](https://user-images.githubusercontent.com/3345261/110510299-d38a8680-80e1-11eb-882c-9a123e2d7d16.png)
![image](https://user-images.githubusercontent.com/3345261/110510369-e309cf80-80e1-11eb-9d40-5c8851a2b32a.png)

# poly3.line
But some cases like `poly3.line` are not passing the visual test:

![image](https://user-images.githubusercontent.com/3345261/110510737-43990c80-80e2-11eb-99b5-a2b18310df44.png)
![image](https://user-images.githubusercontent.com/3345261/110510767-4ac01a80-80e2-11eb-8829-e337b86cb15a.png)

Notice how some edges cross. That shouldn't be the case.

With the latest changes, we can also handle polygonal areas with holes in the `holes1...5.line` family, for example:

# hole2.line
![image](https://user-images.githubusercontent.com/3345261/110511117-ac808480-80e2-11eb-8f7d-80fde2a39def.png)
![image](https://user-images.githubusercontent.com/3345261/110511155-b4d8bf80-80e2-11eb-9228-793b37a35d30.png)

# hole1.line
But some cases like `hole1.line` have crossing edges too:

![image](https://user-images.githubusercontent.com/3345261/110511490-0a14d100-80e3-11eb-86db-5b2b385968a1.png)
![image](https://user-images.githubusercontent.com/3345261/110511540-139e3900-80e3-11eb-96a6-3f8aae82bfe4.png)

Notice how the left inner hole is crossed by edges.

Finally we have polygonal areas in the `smooth1...5.line` family that are working fine:

# smooth2.line
![image](https://user-images.githubusercontent.com/3345261/110511834-6aa40e00-80e3-11eb-93dd-14b222b3aa02.png)
![image](https://user-images.githubusercontent.com/3345261/110511868-74c60c80-80e3-11eb-9d29-995385144839.png)

# smooth1.line
But similarly, some cases fail with crossing edges:

![image](https://user-images.githubusercontent.com/3345261/110512009-97582580-80e3-11eb-9988-23d36631dd22.png)
![image](https://user-images.githubusercontent.com/3345261/110512051-a17a2400-80e3-11eb-8c0b-3694a0a37c69.png)

It would be nice to dive in debug mode to figure out what is happening. Both `PolyArea` and `UnstructuredMesh` can be plotted directly with our current plot recipes so that helps too in the debugging process.

If someone can read the FIST paper by Held and then read our implementation, which basically follows the exact same notation, that would be great. I think I've implemented all the ingredients except for one or two corner cases they discuss, which may be related to the issues we are seeing.

If someone wants to dive in, I can help explaining the current implementation in a video chat for example.

**Comment by serenity4** [comment]
I can give it a shot. I read a bit about the FIST paper some time ago, but some explanations would be very welcome. We can continue the discussion on Zulip if you want.

**Comment by juliohm** [comment]
That would be great @serenity4. Feel free to reach out on Zulip, and we can even setup a video chat there. I'd be happy to walk through the current implementation to explain what is happening.
