### ISSUE TITLE
Incorrect colors when values have NaN

### ISSUE THREAD

**Issue by ErickChacon** [JuliaGeometry/Meshes.jl#657]
The following code creates a graph with the same color for all geometries under the presence of NaN.

```julia
g = CartesianGrid(10,10)
vals = rand(100)
vals[1] = NaN
viz(g, color = vals)
```

Should it be fixed by also considering the presence of NaN in the code to create color? Basically the following line:

https://github.com/JuliaGeometry/Meshes.jl/blob/2cdcfb7375cc03d44c2897ad0e7fb0e359f467f5/ext/colors.jl#L33

**Comment by juliohm** [comment]
We only support `missing` as missing value. Try `Replace(NaN => missing)` and the visualization will work.

**Comment by juliohm** [comment]
Maybe we need to add support for this as well, in case the file format doesn't support special missing symbols.
