### ISSUE TITLE
While loop in FIST algorithm fails to terminate

### ISSUE THREAD

**Issue by sean-n0** [JuliaGeometry/Meshes.jl#675]
With certain input data (large complex polygons automatically generated by a geographical information system) I found that the FIST algorithm can get stuck in the while loop that starts at line 56 in the fist.jl file.

Because of the randomness introduced by the shuffle option, this doesn't happen every time a nasty polygon is input, but for the worst polygons it was occurring more than 1 occasion in 10.

I don't know the underlying cause of this bug, but it can be cured as follows:
1) Introduce a iterations counter into the while loop
2) if the iteration counter reaches some high number (I used 10000 - maybe some function of the number of vertices would be better) then it means the triangulation is failing, so it breaks out of the  while loop.
3) If the while loop completes because the iteration count has reached the limit then any outputs are discarded and the whole FIST algorithm is restarted.
4) Restarting the algorithm means running shuffle again, so most of the time the FIST algorithm will succeed the second time.
5) If it fails a second time, FIST can be tried a third time (with further re-shuffling) and so on. My version of the code (which I can't easily post) allows 100 attempts before it gives up and generates an error message. When tried on real-world data I found that in no case were more than 2 retries needed.

If needed I should be able to provide some examples of troublesome polygons for testing, but there may be a delay doing this as the source of the data will need to be obfuscated.

**Comment by juliohm** [comment]
Thank you @sean-n0 for reporting the issue. We saw it sometimes in our test suite, but couldn't produce a MWE with a small polygon and fixed seed yet. If you can find a problematic case with a fixed seed, we can try to reproduce and nail down the problem.

**Comment by sean-n0** [comment]
Hi Julio,

I attach an input file containing two polygons. 

[Obfus_inputs.xlsx](https://github.com/JuliaGeometry/Meshes.jl/files/13793782/Obfus_inputs.xlsx)

This isn’t exactly the original data (it has been obfuscated by adding offsets) but it triggers the same bugs. Both polygons were originally “real world” outputs from a geographical information system. Neither is particularly long (others in the larger original data set are *much* longer).

There are two polygons in the file:

i)   The polygon in row 3 crashes FIST because it contains large X and Y values. When normalised down to numbers between 0 and 1 it works fine.

ii)   Even after normalising the inputs the polygon in row 4 consistently crashes FIST if you put Random.seed!(1234) before the call to discretize

It’s not exactly an MWE, but I can probably extract the code I’m using to test workarounds. This will also reproduce the bug.

**Comment by juliohm** [comment]
Hi Sean,

I cannot find the attachment on GitHub. Can you please share a link to a cloud drive? GitHub removes attachments from emails I guess.

**Comment by sean-n0** [comment]
I've edited my previous comment and added to that comment a link to the the Excel file that holds the example polygons.

**Comment by eliascarv** [comment]
We reduce the issue of the first polygon to this intersection of segments:
```
julia> s1 = Segment(Point(1.1794105009e7, 1.7289766778e7), Point(1.1794424965e7, 1.7289626797e7))

julia> s2 = Segment(Point(1.1793965029e7, 1.7289586803e7), Point(1.1794424965e7, 1.7289626797e7))

julia> intersection(s1, s2)
Intersection{Point2}(Crossing, Point(1.1794424964998351e7, 1.728962679700072e7))
```
Plotting the segments we can see that they are not crossing:

![image](https://github.com/JuliaGeometry/Meshes.jl/assets/73039601/8215dfbd-cdff-4343-b081-77f35b20403d)

Unfortunately, I was unable to reproduce the issue with the second polygon. Even using `Random.seed!(1234)`, after normalizing the coordinates, the FIRST algorithm does not break.

@sean-n0, could you run the `versioninfo()` command in the REPL to get information about your environment? This information is important for reproducing the bug.

**Comment by juliohm** [comment]
@sean-n0 we will standardize the coordinates as a pre-procesing step before discretization. This will avoid similar problems in the future.

Regarding the second issue, we were unable to reproduce as @eliascarv described above. Mind double checking it?

**Comment by juliohm** [comment]
@dorn-gerhard the intersection between two segments that you wrote a while ago is sensitive to large coordinate values. Do you have a suggestion of improvement? I am copying the MWE here:

```julia
julia> s1 = Segment(Point(1.1794105009e7, 1.7289766778e7), Point(1.1794424965e7, 1.7289626797e7))

julia> s2 = Segment(Point(1.1793965029e7, 1.7289586803e7), Point(1.1794424965e7, 1.7289626797e7))

julia> intersection(s1, s2)
Intersection{Point2}(Crossing, Point(1.1794424964998351e7, 1.728962679700072e7))
```

**Comment by dorn-gerhard** [comment]
The problem is, that one has to substract the segment vertices at one point.
Working with large numbers of the order 10^7 leads to absolute errors in the range of 10^-9 - 10^-10 which is above the per default used absolute tolerance of type Float64: `tol(Float64) = 10^-10`
You could either increase the absolute tolerance (tol) switch to relative tolerance or normalize the vertices:
``` julia
julia> s1 = Segment(Point(1.1794105009e4, 1.7289766778e4), Point(1.1794424965e4, 1.7289626797e4))
julia> s2 = Segment(Point(1.1793965029e4, 1.7289586803e4), Point(1.1794424965e4, 1.7289626797e4))
julia> intersection(s1, s2)
Intersection{Point2}(CornerTouching, Point(11794.424965, 17289.626797))
```

**Comment by juliohm** [comment]
We will normalize the coordinates in a preprocessing step for end users
before we run FIST. But I was wondering if there was a solution for the
intersection call that did not involve normalization. Thanks for clarifying
it.

Em seg., 29 de jan. de 2024 18:18, Gerhard Dorn ***@***.***>
escreveu:

**Comment by juliohm** [comment]
Regarding the second polygon, we identified the issue in the intersection of two segments: #719
