### ISSUE TITLE
FIST algorithm is sensitive to the scale of the x and y co-ordinates inputs

### ISSUE THREAD

**Issue by sean-n0** [JuliaGeometry/Meshes.jl#676]
I found that the FIST algorithm can fail when input polygons have large numerical values (e.g. x or y co-ordinates in millions). I was able to work around this by scaling down all of the input co-ordinates so that all x and y values were between 0 and 1, and then scaling the outputs of the FIST algorithm back to the original size. 

I can provide some input data that triggers this issue, but there may be a delay providing this as the data would need to be obfuscated.

**Comment by juliohm** [comment]
I wonder if this is specific to FIST or a more general issue related to all discretization methods available. If you can share a MWE, we can try to fix it next year.

**Comment by juliohm** [comment]
Fixed on master.
