### ISSUE TITLE
Idea for a SurfaceTrajectory

### ISSUE THREAD

**Issue by mikeingold** [JuliaGeometry/Meshes.jl#677]
I've been thinking about trying to implement a data structure representing a path followed along a surface in space, not unlike the red line illustrated here:

![image](https://github.com/JuliaGeometry/Meshes.jl/assets/4054970/ab121573-051b-4236-9117-556547345490)

A simple `Rope` object could be constructed containing a vector of 3D `Point`s to represent the path itself, but I'd like to retain information about the spatial orientation of the path, e.g. the surface normal at any point along the path. In this version the path is discretized into segments, so I would think this would require something like

```julia
struct SurfaceTrajectory{T} <: Domain{3,T}
  path::Vector{Point{3,T}}   # length n
  normals::Vec{3,T}          # length (n-1)
end
```

Anybody have any better/other ideas before I dive into this?

**Comment by juliohm** [comment]
Perhaps you need a GeoTable with feature columns besides the path of points?

Can you please confirm you read the GDSJL book in the docs?

Em qua., 3 de jan. de 2024 22:57, Michael Ingold ***@***.***>
escreveu:

**Comment by mikeingold** [comment]
I hadn’t seen the book before but was able to read through it today. In that `struct`-based suggestion I gave I was mirroring the current `Meshes.CylindricalTrajectory` implementation, but I can see now why you’d suggest a GeoTable.

My personal interest in this proposed `SurfaceTrajectory` type would be to facilitate calculating path integrals along a surface where the surface orientation matters. This sort of arrangement crops up a lot in electromagnetic and radiometric problems. I could probably slap something together for personal use pretty quick, but it’s a generic enough feature that it seemed like a reasonable enough thing to propose for general usage.

That being the case, if I were to put together a demo/PR of this feature, what architecture would you prefer or expect? Fundamentally, I think the structure can be described by a `Chain{Dim,T}`, where each child Segment of the chain is associated with a `Vec{Dim,T}`.

Alternatively, a GeoTable with a column of Points and another column of Vecs could work, though it’s not exactly a 1:1 relationship since the new vector is sort of effective beyond that point at not simply at that point, making the final Vec redundant. A GeoTable with a Segment column and a Vec column might make more conceptual sense, but leads to even more redundant data.

**Comment by juliohm** [comment]
Can you elaborate on the function call you have in mind to perform the integral along the surface trajectory? Perhaps we can brainstorm this in Zulip instead of a GitHub issue. The design feels very open still.

**Comment by mikeingold** [comment]
Wow, I didn't realize there was such an active `#meshes.jl` channel on the Zulip.

I'm working on putting together a reference design in a new package, focused on implementing some canonical line integral forms by leveraging Meshes under the hood. The built-in parameterizations, e.g. `(::Segment{Dim,T})(t) -> ::Point{Dim,T}`, make it very easy to implement integration routines over arbitrary paths.

**Comment by juliohm** [comment]
That is awesome! Looking forward to learning more about it. Let's continue the discussion over Zulip then, and come back here if we discover a missing feature that is general enough.
