### ISSUE TITLE
Clamping points to boxes and/or bounding boxes

### ISSUE THREAD

**Issue by markmbaum** [JuliaGeometry/Meshes.jl#698]
As part of a simulation project I'm working with points, grids, and boxes in two dimensions. At different points I need to clamp point locations that lie outside of a box by moving them to the box boundary. This is straightforward with the `clamp` and `clamp!` functions from `Base.Math`. You just have to clamp both dimensions of the point, or however many dimensions you have.

I see the clipping functionality but no clamping. New methods could look something like

```julia
clamp(Point{Dim,T}, Box{Dim,T}) where {Dim,T}

clamp(PointSet{Dim,T}, Box{Dim,T}} where {Dim,T}
```

Happy to contribute if it makes sense.

**Comment by juliohm** [comment]
That is an interesting idea @markmbaum, thanks for sharing. Feel free to submit a PR for review.

**Comment by markmbaum** [comment]
Planning to do this, just been busy (feel free to assign me)
