### ISSUE TITLE
allowing `center(::Segment{Dim,T})` when `T` is not `<:Real` such as a `Unitful.Quantity`

### ISSUE THREAD

**Issue by kylebeggs** [JuliaGeometry/Meshes.jl#702]
Opening a new issue although discussed in #692 so we can brainstorm a solution before making a PR. The immediate issue is that this implementation does not work when the data type of `Segment` is not a `Real`, as then the check to make sure the unitless parameter `t` is between 0 and 1 errors.

Here is the current implementation:
```julia
center(s::Segment{Dim,T}) where {Dim,T} = s(T(0.5))

function (s::Segment)(t)
  if t < 0 || t > 1
    throw(DomainError(t, "s(t) is not defined for t outside [0, 1]."))
  end
  a, b = s.vertices
  a + t * (b - a)
end
```

A few options:
- convert 0 and 1 in the check for `t` for match the data type of `Segment`. This is what I did initially, but I don't think this makes sense because `t` should always be a unitless real number, and then now you are constrained to this only working for data types which have comparison operators defined.
- A solution that works for `Unitful.Quantity`s would be to just convert 0.5 to the underlying data type of the `Unitful.Quantity` which would give you the same type as the `Points` of `Segment` which is the goal. This was the last state of #692 but also is not ideal because then you'd need to define helper methods to "get the precision".
- Perhaps just calculate the mean directly without using `t` and generic implementation for `Segment`?
```julia
function center(s::Segment)
  a, b = coordinates.(s.vertices)
  return (a + b) ./ 2
end
```

**Comment by juliohm** [comment]
The best approach is the third one where we redefine the center in terms of a and b directly, and divide by the integer 2 instead of multiply by 0.5.

**Comment by juliohm** [comment]
Thanks @kylebeggs , fixed on master.
