### ISSUE TITLE
Intersection of segments in single precision

### ISSUE THREAD

**Issue by juliohm** [JuliaGeometry/Meshes.jl#71]
Found an issue with the last branch of the intersection algorithm:

```julia
s1 = Segment(Point(0.94495744f0, 0.53224397f0), Point(0.94798386f0, 0.5344541f0))
s2 = Segment(Point(0.94798386f0, 0.5344541f0), Point(0.9472896f0, 0.5340202f0))

s1 ∩ s2
Segment{2,Float32}
  └─Point(0.9472896f0, 0.5340202f0)
  └─Point(0.94798386f0, 0.5344541f0)
```
![image](https://user-images.githubusercontent.com/3345261/110969029-fb265c80-8336-11eb-9e16-9fe9aa78c0c1.png)

In this plot `s1` is the black segment and `s2` is the red segment. The intersection algorithm reaches the `CASE (III)` correctly, and then tries to decide whether or not these two segments are co-linear:

```julia
elseif !determinatex && !determinatey # CASE (III)
    if !isapprox((x2 - x1) × (y2 - y1), zero(T), atol=atol(T))
      # configuration (3)
      CornerTouchingSegments(intersectpoint(s1, s2))
    else
      # configuration (3), (4) or (5)
      intersectcolinear(s1, s2)
    end
  end
```

I am using the cross product to check for co-linearity, but the tolerance seems to be too tight. The `atol(T)` should return a reasonable tolerance for distances, not areas or volumes, I think that is causing the issue. Based on the plot, we would like to return `configuration (3)` because the segments aren't overlapping and aren't co-linear.

How should we set the tolerance in this case? Or should we use a different condition to check for co-linearity that doesn't use the cross product?

**Comment by juliohm** [comment]
I will try to use the length of the orthogonal component of the red segment with respect to the black segment as the condition. That way the `atol(T)` will apply to a distance as opposed to an area. Let me know if you have other ideas.

**Comment by serenity4** [comment]
What about simply using `atol(T)^2`? This should be correct for areas in theory, right?
