### ISSUE TITLE
NaN and Inf points inside finite polygon

### ISSUE THREAD

**Issue by markmbaum** [JuliaGeometry/Meshes.jl#714]
I ran into something unexpected when checking that points are contained by polygons, in this case, instances of `PolyArea{2, Float32}` specifically. With points that have infinite and nan coordinates, I see `point ∈ poly` returning `true`.

For example, this polygon
```julia
poly = PolyArea([
    (0.0f0, 0.0f0),
    (0.0f0, 1.0f0),
    (5.0f-1, 1.0f0),
    (5.0f-1, 5.0f-1),
    (1.0f0, 5.0f-1),
    (1.0f0, 0.0f0),
])
```
looks like this
<img width="591" alt="Screenshot 2024-01-27 at 10 50 42 AM" src="https://github.com/JuliaGeometry/Meshes.jl/assets/18745581/fa0bab2b-f907-4083-adad-75332af11891">

The following return `true`, unexpectedly
```julia
point = Point(Inf32, Inf32)
point ∈ poly
```
And so does
```julia
point = Point(NaN32, NaN32)
point ∈ poly
```

Here is a quick screenshot as well:

<img width="380" alt="Screenshot 2024-01-27 at 10 53 21 AM" src="https://github.com/JuliaGeometry/Meshes.jl/assets/18745581/963ad475-6593-44db-84a7-6015a809d7f1">

**Comment by juliohm** [comment]
We do not support `Inf` or `NaN` coordinates currently. What is the use case you have in mind? What would be the meaning of `NaN` coordinates? I can think of coordinate systems where some coordinates are `Inf`, not sure we want to support this.

**Comment by markmbaum** [comment]
Ah ok. I found a work around, but I was initializing an infinite point before a while loop that updates the point coordinates, as part of an interaction with some other geometries.

Is it helpful to put checks for `Inf` and `NaN` coordiantes into the `Point` constructor? I don't think this would be obstructive for arbitrary coordinate types because the `isinf` and `isnan` functions can have methods for whatever types are needed. It would also flow through nicely to all the other geometries that construct points.

If so, happy to contribute.

**Comment by juliohm** [comment]
We also have internal algorithms that initialize the coordinates with `Inf` and then update (e.g. minmax). Given that this is a useful trick, we can allow this in the constructor for internal use. Maybe it is too early to support the `Inf` case in external use.

Let's reopen the issue later if necessary.
