### ISSUE TITLE
Point ∈ Sphere

### ISSUE THREAD

**Issue by markmbaum** [JuliaGeometry/Meshes.jl#722]
I'm noticing unexpected results when checking if a `Point` is inside a `Sphere`. In my case, for two dimensions, this example checking if a point at the origin is inside a sphere centered on the origin,
```julia
s = Sphere((0,0), 1)
p = Point(0,0)
p ∈ s
```
will return `false`.

<img width="319" alt="Screenshot 2024-01-30 at 11 37 05 AM" src="https://github.com/JuliaGeometry/Meshes.jl/assets/18745581/9dbf2323-706f-4c8b-b653-ef562fa54b1a">

**Comment by juliohm** [comment]
The `Sphere` is the `boundary` of the `Ball`. I think you want to check if a point is in the ball instead.

**Comment by markmbaum** [comment]
Ah...

thank you! my mistake
