### ISSUE TITLE
Stackoverflow when discretizing a `Cone`

### ISSUE THREAD

**Issue by orswan** [JuliaGeometry/Meshes.jl#757]
The following code should make a simple cone and display it: 

```
using Meshes
c = Cone(Disk(Plane(Point(0.0,0.0,0.0),Vec3(0.0,0.0,1.0)), 1.0), Point(1.0,1.0,1.0))
using MeshViz, GLMakie
display(viz(c))
```
But instead it throws 
```
StackOverflowError:

Stacktrace:
     [1] discretize(geometry::ConeSurface{Float64})
       @ Meshes C:\Users\anonc\.julia\packages\Meshes\uPQGa\src\discretization.jl:103
     [2] simplexify(geometry::ConeSurface{Float64})
       @ Meshes C:\Users\anonc\.julia\packages\Meshes\uPQGa\src\discretization.jl:130
--- the last 2 lines are repeated 39990 more times ---
 [79983] discretize(geometry::ConeSurface{Float64})
       @ Meshes C:\Users\anonc\.julia\packages\Meshes\uPQGa\src\discretization.jl:103
```

**Comment by juliohm** [comment]
Thank you for reporting the issue. We need to repeat the same process that was done with `Cylinder`, `ParaboloidSurface`, etc. These primitives can be discretized with `RegularDiscretization` and parametric coordinates.

**Comment by juliohm** [comment]
This is fixed on master. Now you get the expected visualization:

![image](https://github.com/JuliaGeometry/Meshes.jl/assets/3345261/d45a6518-3099-4200-81a0-86610eaee84f)
