### ISSUE TITLE
Add mesh quality metrics

### ISSUE THREAD

**Issue by serenity4** [JuliaGeometry/Meshes.jl#77]
At some point, we will most likely want to compare meshing algorithms. For the moment, we may want to only evaluate the quality of _triangulated_ meshes, to compare triangulation algorithms, but in the future other types of algorithms (e.g. quad meshing) may probably be implemented. Besides algorithmic time performance, there are many geometrical considerations that are of importance. This can be broken down into several characteristics. Here is a small general list to start with, which should be updated based on discussion and feedback:
- Mesh statistics:
  - [ ] Number of triangles (after triangulation, if considering non-triangle meshes).
  - [ ] Memory usage (for the total mesh; irrelevant between meshes with the same element types. Between triangle meshes with the same embedding dimension and coordinate type for example, it would be directly proportional to the number of elements.)
- Triangulation quality:
  - [ ] Sliverness (min, median, max)
- Application specific:
  - [ ] Number of poles
  - [ ] Number of involved edges in largest pole

In the scope of this package, this would be most relevant for testing, although I think some algorithms may directly benefit from this. External applications would definitely find this of interest.

**Comment by juliohm** [comment]
I think this is a very nice exercise that someone can do in a research paper. In terms of the development of Meshes.jl itself it is very low in the priority list, and not actually a new feature. Benchmarks can be run by the community if they are interested in learning more about these methods or interested in improving the current implementations.
