### ISSUE TITLE
Geometric primitives

### ISSUE THREAD

**Issue by serenity4** [JuliaGeometry/Meshes.jl#78]
There are a few geometric primitives already defined (ball, box, cylinder and sphere). Do we plan to complete this collection with other primitives (Bézier curves, splines, torus, circles...)? For example, I need to use Bézier curves, which are naturally defined from control points, should I make a PR to implement them here?

This is an open question. I would personally think that we may want to put everything in Meshes for now, and split parts of it later on when it becomes too big.

**Comment by juliohm** [comment]
I think it is a good addition. It is better to concentrate efforts here to
make sure we have nice interoperability and then later in the future we
split if needed.
