### ISSUE TITLE
Parameterization of a Torus with `minor > major`

### ISSUE THREAD

**Issue by mikeingold** [JuliaGeometry/Meshes.jl#789]
I stumbled onto this while testing a new surface integral function:

- A `Torus` can be constructed whose `minor` radii is greater than its `major` radii. Based on a quick reading of the Wikipedia page (IANA-geometer), it sounds like this is valid but sort of a special case.
- For such a `Torus`, the current parameterization code will error. Line 55 essentially takes `sqrt(t.major^2 - t.minor^2)`, which throws a `DomainError` since the argument is negative but also `<:Real`.

https://github.com/JuliaGeometry/Meshes.jl/blob/d52cc5e850a773d28e60bd43269ea33699de8774/src/primitives/torus.jl#L47-L63

I don’t know enough about how the parameterization here is derived to know whether the absolute value of the interior term could be taken first, or if parameterizing `Torus` with this property is a harder problem. It’s also non-obvious to me whether this type of `Torus` was even intended to be supported.

**Comment by juliohm** [comment]
@stla could you please take a look in this issue? Do I remember correctly that you added the Torus primitive last year?

**Comment by stla** [comment]
Yes, that's me. In fact, I implemented a non-usual parameterization of the torus, valid only for major > minor. I thought it was interesting because it is a conformal parameterization, but actually this is useless.

**Comment by juliohm** [comment]
What do you suggest in this case @stla? Should we adopt a different parametrization?

**Comment by stla** [comment]
Yes, we should adopt the classical parameterization (certainly given on Wikipedia).

**Comment by juliohm** [comment]
Appreciate if you can take a look into it. Otherwise, we can try to fix
ourselves when we find time. Do you have a link to the wiki page and
formula? That can speed things up.

Em qua., 28 de fev. de 2024 11:53, stla ***@***.***> escreveu:

**Comment by stla** [comment]
[Here](https://en.wikipedia.org/wiki/Torus#Geometry). I could do the modifications but not so soon.

**Comment by mikeingold** [comment]
This seems like it should be easy enough to re-implement. I’ll make an attempt at a PR for this.

**Comment by juliohm** [comment]
Fixed on master.
