### ISSUE TITLE
Set elements of CartesianGrid and RectilinearGrid using `Box` instead of `Hexahedron`

### ISSUE THREAD

**Issue by ehgus** [JuliaGeometry/Meshes.jl#793]
`Hexahedron` is very generic, so performing some operations on elements requires extra work. The `Box` element will reduce unnecessary computation and memory when representing the CartesianGrid and RectilinearGrid.

**Comment by juliohm** [comment]
@ehgus can you elaborate on the operations a bit more?

**Comment by ehgus** [comment]
`isconvex` is a case. It requires some computation to tell the input  `Hexahedron` is convex, but `Box` is convex by default.
Due to that, `intersects` will be affected because it uses `isconvex` inside.

**Comment by juliohm** [comment]
The main issue with `Box` is that it is not represented with a `Connectivity`. It only stores the corner points along the diagonal. The `Mesh` subtypes assume that the elements can be constructed from a `Connectivity` with the appropriate `Polytope` type.

We can review the design to see if an optimization is possible. If you see this as high priority, please feel free to go ahead and suggest some changes in a PR for review.

**Comment by juliohm** [comment]
@ehgus can you share a MWE with the latest master branch showing the use case with `intersects`? Perhaps we can simply add a special method with `CartesianGrid` as one of the inputs. The grid itself has to return Polytope geometries as elements, the Box is a Primitive, so this won't change unless we see a real use case that cannot be solved with the current design.

**Comment by juliohm** [comment]
I investigated this design change today, and confirmed that it introduces some issues. It requires adding `vertices` and `nvertices` to `Box`, which is non-natural for `Primitive` geometries. Many other methods that are implemented for `Hexadron` and `Quadrangle` would need an implementation for `Box` as well via explicit `convert`, and that can lead to code repetition and ambiguities with methods that receive `Polytope` and `Primitive` as arguments (e.g., `==`, `isapprox`).
