### ISSUE TITLE
Surface normal of a triangle should be normalized

### ISSUE THREAD

**Issue by cserteGT3** [JuliaGeometry/Meshes.jl#798]
In this line:

https://github.com/JuliaGeometry/Meshes.jl/blob/f229535b121fbde68144bf773be00b69d31f7807/src/polytopes/ngon.jl#L81

The cross product should be normalized, isn't it?

A very basic example:

```julia
julia> Triangle((0,0,0), (1,0,0), (0,1,0)) |> normal
Vec(0.0, 0.0, 0.5)
```

**Comment by juliohm** [comment]
We don't normalize because some algorithms benefit from the norm.

Em qui., 14 de mar. de 2024 10:59, cserteGT3 ***@***.***>
escreveu:

**Comment by cserteGT3** [comment]
Oh, okay. Thank you!
