### ISSUE TITLE
Viz command not working on domain

### ISSUE THREAD

**Issue by vetereb** [JuliaGeometry/Meshes.jl#812]
The documentation https://juliageometry.github.io/MeshesDocs/stable/visualization.html#Domains provides sample code for using the domain "CartesianGrid".  However, viz will not accept a CartesianGrid object.  It looks like some of the old MeshViz Makie recipes did not get ported over to Meshes.

**Comment by juliohm** [comment]
That is invalid for sure. The documentation is up-to-date and these Makie recipes are constantly used.

**Comment by vetereb** [comment]
(@v1.10) pkg> st
Status `~/.julia/environments/v1.10/Project.toml`
  [31a5f54b] Debugger v0.7.8
  [b305315f] Elliptic v1.0.1
  [e9467ef8] GLMakie v0.9.9
  [a98d9a8b] Interpolations v0.15.1
  [7031d0ef] LazyGrids v0.5.0
  [ee78f7c6] Makie v0.20.8
  [eacbb407] Meshes v0.41.1
  [e6723b4c] Meshing v0.6.0
  [695b2228] MobiDes v0.1.0 `../../../Library/Mobile Documents/com~apple~CloudDocs/Julia/MobiDes`
  [295af30f] Revise v3.5.14
  [6038ab10] Rotations v1.7.0
  [90137ffa] StaticArrays v1.9.3
  [a7f1ee26] Trixi v0.7.5
  [bc1476a1] Trixi2Vtk v0.3.13


julia> grid = CartesianGrid(10, 10, 10)
10×10×10 CartesianGrid{3,Float64}
  minimum: Point(0.0, 0.0, 0.0)
  maximum: Point(10.0, 10.0, 10.0)
  spacing: (1.0, 1.0, 1.0)

julia> viz(grid, showfacets = true, facetcolor = :teal)
ERROR: MethodError: no method matching viz(::CartesianGrid{3, Float64}; showfacets::Bool, facetcolor::Symbol)
Stacktrace:
 [1] top-level scope
   @ REPL[34]:1

julia> 

The code is copy paste from the doc.

**Comment by juliohm** [comment]
You did not import any Makie backend into the session.
