### ISSUE TITLE
`Affine` does not work with `CartesianGrid`

### ISSUE THREAD

**Issue by DylanMMarques** [JuliaGeometry/Meshes.jl#823]
`Affine` works in a unexpected way when used with `CartesianGrid`:  
```julia
aff = Affine([-1 0 ; 0 -1], [0, 0])
grid = CartesianGrid(10, 10)

grid |> aff
# 10×10 CartesianGrid{2,Float64}
#  minimum: Point(0.0, 0.0)
#  maximum: Point(10.0, 10.0)
#  spacing: (1.0, 1.0)
```
I was expected the output to be a grid from -10 to 0 in both dimension as computed if I use `aff(collect(grid))`

**Comment by juliohm** [comment]
Thanks for reporting @DylanMMarques , we are taking a look into it.
