### ISSUE TITLE
Use StableRNGs.jl for creating test data.

### ISSUE THREAD

**Issue by KristofferC** [JuliaGeometry/Meshes.jl#833]
In 1.10:

https://github.com/JuliaGeometry/Meshes.jl/blob/368b5d38826a8c49b0ac85a70aa2541ded912ba8/test/partitioning.jl#L4-L11

creates a different mesh from 1.11, where it creates

```julia
julia> p = partition(d, UniformPartition(100))
100 Partition
├─ 1 view(::CartesianGrid{2,Float32}, [36])
...
```

Relying on the exact numbers from the random number generator and exactly how things are printed is generally quite brittle when it come to test working over many julia versions.

Using StableRNGs.jl would make this a bit more stable.

**Comment by juliohm** [comment]
Thank you. We noticed it in our tests on Julia v1.11 beta. Will fix it soon.

**Comment by juliohm** [comment]
Fixed on master.
