### ISSUE TITLE
Miscellaneous issues to fix after major CRS refactor

### ISSUE THREAD

**Issue by juliohm** [JuliaGeometry/Meshes.jl#839]
## Urgent:

- [x] `normal` must be reviewed to return normalized normals for all geometries
- [x] review the role of `atol` in `Vec` `isapprox` comparisons
- [x] default tolerances in `PartitionMethod` should be based on `atol`
- [x] `show` of `BezierCurve` should be incorporated into generic `show`
- [x] review fields of structs to make sure they all have units when appropriate
- [x] review occurrences of `zero(lentype(p))^2`
- [x] `coordinates` returns a `Vec`, but should return the coordinates instead
- [x] fix occurrences of `Point(Vec(...))` in some algorithms

## Not urgent:

- [x] `rand` of `Point` should produce concrete types
- [x] `to` should work with any crs, converting to `Cartesian`
- [x] more flexible crs in `Grid` subtypes
- [x] propagate crs information in some algorithms
- [x] fix `Cone` and `ConeSurface` constructors with non-unitful args
- [x] review constructors of `Point`, `Vec` and `CRS` with `Tuple` and `SVector`
- [x] review distance interface in distances.jl
- [x] replace `@assert` by appropriate exception type
- [x] review occurrences of `SVector` in fields

**Comment by cserteGT3** [comment]
Just out of curiosity can I ask why was `@assert` replaced by the `assertion` function?

**Comment by juliohm** [comment]
From the docstring of `@assert`, the macro is not intended for logical checks in implementations, but merely for debugging purposes. One can disable it with runtime flags, but we don't want that. We are making sure that the `AssertioError` is thrown if a condition is not satisfied.

**Comment by cserteGT3** [comment]
Thank you for the explanation!

**Comment by juliohm** [comment]
All fixed on master.
