### ISSUE TITLE
Make parametric objects callable

### ISSUE THREAD

**Issue by serenity4** [JuliaGeometry/Meshes.jl#84]
Some geometric objects possess a natural parametric space. For example, segments linearly interpolate between two points, rays can be evaluated from the origin to the infinity, bezier curves can be evaluated between its endpoints... I had the idea of making these objects callable on their parametric inputs, so a segment could be called with `t` going from 0 to 1 to make a linear interpolation of its two points. Considering objects with a single parametric dimension it should be fine, unambiguous and easy to do. I can draft a PR to see how it goes for one-dimensional parametric objects.

When there is more than one parametric dimension, I am not sure how this should be implemented. For triangles, for example, it is possible to use barycentric coordinates (from 0 to 1), but also two-dimensional coordinates within a certain range (since this is a polygon after all, with parametric dimension 2). Feel free to comment if you have any ideas.

- [x] Segment
- [x] Ray
- [x] BezierCurve
- [x] Line
- [x] Triangle
- [x] Quadrangle

**Comment by juliohm** [comment]
Yes, it would be great to parameterize these geometries when this is possible. We can start with the ones of parametric dimension 1 as you suggested 👍🏽

**Comment by juliohm** [comment]
As an update, we currently have `Segment`, `Ray` and `BezierCurve` as callables.

**Comment by GuoHaoxuan** [comment]
For `Triangle` and `Quadrangle` is should be solved via barycentric coordinate system. (Same as `Segment`)

But in `Triangle`, it will has 2 parameters due to u+v+w=1. Which point is special that not included in the parameters in a triangle? Is it reasonable to use the 2 points in the front?

It is the same question in `Quadrangle`.

**Comment by juliohm** [comment]
@HaoxuanGuo the first two points of the triangle are a good simple choice :) Would you mind submitting a PR for that? We have barycentric coordinates in some methods like [this one](https://github.com/JuliaGeometry/Meshes.jl/blob/982b902e635c1789850400cdcd3b2781592c8c67/src/sampling/homogeneous.jl#L38-L44). If you could add a functor method to the `Triangle` with two arguments and could replace the function linked by a simple call with random arguments, that would be great.

I forgot to check the quadrangle case, it is already solved [here](https://github.com/JuliaGeometry/Meshes.jl/blob/982b902e635c1789850400cdcd3b2781592c8c67/src/polytopes/ngon.jl#L168-L171) 👌🏽
