### ISSUE TITLE
Methods for uconvert

### ISSUE THREAD

**Issue by VEZY** [JuliaGeometry/Meshes.jl#879]
It would be useful to add methods for converting units of Meshes objects (without changing the CRS). For example, if I want to convert a point with a cartesian CRS from meters to centimeters, I have to do this:

```julia
p = Point(1.0, 1.0, 1.0)
Point(uconvert.(u"cm", to(p))...)
```

But I think we would expect to use this:

```julia
p = Point(1.0, 1.0, 1.0)
uconvert(u"cm", p)
```

Or maybe I missed something.

**Comment by juliohm** [comment]
We probably need a transform to change the length units inside geometries and domains. It could be something like:

```julia
object |> LengthUnit(u"cm")
```

**Comment by VEZY** [comment]
That was fast! Thank you!
