### ISSUE TITLE
Cross-referencing `Meshes.jl` documentation

### ISSUE THREAD

**Issue by maltezfaria** [JuliaGeometry/Meshes.jl#886]
I was trying to use the setup suggested here

https://documenter.juliadocs.org/stable/man/guide/#External-Cross-References

to cross-reference a function from `Meshes` in my package's documentation, and I could not find the `objects.inv` inventory for the `Meshes.jl` documentation. From the link above

> Any project building its documentation with the most recent release of Documenter will generate an objects.inv inventory that can be found in the root of the [deployed documentation](https://documenter.juliadocs.org/stable/man/hosting/#Hosting-Documentation)

But somehow I could not find the inventory for `Meshes`. Am I doing something wrong?

Thanks.

**Comment by juliohm** [comment]
The docs are deployed in an external repository: https://github.com/JuliaGeometry/MeshesDocs

It is a non-standard setting to avoid polluting the source code repo with big image blobs.

**Comment by juliohm** [comment]
Feel free to continue the conversation on Zulip. Closing the issue.

**Comment by maltezfaria** [comment]
> The docs are deployed in an external repository: https://github.com/JuliaGeometry/MeshesDocs
> 
> It is a non-standard setting to avoid polluting the source code repo with big image blobs.

Thanks, I saw that the docs were deployed on a different repo, but I still did not find an `objects.inv` there. I will continue the discussion on Zulip, but for the reference in case someone else gets here: does that mean there is no `objects.inv` created for the Meshes documentation, or was I not looking at the right place?

**Comment by juliohm** [comment]
I don't know. This is a Documenter.jl question, better ask it there?

Em qui., 13 de jun. de 2024, 12:43, Luiz M. Faria ***@***.***>
escreveu:
