### ISSUE TITLE
`Scale` and `LengthUnit` transforms on geometries

### ISSUE THREAD

**Issue by cserteGT3** [JuliaGeometry/Meshes.jl#888]
I'm updating my code after the "unitful" update and found that transformations are not working as I expected on geometries. For example, `LengthUnit` only changes the point and vector units:

```julia
julia> LengthUnit(u"mm")(Sphere(Point(1,1,1)))
Sphere
├─ center: Point(x: 1000.0 mm, y: 1000.0 mm, z: 1000.0 mm)
└─ radius: 1.0 m
```

or `Scale` only scales the points, which is (for me at least) counterintuitive for spheres (I expect to change only the radius):

```julia
julia> Scale(2)(Sphere(Point(1,1,1)))
Sphere
├─ center: Point(x: 2.0 m, y: 2.0 m, z: 2.0 m)
└─ radius: 1.0 m
```

I think former is straightforward: the units of all fields should be updated. Scaling (and stretching) could be however controversial.

**Comment by cserteGT3** [comment]
In theory this would be enough for `LengthUnit`:

```julia
applycoord(t::LengthUnit, q::Quantity) = uconvert(t.unit, q)
```

**Comment by juliohm** [comment]
Thank you for reporting these issues @cserteGT3 , we will take a look.

**Comment by juliohm** [comment]
> or `Scale` only scales the points, which is (for me at least) counterintuitive for spheres (I expect to change only the radius):
> 
> ```julia
> julia> Scale(2)(Sphere(Point(1,1,1)))
> Sphere
> ├─ center: Point(x: 2.0 m, y: 2.0 m, z: 2.0 m)
> └─ radius: 1.0 m
> ```

In this case, the `Scale` of a `Sphere` will be a `Ellipsoid`, both the center and the radius change: https://juliageometry.github.io/MeshesDocs/stable/geometries/primitives.html#Ellipsoid

The `Stretch` only affects the radius.
