### ISSUE TITLE
Lines and Planes

### ISSUE THREAD

**Issue by juliohm** [JuliaGeometry/Meshes.jl#90]
Opening this issue to discuss the definitions and representations of lines and planes. The literature is vast on these objects and so we need to be careful to define something practical still. For some people, the term "line" refers to curved objects in non-Euclidean geometry. For others, a line is a straight line with parametric dimension 1. We need to list all these definitions we know, start giving them names, and finally agree on useful representations to implement.

**Comment by juliohm** [comment]
cc: @serenity4 @stillyslalom

**Comment by stillyslalom** [comment]
We might need one more parameter for `Geometry{Dim,T}` describing the type (`Euclidean`, `Elliptic`, `Hyperbolic`, `...`) of geometry being described, with appropriate primitives for each type of geometry.

**Comment by juliohm** [comment]
Yes, I think we need to be careful to not over-complicate things prematurely. The issue of non-Euclidean geometry is a world in itself. We need focus to handle the `Line` and `Plane` situation first.

Let me add the first definitions of Line and Plane I find useful:

1. A straight line is the set of all points expressed as `t*a + (1-t)*b` with `a` and `b` points and `t` a free parameter. Hence, in this definition, this object has parametric dimension 1.
2. A plane is the set of all points perpendicular to a given direction, including a given point of reference. In this case, the plane is an object with parametric dimension equal to the embedding dimension minus one.

Feel free to add alternative definitions. Let's try to concentrate on Euclidean geometries. All these exotic geometries where lines are not straight could be discussed in a separate issue in the future. We are too young to enter this world in my opinion.

**Comment by stillyslalom** [comment]
A plane can be given parametrically as the set of points expressed as `p₀ + a*u + b*v`, with `p₀` a point, `a` and `b` vectors, and `u, v` free parameters. Under this notion, the plane has parametric dimension 2 (this is the notion I had in mind for https://github.com/JuliaGeometry/Meshes.jl/pull/88).

Spherical geometry is a subset of elliptic geometry, and it seems important to handle at least spherical geometry robustly for geospatial applications.

**Comment by juliohm** [comment]
Nice. Let's keep adding definitions and then we can give time to digest all the alternatives and design decisions. It is nice to have a group of people thinking about it.

**Comment by serenity4** [comment]
The nature of geometries (Euclidean, non-Euclidean) has to do with how distance between two points is measured. I would define a line as the geodesic joining two points (the shortest path in terms of distance). With this definition, we get straight lines in Euclidean geometry, and the curved lines in non-Euclidean geometry. Well, this is only useful at the condition that we use the right distance function when we do any operations on line objects, of course. If we want to support non-euclidean geometries in a natural way using multiple dispatch, we'd need to revisit all our assumptions that the shortest path between points is straight. Which would imply that locally parallel lines don't stay parallel, unless the geometry is Euclidean. This would indeed need a lot more thinking, and I think we need the right tools before we dive into it. Obviously, many standard results don't apply, and if you want a generic solution you may want to use geometric algebra. It could let you change your geometry from Euclidean to Elliptical/Hyperbolic with only a parameter change. At some point, if/when we rely on geometric algebra for common operations such as intersections, it would be natural to consider adding non-Euclidean geometries ([here](https://bivector.net/3DPGA.pdf) is a taste of all geometric algebra could offer).
So, for an Euclidean geometry, a geodesic between two points is exactly a straight line conveniently described as

> A straight line is the set of all points expressed as `t*a + (1-t)*b` with `a` and `b` points and `t` a free parameter.

Although I would restrict `t` between 0 and 1 to stay coherent with the definition above. It can be extended to infinite lines, which is naturally done via letting `t` be outside `[0, 1]`.
As a side note, in spherical geometry, infinite lines are circles.

> A plane is the set of all points perpendicular to a given direction, including a given point of reference. In this case, the plane is an object with parametric dimension equal to the embedding dimension minus one.

This is the definition of a [hyperplane](https://en.wikipedia.org/wiki/Hyperplane). A plane is only two-dimensional. Take R2 for example, the whole space is a plane and we shouldn't have to consider it as such only if embedded in R3.

> A plane can be given parametrically as the set of points expressed as `p₀ + a*u + b*v`, with `p₀` a point, a and b vectors, and `u, v` free parameters.

I think this is a good definition. It can also be seen as a sphere with infinite radius, which can be more naturally represented in a conformal space, but the former definition provides a natural parametric evaluation, as done in #88. I would suggest adding at least two constructors: one taking three points as input, and one taking a normal vector and an initial point as @juliohm suggested on the PR.

**Comment by stillyslalom** [comment]
> I would suggest adding at least two constructors: one taking three points as input, and one taking a normal vector and an initial point as @juliohm suggested on the PR.

The constructor for three points is straightforward, but not so much for the point-normal form, since it leaves the orientation of the plane's component vectors indeterminate. I arrived at a deterministic solution, but it's a bit ugly, and I'd be happy to take suggestions.
```
function Plane(p::Point{3,T}, n::Vec{3,T}) where {T}
  eᵢ = Vec(one(T), 0, 0), Vec(0, one(T), 0), Vec(0, 0, one(T))
  i = last(findmin([abs(n ⋅ e) for e in eᵢ]))
  w = n × eᵢ[i]
  v = -(n × w)
  Plane(p, v, w)
end
```

**Comment by juliohm** [comment]
I believe we already addressed the concrete issue here, which is the representation and construction of lines and planes.

The remaining discussion is still too open and about non-Euclidean geometries and geometric algebra. I will close the issue and we can open a separate one in the future when we start to work on such generalizations.
