### ISSUE TITLE
SutherlandHodgman not handling overlapping line intersections

### ISSUE THREAD

**Issue by jnemanja** [JuliaGeometry/Meshes.jl#950]
In the `clip` function of the sutherlandhodgman.jl file, an intersection between lines is being pushed to a vector of points. This is fine as long as the intersection between lines is crossing and a point is returned. However, the intersection can be overlapping when a line is returned, resulting in an exception. Admittedly, this only happens after I override `Meshes.atol(::Type{Float64}) = 1e-13` (which I need to avoid a different intersection problem). Still, it looks like this needs updating. I have a fix which in case of an overlapping intersection, pushes only the first point of the line. I am no quite sure if that is sufficient, I do not know if the returned line is always conveniently oriented to be able to always select the first point.

**Comment by juliohm** [comment]
Hi @jnemanja can you please share a MWE? Thanks for reporting the issue.

Em sáb., 20 de jul. de 2024, 13:23, jnemanja ***@***.***>
escreveu:

**Comment by jnemanja** [comment]
Here it is. Reproducible without overriding the `atol`.

```
p1 = Ngon(Point(0.0, 0.0), Point(0.0, 1.000000000000001), Point(1.0, 1.0))
p2 = Ngon(Point(0.0, 1.0), Point(0.0, 2.0), Point(1.0, 1.000000000001))
intersection(p1, p2)
```

**Comment by jnemanja** [comment]
I forgot to mention another part of the problem. It might even be an issue on its own, but probably it needs fixing for this issue to be properly fixed. When two overlapping lines are intersected, it just returns the first line instead of returning the line with two innermost points.

This:
```
l1 = Line(Point(0.0, 0.0), Point(2.0, 0.0))
l2 = Line(Point(1.0, 0.0), Point(3.0, 0.0))
get(intersection(l1, l2))
```
returns `Line(Point(0.0, 0.0), Point(2.0, 0.0))` instead of `Line(Point(1.0, 0.0), Point(2.0, 0.0))`.

**Comment by juliohm** [comment]
@jnemanja regarding your example with `Line`, you probably need `Segment`:

```julia
julia> s1 = Segment((0, 0), (2, 0))
Segment
├─ Point(x: 0.0 m, y: 0.0 m)
└─ Point(x: 2.0 m, y: 0.0 m)

julia> s2 = Segment((1, 0), (3, 0))
Segment
├─ Point(x: 1.0 m, y: 0.0 m)
└─ Point(x: 3.0 m, y: 0.0 m)

julia> s1 ∩ s2
Segment
├─ Point(x: 1.0 m, y: 0.0 m)
└─ Point(x: 2.0 m, y: 0.0 m)
```

If you are coming from the GIS world, you will have to unlearn this incorrect naming.

I will try to take a look into your original MWE above soon.

**Comment by juliohm** [comment]
@jnemanja we can reduce your MWE to the following intersection between `Line`s:

```julia
julia> l1
Line
├─ a: Point(x: 0.0 m, y: 1.0 m)
└─ b: Point(x: 1.0 m, y: 1.000000000000001 m)

julia> l2
Line
├─ a: Point(x: 1.0 m, y: 1.0 m)
└─ b: Point(x: 0.0 m, y: 1.000000000000001 m)

julia> 
julia> l1 ∩ l2
Line
├─ a: Point(x: 0.0 m, y: 1.0 m)
└─ b: Point(x: 1.0 m, y: 1.000000000000001 m)
```

As you can see, these two lines are equal up to machine tolerance (i.e., `Meshes.atol`). You can find the exact algorithm that leads to this result here:

https://github.com/JuliaGeometry/Meshes.jl/blob/60996c48b59a795ebccec187e5d2fc52e38e02b5/src/intersections/lines.jl#L5-L23

As you can see, the algorithm is very simple to read and understand. What do you think we should do in this case?

**Comment by jnemanja** [comment]
Ah right, a silly misunderstanding on my part there for line and segment distinction. I'm not even from the GIS world, so it's a learning and not unlearning opportunity. However, does this still expose a problem in the SutherlandHodgman method? The method should use segments instead of lines, or it could produce malformed intersections.

**Comment by juliohm** [comment]
@jnemanja I commented above with more information. The Suthreland-Hodgman algorithm uses `Line`s. The issue you are facing is related to floating point errors.

**Comment by juliohm** [comment]
Here are a few suggestions:

1. Consider cleaning up your geometries if that is possible. We have some `Repair` algorithms implemented that you can check in the docs.
2. Consider testing alternative clipping algorithms such as the ones described in https://github.com/JuliaGeometry/Meshes.jl/issues/578. We didn't have to implement them yet, and contributions are very welcome.

Please let me know if you need further help. I will mark the issue as invalid, given that it is not an issue of the clipping implementation. Our Zulip channel is a nice place to chat too.
