### ISSUE TITLE
Preserve order between input points and output polygons in VoronoiTessellation

### ISSUE THREAD

**Issue by disberd** [JuliaGeometry/Meshes.jl#974]
Hi,

I was playing around with the Voronoi tessellation and noticed that despite having one polygon generated for each point in the provided initial vector, the order of the output polygons is completely disconnected from the order of the input points.

I have checked the code internally and this would seem to be quite trivial to solve (either by default, or hopefully via a flag/kwarg to `tessellate` if for some reason an ordered output is considered not a good default).

The problem seems to stem from line 42 in the relevant `tessellate` function body:
https://github.com/JuliaGeometry/Meshes.jl/blob/05cbd2060d69941ba9094f6f629b82b4b5849093/src/tesselation/voronoi.jl#L34-L43

which simply calls `values(vorono.polygons)`, with `vorono.polygons` being a `Dict` with the indices of the starting points as `Key` and the indices of the polygon vertices as values.

Despite the order information being present the original `Dict`, the value iterator coupled with the unordered nature of `Dict` creates the specific issue.

Would you be willing to accpet a PR to either change the default to have ordered output or at least add a flag to enable it?

The solution I tried with a flag was to simply add the following two lines after line 43 in the code above
```julia
 if sorted
  	original_idxs = keys(vorono.polygons) |> collect
	invpermute!(tuples, original_idxs)
 end
```

In an actual PR it would be best to directly import and use the `each_polygon_index` function from the `DelaunayTriangulation` package rather than doing `keys(vorono.polygons)`.

I think this sorting will necessarily add a few allocations but `tessellate` already allocates quite a lot already and the impact in timing seemed to be negligible  from my very limited test

EDIT: preallocating the tuples vector and directly iterating over the dict pairs to assign the polygon vertices to the correct index will likely make this sorted output have no more allocations than the current approach

**Comment by juliohm** [comment]
Hi @disberd this fix would be very welcome. It is good to retain order of points as much as possible.

**Comment by juliohm** [comment]
Fixed on master.
