### ISSUE TITLE
Fibonacci lattice as additional sampling method

### ISSUE THREAD

**Issue by mcontim** [JuliaGeometry/Meshes.jl#979]
Hi,

I was looking at the available sampling algorithms in the package and I was wondering if it would be of interest adding an area preserving method for evenly distributing points on a sphere. I'm currently using the Fibonacci lattice for this task.

Let me know if you think this could be an interesting addition, so I can propose an implementation :)

**Comment by juliohm** [comment]
Hi Matteo, thanks for considering a contribution. You mean a new method for
the HomogeneousSampling?

Em seg., 5 de ago. de 2024, 04:49, Matteo Conti ***@***.***>
escreveu:

**Comment by mcontim** [comment]
Hi @juliohm!

Yes exactly, you're for sure more familiar than me with this method but here a quick reference: https://observablehq.com/@meetamit/fibonacci-lattices

That would be nice in order to have a "tesselation method" for the sphere, avoiding more complicated implementations like the icosahedral Goldberg polyhedra.

I work in SatCom and for example I use the Fibonacci lattice on a sphere to obtain a "grid" of points regularly distributed (preserving density per area) on Earth to collect statistics (of course here there is an approximation when you translate to lat-lon on the ellipsoid).

**Comment by juliohm** [comment]
That is great @mcontim. Appreciate if you can submit a PR for review. We need to figure out if this is a new case of the `HomogeneousSampling` or if it requires a new sampling method.

I understand that this algorithm you are interested in is deterministic, even though we can create some randomness as explained here: https://www.johndcook.com/blog/2023/08/12/fibonacci-lattice/

Let's brainstorm the best place in the PR.

**Comment by mcontim** [comment]
Thank you @juliohm for the quick reaction! 
I iwll submit a PR, then we can discuss on how to proceed :)

**Comment by juliohm** [comment]
@mcontim I think this method deserves a new `FibonacciSampling` struct. It works on various geometries as shown in the link you shared. It could be deterministic instead of random.

Did you have a chance to take a look into it?

**Comment by mcontim** [comment]
@juliohm I'm planning to work on the PR in the next couple of days (it was a busy week of coding this one :D ).

I agree on the new `FibonacciSampling` struct, however, I think the sampling will be a method limited to the only `Sphere` and `Ball`.

**Comment by juliohm** [comment]
> I think the sampling will be a method limited to the only `Sphere` and `Ball`.

Thank you @mcontim, you mean that you only have time to contribute the `Sphere` case, right? That is nice already. Let me know if you need assistance with the codebase. Try to follow the code style as much as possible from the other sampling methods.

**Comment by davibarreira** [comment]
Hey, @juliohm . I've implemented this for Disk and Sphere. Does the PR usually comes together with an updated docs, or are docs PR done separately?

**Comment by juliohm** [comment]
Please feel free to add docs in the same PR. It is nice to see examples.

Em sex., 27 de set. de 2024, 16:37, Davi Sales Barreira <
***@***.***> escreveu:
