### ISSUE TITLE
Documentation examples

### ISSUE THREAD

**Issue by juliohm** [JuliaGeometry/Meshes.jl#99]
Following the work initiated by @atreyamaj , we need more examples in the documentation. Here is a list of features that we could illustrate with plots:

- [x] Douglas-Peucker simplification of polygonal chains and areas
- [x] Migrate partitioning and sampling examples from GeoStats.jl to here

PRs are very welcome.

**Comment by juliohm** [comment]
@atreyamaj are you still interested in contributing more examples to the documentation?

**Comment by atreyamaj** [comment]
> @atreyamaj are you still interested in contributing more examples to the documentation?

I am interested!
 I'm a bit caught up with some uni work, I'll start working as soon as my load lightens up a bit!

**Comment by juliohm** [comment]
Fixed on master.
